### ISSUE TITLE
We're moving to GitHub for API help!

### ISSUE THREAD

**Issue by rectifyer** [trakt/api-help#1]
As you likely know, Google+ is shutting down soon and that means the existing API community over there will be going away soon. We considered several options and decided to use GitHub for API help moving forward. Trakt API devs are likely familiar with GitHub already, and we can clearly label any issues and questions that are posted here.

If you want to be notified of new posts or when you're @mentioned in a conversation, make sure to **Watch** this repo (top right). Thanks for all the great apps and projects you've all created using the **Trakt API**!

**Comment by clschnei** [comment]
Settings page is still showing G+ link. Should it be updated?

<img width="906" alt="screenshot" src="https://user-images.githubusercontent.com/1232625/51012060-36dff480-1529-11e9-9274-02dfff06e598.png">

**Comment by rectifyer** [comment]
You were just slightly ahead of me, the website should be all updated now :)

**Comment by tysonkerridge** [comment]
@rectifyer I just came across something which might be the answer to getting an export/archive of the Google+ posts/comments. https://plus.google.com/+FriendsPlusMe/posts/jSFYkqFBMJZ

> Hi Everyone,
> 
> We've just released Google+ Exporter, an application that helps you to export your Google+ feeds (profile, pages, collections, communities, including all comments) to Wordpress 4.x and 5.x Backup, Blogger Backup and JSON file.
> 
> Download latest Google+ Exporter version from https://gplus-exporter.friendsplus.me
> 
> Another available option is to export all posts published to profile, pages, collections, and communities to JSON file, including all comments!
> 
> More details on Google+ Exporter web site https://medium.com/google-plus-exporter
> 
> Transform exported JSON data can into imports for other services, or you can use JSON export as a full generic backup of your posts.
> 
> The free version of the application enables you to download up to 800 posts per every single Google+ feed (profile, page, collection, community). You can buy a license key to get unlimited experience.

**Comment by kgbm3** [comment]
Btw., apparently, "Your Google+ account is going away on April 2, 2019" @
https://support.google.com/plus/answer/9195133?hl=en

(I know, we know..:))

**Comment by AmineI** [comment]
@tysonkerridge There's an official way for the admin of the community though - 

>If you're a Google+ Community owner or moderator, you may download and save your data for your Google+ Community. Starting early March 2019, additional data will be available for download, including author, body, and photos for every community post in a public community. 

https://support.google.com/plus/answer/1045788#communities
