### ISSUE TITLE
Twice as many entries returned when limit is provided.

### ISSUE THREAD

**Issue by powlo** [trakt/api-help#101]
Reproduction:

GET https://api.trakt.tv/search/movie?query=tron&limit=1

returns:

```
[
  {
    "type": "movie",
    "score": 1000,
    "movie": {
      "title": "Tron",
      "year": 1982,
      "ids": {
        "trakt": 66,
        "slug": "tron-1982",
        "imdb": "tt0084827",
        "tmdb": 97
      }
    }
  },
  {
    "type": "movie",
    "score": 708.06775,
    "movie": {
      "title": "TRON: Legacy",
      "year": 2010,
      "ids": {
        "trakt": 12601,
        "slug": "tron-legacy-2010",
        "imdb": "tt1104001",
        "tmdb": 20526
      }
    }
  }
]
```

Expect: The number of items in the list returned to equal the limit specified.

Actual: The list is twice the limit provided.

Reference: 
https://trakt.docs.apiary.io/#reference/search/text-query
https://trakt.docs.apiary.io/#introduction/pagination

**Comment by rectifyer** [comment]
Behind the scenes it actually runs 2 separate searches, one for the exact title match and another that searches all the other fields. That is why it's adding another entry to the front of the result set. I'm not sure I can control this any better.
