### ISSUE TITLE
Season translations

### ISSUE THREAD

**Issue by minas1** [trakt/api-help#107]
I've noticed that there's no API endpoint for getting the translation of a season - **not the episodes of the season**, but the season's overview and title.

**Comment by rectifyer** [comment]
We don't currently store any translated info for seasons.

**Comment by minas1** [comment]
Are there plans to do so?

**Comment by rectifyer** [comment]
Better later than never 😄 I'll release this next week and we'll start saving season translations from TMDB. Data will fill in as shows get refreshed data from TMDB.

https://trakt.docs.apiary.io/#reference/seasons/translations/get-all-season-translations
