### ISSUE TITLE
Unable to sign-in on ios13

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#114]
Hello,

On iOS 13, the login page does not redirects to my custom url scheme. 
It may be related to this issue "https://forums.developer.apple.com/thread/119186" ?

Can you help me on this matters please !

**Comment by jonathanantoine** [comment]
Sorry, this was not related to trakt at all. Have a nice day !

**Comment by DevonJerothe** [comment]
Sorry to bring up an old issue but do you mind telling me what it was? Im all of a sudden having this issue custom schemes and deeplinks are no longer redirecting rather just refreshing the call.
