### ISSUE TITLE
Something is wrong with people trakt ids

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#115]
Did a search for Quentin Tarantino. Got `23` as trakt id. Then when I get more info with the trakt id `23` I get another person: 

https://trakt.tv/people/quentin-tarantino -> OK 
https://trakt.tv/people/23 -> NOK

Is it a linking/db issue? Should I use slug for people instead of trakt ids?

**Comment by rectifyer** [comment]
Looks like there is a bug with Trakt ID lookup in the API. I'll have a fix out later today and thanks for the info!
