### ISSUE TITLE
Likes for comments and lists

### ISSUE THREAD

**Issue by kimdv** [trakt/api-help#119]
Is there a way where I can sync likes for comments and lists?

I see that the trakt website have `likes_comments` and `likes_lists` 🚀

**Comment by kevincador** [comment]
It's available and documented here: https://trakt.docs.apiary.io/#reference/users/likes/get-likes

You can filter to get only comments or only lists otherwise you can use the `type` in the response.

**Comment by kimdv** [comment]
Is there a way to get all items? 
Like the watchlist or something like that? 

Otherwise I have to iterate trough it? 😬

**Comment by kevincador** [comment]
From this endpoint, you can get all the likes a user made. The information can't be cached efficiently otherwise. You need to keep that data your side and match it with the list of comments you get from other endpoints.

**Comment by kimdv** [comment]
I read the docs wrong, pagination is optional. 

Thanks!
