### ISSUE TITLE
List of supported Languages and Countries in API Filters

### ISSUE THREAD

**Issue by eliehaykal** [trakt/api-help#12]
Hello Team,

Is there any predefined list of country and language symbols we could use?

The obvious ones include: 
us, gb, it, pt, es

Thanks

**Comment by rectifyer** [comment]
Added 2 new API methods.

/countries/:type
https://trakt.docs.apiary.io/#reference/countries

/languages/:type
https://trakt.docs.apiary.io/#reference/languages

**Comment by henrikfroehling** [comment]
I think the link https://trakt.docs.apiary.io/#reference/languages/list/get-countries should be called "get-languages"?
