### ISSUE TITLE
try import tv series from tvdb

### ISSUE THREAD

**Issue by holbalzs** [trakt/api-help#123]
I try to import tv series form tvdb, the series is existing both tvdb(262029) and tmdb.
After pressed import the webpage drop me on to search page but not find the series.

**Comment by Paynmayn** [comment]
I think the tv series importer requires English title on TVDB to be imported. Looks like it has that now and it has been imported to Trakt.TV: https://trakt.tv/shows/the-edge-of-truth

**Comment by rectifyer** [comment]
TVDB released their v3 website and architecture last weekend, which caused some import issues. Should be working ok now.
