### ISSUE TITLE
Endpoint to get MY PRIVATE lists containing a movie?

### ISSUE THREAD

**Issue by javikr** [trakt/api-help#124]
Is there any endpoint that returns my private lists containing a movie?

I know that there is an endpoint (https://trakt.docs.apiary.io/#reference/movies/lists/get-lists-containing-this-movie) that it shows ALL COMMUNITY lists containing a movie, but there is no way (or I don't know) to filter only by MY PRIVATE lists.

Is there any endpoint or parameter to perform this? If not... how we can proceed?

Thanks,

**Comment by tysonkerridge** [comment]
I don’t think this is directly possible via the API. You’d have to sync your lists and their list items and then do a look up based on that data.

Eg 
List A with items 1,2,3
List B with items 1,4,5
List C with items 6,7,8

Look up item 1, and find it references List A and B. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by javikr** [comment]
Hi @tysonkerridge,
The problem with this solution is the performance and the number of requests: First I need to make a request to obtain all user lists, then for each list a request to get all list items, and then, look up for the movie...

Anyway, thanks for your answer ;)

**Comment by tysonkerridge** [comment]
No worries. Yeah, I guess it depends on your use case. 

If you were to use my suggestion, the “last activities” will allow you to keep lists up to date and only fetch changes when necessary. Then lists have an individual “updated at” I think, which you can use to only get items again when necessary. Then once it’s cached, while more manual effort involved by the client/app, the performance is negated and faster than any API call would be. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rectifyer** [comment]
Yes @tysonkerridge is correct and we recommend caching all the lists locally in your app for the signed in user. This way, you can do all the checks locally and it decreases the API hits needed by a lot.
