### ISSUE TITLE
Dates of "End of the F***ing World" S2 is corrupted

### ISSUE THREAD

**Issue by internalG** [trakt/api-help#125]
https://trakt.tv/shows/the-end-of-the-f-ing-world/seasons/2
https://www.themoviedb.org/tv/74577-the-end-of-the-f-king-world/season/2?language=en-US

Dates on TMDB are 2 episodes every day after. Trakt only has 2 dates. I saw the trakt is consist with TMDB before, but sometime it lost somewhere.

**Comment by rectifyer** [comment]
We use air dates from TVDB, and it looks to match up with what they have.

https://www.thetvdb.com/series/the-end-of-the-f-ing-world/seasons/official/2

**Comment by internalG** [comment]
Thanks. It seems the TMDB dates are better, but there's no time for episode?

**Comment by rectifyer** [comment]
We use TVDB as the first source. Air dates come from the episodes and air time comes from the show level. If the air date is blank on TVDB, we then use TMDB for that info. TMDB doesn't have air time so TVDB is the only source for that.
