### ISSUE TITLE
I need to pull my own unwatched episodes of a specific show

### ISSUE THREAD

**Issue by greatvc** [trakt/api-help#126]
Hi,
I really do not know where to post this, i tried the vip.trakt.tv but it is down all day. Also i read the api guide but even though i have a bit of coding experience on this am totally lost on where to start.

If i understood this correctly i can call a URL and return an .xml or other structure format of what i want.
I need to be able to get a list of unwatched and collected episodes (the collected option is so i do not get future unaired ones as unwatched) of a specific show.

Can someone provide the link or what to do. 
For example on the show Goldbergs (2013), i have half season 6 and season 7 as unwatched so i need to get for example:

Goldbergs 6x21
Goldbergs 6x22
Goldbergs 7x1
Goldbergs 7x2
etc

I don't care of the output, the number of the episode "21", or "22" is enough i will fix this and get my stuff from my VB6 application that i need for personal tracking. Yes VB6, i'm that old :nerd_face: 

I need a serious help boost on this.

Many Thanks in Advance

**Comment by greatvc** [comment]
ok, i have read some stuff on the api wiki and try some things. Of course with no success :cry: 

1. Created the api
![My eikona](https://i.imgur.com/NwaaCn0.png "Eikona")

2. Got the auth and register the device (?) the web page ? something
![My eikona](https://i.imgur.com/X4ZClhA.png "Eikona")

3. Registration is successful
![My eikona](https://i.imgur.com/IihNIAp.png "Eikona")

4. Tried to call my shows list of 2019-11-1, 7 days program, error 401.
![My eikona](https://i.imgur.com/lE7Vdqq.png "Eikona")

So how dump or off am i ?

Many thanks,
Vassilis

**Comment by rectifyer** [comment]
A 401 error means the OAuth (Authorzation header) is invalid. You need to do step 3 listed at https://trakt.docs.apiary.io/#reference/authentication-devices to exchange the `device_code` for an `access_token`. Then use the `access_token` and it should work.

**Comment by greatvc** [comment]
> A 401 error means the OAuth (Authorzation header) is invalid. You need to do step 3 listed at https://trakt.docs.apiary.io/#reference/authentication-devices to exchange the `device_code` for an `access_token`. Then use the `access_token` and it should work.

Ok, i made progress :laughing: 

I used the correct device code and access token and got the results from this
![My eikona](https://i.imgur.com/Big6i60.png "Eikona")

I got correct results now!
Now which parameters (codeids) should i pass to diplay the unwatch episodes of "https://trakt.tv/shows/the-goldbergs-2013" **AND that are status collected.**

Many thanks !!
Vassilis

**Comment by greatvc** [comment]
ok i did it !

FYI, the python code in the site is using urllib2 which is depreciated in python 3.x the correct one is:

```
import urllib.request
req = urllib.request.Request('https://api.trakt.tv/shows/<showname>/progress/watched?hidden=false&specials=false&count_specials=false')
req.add_header('authorization', 'Bearer [access token]')
req.add_header('trakt-api-version', '2')
req.add_header('trakt-api-key', '[api key]')
arxeio=open("c:\Watched.txt","w")
with urllib.request.urlopen(req) as f:
	#title= print(f.read().decode('utf-8'))
	arxeio.write(f.read().decode('utf-8'))

arxeio.close
```

I also made write the output to a file so that you can access it and work it from any dev language you want.
