### ISSUE TITLE
401 on private user's lists

### ISSUE THREAD

**Issue by JumBay** [trakt/api-help#127]
Hi,

Trying accessing a private user's lists will return a `401` error, even if authenticated, instead of a `403`.
Example: `https://api.trakt.tv/users/wakodemo/lists`

**Comment by rectifyer** [comment]
Please post the full request and response, including all headers. A `401` means the OAuth credentials don't have access to view that list.

**Comment by JumBay** [comment]
I may have forgotten to mention that I'm not the owner of the list, that's why the access is forbidden for me. The behavior is as expected (no access to the resource) but the `401` code returned, while authenticated, is "wrong". It should return a `403` forbidden code. 
The common practice when you receive a `401` code is to logout the user because his token is not valid anymore.

**Comment by rectifyer** [comment]
A `403` is currently reserved for an invalid application api key, so we can't really use that in this case. Along with the `401` there is a `X-Private-User` header that is also sent. If that is set to `true`, maybe that can help determine this use case?
