### ISSUE TITLE
Watched movies endpoints (eg. sync/watched) not updating

### ISSUE THREAD

**Issue by tysonkerridge** [trakt/api-help#130]
I seem to be seeing issues (and receiving reports from users) with the Watched movies endpoints not returning the correct data after adding a movie to your history, even though the last activities data is updated and the history endpoint returns the plays as expected. It causes the app to not display the item as watched due to using the plays being more than 0 as the check and to display the number etc.

example calls to reproduce (some JSON filtered to minimum):
GET sync/watched/movies (using an account with all history deleted) as expected
```
[]
```
GET sync/last_activities - response as expected (filtered)
```
{
    "all": "2019-12-22T01:46:17.000Z",
    "movies": {
        "watched_at": "2019-12-22T01:46:17.000Z"
    }
}
```
POST sync/history with body: `{"movies":[{"ids":{"trakt":120}}]}` (The Dark Knight) - response as expected (filtered)
``` 
{
    "added": {
        "movies": 1
    }
}
```
GET sync/last_activities - response as expected (filtered)
```
{
    "all": "2019-12-22T01:46:45.000Z",
    "movies": {
        "watched_at": "2019-12-22T01:46:45.000Z"
    }
}
```
GET sync/history - response as expected
```
[
    {
        "id": 3373625117,
        "watched_at": "2019-12-22T01:46:45.000Z",
        "action": "watch",
        "type": "movie",
        "movie": {
            "title": "The Dark Knight",
            "year": 2008,
            "ids": {
                "trakt": 16,
                "slug": "the-dark-knight-2008",
                "imdb": "tt0468569",
                "tmdb": 155
            }
        }
    }
]
```
**GET sync/watched/movies - response NOT expected**
```
[]
```
Instead I expect to see something like:
```
[
  {
    "plays": 1,
    "last_watched_at": "2019-12-22T01:46:45.000Z",
    "last_updated_at": "2019-12-22T01:46:45.000Z",
    "movie": {
      "title": "The Dark Knight",
      "year": 2008,
      "ids": {
        "trakt": 120,
        "slug": "the-dark-knight-2008",
        "imdb": "tt0468569",
        "tmdb": 155
      }
    }
  }
]
```

**Comment by eliehaykal** [comment]
You are not alone. I'm facing the same issue.

**Comment by javikr** [comment]
Yes. It is not working now for movies :(

**Comment by rectifyer** [comment]
I will look into this tomorrow, but just a few follow up questions. Does this only affect movies? Does the data eventually show up?

**Comment by tysonkerridge** [comment]
@rectifyer Yeah it seems to only affect movies, and yeah it seems to show up eventually (so some caching related issue I guess)

**Comment by Crowley007** [comment]
For me, it also affects TV series and has been going on for a week or two, on and off. Right now I have problem with emby trrakt plugin, it finishes without errors but does not get any watched status from trakt, neither movie or TV-series.

Some time  ago I had similar problems with Kodi trakt plugin.

**Comment by tysonkerridge** [comment]
Yeah I guess I haven’t noticed it happening with Shows but my app isn’t as reliant on the Watched endpoint for shows (in comparison to movies) as it uses show progress instead so would be less obvious too. From a quick check it doesn’t currently seem to be happening for shows, for me, but if it‘s intermittent I can’t be sure. Movies appears to be more consistently incorrect and more obvious due to how it’s used.

**Comment by rectifyer** [comment]
I just pushed a fix for this issue, it only affected movies. TV shows didn't seem affected in my tests, so I'd need more info and a specific use case to test that out.

**Comment by Crowley007** [comment]
Well, my basic use case is this.

1. Watch a movie/episode with Kodi
2. Kodi updates trakt with watched status
3. Emby trakt plugin imports watched status from trakt. <- This has not worked for me for days.

Right now, number 2 seems to work fine, but I did have problems with that earlier this month.

And perhaps due to your fix, Emby now does get watched states from movies, but not from TV shows.

**Comment by tysonkerridge** [comment]
The issue seems to be fixed as far as I can tell. I’m going to close this issue. @Crowley007, perhaps if you’re still having other issues you can create a specific github issue for those? Sounds like the issues you’re having might be related to the third party plugins etc rather than the actual API so you might need to get in touch with those developers directly otherwise. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Crowley007** [comment]
Yeah, I have reported the issue to emby forums as well.  But the fact remains that right now movies work and shows do not. Seems like a weird coincidence if it's not the same issue.
