### ISSUE TITLE
409 status code when deleting a comment

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#131]
I'm having a 409 status code while trying to delete a comment.

`DELETE https://api.trakt.tv/comments/243317`

What can I do? What is the issue?

**Comment by rectifyer** [comment]
The `409` means is returned because of this:

> The comment must also be less than 2 weeks old or have 0 replies. If not, a `409` HTTP status is returned.

**Comment by kevincador** [comment]
Okay, I didn't read the documentation well enough. I'm going to handle that correctly from my app 😅

What's the way to do it then? I have a comment I'd like to delete because it has not been added to the right episode. Should I flag it?

**Comment by rectifyer** [comment]
Yeah, flag it and we can remove it. There isn't a way to delete comments unless the above conditions are true.

**Comment by kevincador** [comment]
Okay. Flagged https://trakt.tv/comments/243317

I'll add a warning in the app saying they should flag from the website if I get a 409.

I'd love to have a way to flag with the API 😉

**Comment by kevincador** [comment]
@rectifyer just an FYI but I've been able to delete some comments that were older than 2 weeks while testing my fix. If they're at least 1 reply it seems to work as expected (receiving a 409 and not deleting 😅)
