### ISSUE TITLE
API status code 500 errors have returned

### ISSUE THREAD

**Issue by nixgates** [trakt/api-help#133]
Just a quick hello to let you know that users have been experiencing regular 502 errors from the API again.

Hope you have the time to take a look.

Edit: Just noticed some requests are returning a 504: Service Unavailable - server overloaded (try again in 30s)

**Comment by kevincador** [comment]
I'm also seeing an increase of people reporting sync issues. Looking at the logs, I see a lot of 5XX errors.

**Comment by eliehaykal** [comment]
The service seems to have been unstable around 12 hours ago. I have been getting lots of syncing reports from my users as well. I'll try to get some logs

**Comment by MaxHasADHD** [comment]
Also getting a lot of 5XX errors on my end with my apps and having users report the same

**Comment by MaxHasADHD** [comment]
I haven't had a successful "sync" in my app in days. I usually call history, ratings, hidden, last activities, watchlist, and custom lists. One of the APIs will fail every time now.

**Comment by rectifyer** [comment]
The API is getting hammered with traffic since this weekend. I just added 5 more API servers to help improve performance.

**Comment by nixgates** [comment]
Appreciate the quick response @rectifyer

**Comment by eliehaykal** [comment]
> The API is getting hammered with traffic since this weekend. I just added 5 more API servers to help improve performance.

Much appreciated!

**Comment by MaxHasADHD** [comment]
Thank you for the quick response!

**Comment by nixgates** [comment]
@rectifyer Looks like the API has returned to a healthy status.

Solid response times and I haven't seen any 5xx errors. 

Solid effort, thank you :)
