### ISSUE TITLE
Season 0 returned from API with no 'episodes' key

### ISSUE THREAD

**Issue by nixgates** [trakt/api-help#135]
When polling the endpoint _"/shows/{show_id}/seasons?extended=episodes"_ some shows are returning season 0 with no episodes key in the dictionary. I wasn't expecting it and didn't prepare for it so it broke my sync for a few shows in the app. 

Not sure if it's by design but figured it wouldn't hurt to make it known just in case.

**Example**:
`{'number': 0, 'ids': {'trakt': 60884, 'tvdb': 519592, 'tmdb': None, 'tvrage': None}},  {'number': 1, 'ids': {'trakt': 60885, 'tvdb': 519732, 'tmdb': 59224, 'tvrage': None}, 'episodes': [{'season': 1, 'number': 1,.....`

Above example is for the show Chicago P.D. What I would have expected would be an empty list at the episodes key like so:

`{'number': 0, 'ids': {'trakt': 60884, 'tvdb': 519592, 'tmdb': None, 'tvrage': None}, 'episodes':[]},` 

If I'm wrong please feel free to close this, I've remedied the issue on my end.

**Comment by rectifyer** [comment]
Extremely delayed here, but I fixed this so `episodes` will always be returned, even with no episodes. It doesn't happen much, but there are occasionally 0 episode seasons added to TMDB. The fix will be live next week.
