### ISSUE TITLE
Incorrect/Unexpected Season Premiere Dates

### ISSUE THREAD

**Issue by tysonkerridge** [trakt/api-help#136]
I was doing some sorting/filtering work with list items which included some seasons and noticed that some season objects returned by the API have incorrect or unexpected season premiere dates attached to them. It seems to be for some of the more recent seasons, and I can't seem to find where the data is coming from (eg. either I can't see it on TVDB/TMDB at all, or the value of the first episode is different on TVDB/TMDB).

Not sure if this expected in some way or would eventually get fixed automatically, but considering one of the ones I found is a season from July 2019 I guess that might've happened by now unless this would require manual adjustments?

It causes sorting/filtering to not work as expected even on the Trakt website (such as filtering unreleased items from your watch list while Westworld Season 3 is on there which has a premiere date of 2003 even though its not aired yet etc.)

Some examples I've come across explicitly:

Veronica Mars (pasted response filtered)
`GET https://api.trakt.tv/shows/veronica-mars/seasons?extended=full`
```
[
  {
    "first_aired": "2014-03-15T01:00:00.000Z",
    "number": 0
  },
  {
    "first_aired": "2004-09-23T01:00:00.000Z",
    "number": 1
  },
  {
    "first_aired": "2005-09-29T01:00:00.000Z",
    "number": 2
  },
  {
    "first_aired": "2006-10-04T01:00:00.000Z",
    "number": 3
  },
  {
    "first_aired": "2008-12-16T22:30:00.000Z",
    "number": 4
  }
]
```
The `first_aired` for `number` 4 is expected to be around July 19, 2019.

---

Westworld (response filtered)
`GET https://api.trakt.tv/shows/westworld/seasons?extended=full`
```
[
  {
    "first_aired": "2017-02-03T02:00:00.000Z",
    "number": 0
  },
  {
    "first_aired": "2016-10-03T01:00:00.000Z",
    "number": 1
  },
  {
    "first_aired": "2018-04-23T01:00:00.000Z",
    "number": 2
  },
  {
    "first_aired": "2003-01-25T05:00:00.000Z",
    "number": 3
  }
]
```
The `first_aired` for `number` 3 is expected to be null I guess seeing as the season/first episode hasn't aired yet (and the first episode doesn't have a `first_aired` in the response of the season's episodes (`GET https://api.trakt.tv/shows/westworld/seasons/3?=&extended=full`)?

Others which seem to have the same issue from a quick search: 
Season 2 of https://api.trakt.tv/shows/magnum-p-i-2018/seasons?extended=full
Season 10 of https://api.trakt.tv/shows/blue-bloods/seasons?extended=full

**Comment by rectifyer** [comment]
I finally tracked down the bug that was causing this. I'll have a fix out later in the week and the season `first_aired` date will get updated when a show is refreshed.
