### ISSUE TITLE
API still not very stable

### ISSUE THREAD

**Issue by eliehaykal** [trakt/api-help#137]
I am receiving negative feedback from my users regarding API stability. 
Users are unable to mark items as watched or add comments. Can you please investigate load issues as I still can notice that the API occasionally goes down when I visit http://status.trakt.tv/
It seems to be happening at certain times of the day.
Thank you

**Comment by kevincador** [comment]
Not a lot of user reports for me but I had some issues myself and a twitter message over the weekend. The status page never seems to indicate any issue.

**Comment by eliehaykal** [comment]
I just noticed another outage: https://imgur.com/a/rY404mf

**Comment by limbero** [comment]
I've had intermittent issues over the past week or two.

**Comment by rectifyer** [comment]
We are still tracking down the issue, but it seems related to user's with a huge amount of data in their account. Some apps are incorrectly syncing millions of extra plays which causes the data on those user accounts to not return correctly. I will be adding some additional error checking today and continuing to track the issue to hopefully prevent the performance issues. We are also working on some behind the scenes upgrades to increase performance as well.

**Comment by eliehaykal** [comment]
> We are still tracking down the issue, but it seems related to user's with a huge amount of data in their account. Some apps are incorrectly syncing millions of extra plays which causes the data on those user accounts to not return correctly. I will be adding some additional error checking today and continuing to track the issue to hopefully prevent the performance issues. We are also working on some behind the scenes upgrades to increase performance as well.

Many thanks for your endless efforts

**Comment by nixgates** [comment]
@rectifyer If and when you get a better grip with what's going on, could we ask you to divulge a little information? 

I think it might be beneficial if we could all take a second to make sure it's not our projects causing this havoc on the service.

**Comment by rectifyer** [comment]
There were some apps that implement sync wrongly which was adding a bunch of duplicate plays to users who used those apps. For some users, this resulted in so many extra plays that it would time out when trying to get their data. We put some extra protections in place on the API to limit the impact those users had on the API and hopefully it has been better recently.

**Comment by eliehaykal** [comment]
> There were some apps that implement sync wrongly which was adding a bunch of duplicate plays to users who used those apps. For some users, this resulted in so many extra plays that it would time out when trying to get their data. We put some extra protections in place on the API to limit the impact those users had on the API and hopefully it has been better recently.

Thanks for your efforts. They have vastly improved. A slight hiccup occurred around 12 hours ago but things are back to normal now.

**Comment by rectifyer** [comment]
From what we can see, the API has been a lot more stable over the last few weeks. We've added lots of additional servers and also made some performance updates in the code. It's not perfect, but from our stats looks a lot better lately and the API is handling the ridiculous amount of requests being thrown at it 😄
