### ISSUE TITLE
GET request - Content-Type header

### ISSUE THREAD

**Issue by TheUltimateC0der** [trakt/api-help#139]
When making a GET request to the https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-custom-list endpoint, why do I have to send a `Content-Type: application/json` header ?

**Comment by rectifyer** [comment]
The API only uses JSON, so the header just explicitly indicates that.

**Comment by TheUltimateC0der** [comment]
The header explicitly says that the body content my client is sending is `application/json`. Since I am sending a  `GET` request, there is no body content.

**Comment by TheUltimateC0der** [comment]
Nvm ... The error was something else.

My application requested a list items from a user that got deleted on your end.

If I make a request to the described endpoint, and the user has been deleted, API returns a HTTP 412 response. Your documentation tells me `Precondition Failed - use application/json content type` I assumed you changed the API in some way.

Is there any way to determine if a user has been deleted? I have seen the username now is {username that i got in my db}-deleted-{random integer}. I guess any user can change his name to something containing "-deleted-" so this would not be a good indicator.

**Comment by rectifyer** [comment]
Please post the full request and response so I can try and replicate the issue.

**Comment by TheUltimateC0der** [comment]
GET `https://api.trakt.tv/users/{username}/lists/{list slug of a users list}/items/shows?extended=metadata&page=0&limit=10`

Where {username} should be the original username of the user that has been deleted.

Headers:
```
Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXX
trakt-api-key: XXXXXXXXXXXXXXXXXXXXXXX
Content-Type: application/json
```

X-Request-Id: 098e1464-a203-40d4-b590-c2d0fb2db7bd
In case you have some kind of log for this.

![image](https://user-images.githubusercontent.com/3315612/72931179-b2d86380-3d5d-11ea-870a-205b52ac7809.png)

**Comment by TheUltimateC0der** [comment]
Could you also answer my question of how I can determine if a user has been deleted ?

**Comment by rectifyer** [comment]
It will return a `404` error if the user is deleted since they are technically not found. I fixed a small bug that affected some older deleted users so it will correctly return the error code.
