### ISSUE TITLE
Endpoint to get replies only

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#14]
Would it be possible to have an endpoint to get replies only? Instead of using [get-comments](https://trakt.docs.apiary.io/#reference/users/comments/get-comments) including replies.

**Comment by thiagocard** [comment]
Like this one?
https://trakt.docs.apiary.io/#reference/comments/replies/get-replies-for-a-comment

**Comment by kevincador** [comment]
No. This one is to get replies on specific comment. I'd like to have all replies from a user, no mater the comment. You can get-comments from a user, add a param to get all comments and replies. But you can't get all replies only.

**Comment by rectifyer** [comment]
You can send `?include_replies=only` to do this now.

https://trakt.docs.apiary.io/#reference/users/comments/get-comments
