### ISSUE TITLE
API Request Limit

### ISSUE THREAD

**Issue by sereisoglu** [trakt/api-help#141]
Hi.
What is API usage limit?
I get this error when I make several calls in a row:
Too much requests. Please contact us if you need higher limits and obey Retry-After header.

**Comment by rectifyer** [comment]
That doesn't look like an error message we send, are you sure this is from the Trakt API? If so, please post the full API request and response, including all headers.

**Comment by sereisoglu** [comment]
I couldn't create the same error situation, I will write it if it happens again.
