### ISSUE TITLE
Search by release date

### ISSUE THREAD

**Issue by MrMamen** [trakt/api-help#144]
Because of some inconsistencies with seasons names and order, I'd like a lookup for release date for a show. The season is that my lookup fails because of the data appears like this:
/shows/some-show/season/2020/episode/3
I've not found a way to map between numerical seasons and year-bases season, however I do have the original air date so if I could do a search based on that I would indeed get a match.

**Comment by rectifyer** [comment]
You can call `/shows/:id/seasons?extended=episodes` to get all episodes for a show, then loop over each episode to find your matches. This returns a ton of data, so if you are able to use other methods that would still be better for the Trakt API and for your app.

A better alternative might be to call `/shows/:id/seasons` (no extended info) then `/shows/:id/seasons/:season` to get episodes for each.

There isn't a super clean solution to this unfortunately.
