### ISSUE TITLE
Crew Types

### ISSUE THREAD

**Issue by sereisoglu** [trakt/api-help#145]
Hi.
https://trakt.docs.apiary.io/#reference/people/movies
You specified in the link above:
> The crew object will be broken up into production, art, crew, costume & make-up, directing, writing, sound, and camera (if there are people for those crew positions). Each of those members will have a jobs array and a standard movie object.

But if you do this API call:
https://api.trakt.tv/shows/tt0944947/people?extended=guest_stars
You can see "editing" as crew type. You did not specify this in the document.
If you are getting crew types from TMDb. There are "Lighting" and "Editing" type different from you.

**Comment by sereisoglu** [comment]
https://api.trakt.tv/movies/tt7286456/people?extended=guest_stars
There is "lighting" in this API call.

**Comment by rectifyer** [comment]
Thanks, I'll get the API docs updated later today.
