### ISSUE TITLE
Issue with authentication

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#146]
Hello,

One of my user reports me that he can't use my app because I soon as he is logged in, he loose the authentication. 

I made some tests with him and the first call I made is `https://api.trakt.tv/sync/last_activities` after setting the token I just got from the authent process (and I correctly set the trakt-api-key header too) but then I got a 401.

How can we debug further ?

**Comment by rectifyer** [comment]
A 401 indicates invalid auth information, can you provide a more detailed request and response?

**Comment by jonathanantoine** [comment]
Which request do you need ? I would like to provide them to you but I don't want to reveal any private or sensitive information.

**Comment by rectifyer** [comment]
You can post the info here, but with the private info removed, which you can email directly to support@trakt if needed.

**Comment by jonathanantoine** [comment]
So here is what I do :

1. I Open the connection screen in a browser : https://trakt.tv/oauth/authorize?client_id=XXX&redirect_uri=YYY&response_type=code

1. The user log in via login / password

1. My app is opened via it's protocol YYY?code=ZZZ
1. I send the below POST content to : https://api.trakt.tv/oauth/token

```json
{
    "code": "ZZZ",
    "client_id": "XXX",
    "client_secret": "AAA",
    "grant_type": "authorization_code",
    "redirect_uri": "YYY"
}
```
5.  I get the below answer :
```
{
    "access_token": "HHH",
    "token_type": "Bearer",
    "expires_in": 7776000,
    "refresh_token": "UUU",
    "scope": "public",
    "created_at": 1581772918
}
```
6. I then use the access token ad a Bearer header and I get 401.

Do you need more information ? You already get the user email as he contacted you by mail.

**Comment by Kylarofthenight** [comment]
Hi there,
I'm the user having the issues. 
I've emailed your support email and was speaking to someone named Justin, but I've not had a reply in 4 days.
Is there any additional info I can provide, either on here or by email?

**Comment by rectifyer** [comment]
Ok, it appears the user account was deleted a long time ago when we still on Trakt version 1. This old remnant was causing an issue specifically for this account. I've fixed it manually and it should work to connect now.

**Comment by jonathanantoine** [comment]
Can you please confirm @Kylarofthenight  ;) 

Thanks a lot @rectifyer  !
