### ISSUE TITLE
Question - endpoint to get only the actions made by the user since a provided date ?

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#151]
Hello,

Does an endpoint to get only the actions made by the user since a provided date  exists ?
I would be able to get only the last XX episodes watched instead of getting the whole watched history.

Regards.

**Comment by rectifyer** [comment]
The `history` endpoint can do this.

https://trakt.docs.apiary.io/#reference/sync/get-history/get-watched-history

**Comment by jonathanantoine** [comment]
Will I get the collected and 'add a show to a watchlist" infos too ?

Thanks !

**Comment by rectifyer** [comment]
No, this endpoint os only for history. We don't really have the same concepts for collection and watchlist since items can only appear one time.
