### ISSUE TITLE
Getting user settings?

### ISSUE THREAD

**Issue by MrMamen** [trakt/api-help#152]
Would it be possible to expose user settings in userprofile search. Of course a OAuth for the current user has to be provided. Settings that could be useful the items specified under "DATE & TIME" in account settings. (Time & Date format)

**Comment by rectifyer** [comment]
I don't think we want to expose any user settings like that, I'm not sure what the use case is to need that info? You can get the OAuth user settings using https://trakt.docs.apiary.io/#reference/users/settings/retrieve-settings for that specific user.

**Comment by MrMamen** [comment]
That was what I was looking for! Didn't find it on my own. Thanks.
