### ISSUE TITLE
Getting 401 on access token after I just refreshed.

### ISSUE THREAD

**Issue by jarrodls** [trakt/api-help#155]
We've been seeing this issue for a while, we will get a 401 returned saying that the token has expired (even though I don't think they have). So we use the refresh token to get a new access_token which works but then when we use the new access token we still get a 401.

Flow:
 * Make request to get user activities using stored access token
 * 401 returned
 * Attempt to refresh token
 * Refresh success, store new access token and refresh token
 * Attempt request again with new token
 * 401 returned

If a user has revoked the application, would the refresh token still work?

**Comment by rectifyer** [comment]
This is likely the same issue mentioned in https://github.com/trakt/api-help/issues/146#issuecomment-590485193 where a user has a deleted account from back in the Trakt version 1 days. A user can email support@trakt.tv with their username and we can fix manually.

If a user revokes the app, the refresh token shouldn't be valid either. But I don't think that is what's going on here.
