### ISSUE TITLE
Get episode summary using episode ID

### ISSUE THREAD

**Issue by Migushthe2nd** [trakt/api-help#157]
I can't seem to find a way in the API docs to get an episode's summary based on the episode ID. Do I really need to request an episode's summary via `/shows/game-of-thrones/seasons/<seasonNr>/episodes/<episodeNr>` or did I miss something?
It would be a lot easier to be able to request it via e.g. `/episodes/<episodeID>`

**Comment by jonathanantoine** [comment]
Hello @Migushthe2nd ,

As far as I know, you do not miss something. You can also get them all at once using the `"shows/" + _showId + "/seasons"` endpoint.

**Comment by Migushthe2nd** [comment]
Thanks, but that is not entirely what I was looking for. For now I guess I'll just save the episode IDs with the corresponding season and episode number in my database.
