### ISSUE TITLE
Feature Request: Paused at filter for 'sync/playback/'

### ISSUE THREAD

**Issue by nixgates** [trakt/api-help#159]
After sheepishly closing off my last issue not realizing the size of the call with the extended parameter, I would like to throw out the suggestion of adding a filter for the "paused_at" value so we don't have to pull the entire collection down.

Hopefully this will allow us to make much smaller and less taxing calls to the servers in our app sync cycles.

**Comment by rectifyer** [comment]
That method supports the `limit` parameter so you can just sync a certain number of items. Will that work for you?

**Comment by rectifyer** [comment]
The API method will be updated later this week to support optional pagination and date filtering. API docs are updated in the meantime.
