### ISSUE TITLE
Move app to different account?

### ISSUE THREAD

**Issue by anthonylavado** [trakt/api-help#16]
Hi there! :wave:

We're starting to implement Trakt over at Jellyfin. I registered the API app under my personal Trakt account, and would like to move it over to one we're setting up for the organization. Is there an easy way/backend way to officially do this, or should I just have two browsers open and rename/create at the same time?

Thanks!

**Comment by rectifyer** [comment]
We can handle this via support. Please send an email from both of your accounts to support@trakt.tv and include the app info like client ID, etc. I should be able to move it over ok.

**Comment by anthonylavado** [comment]
It turns out that more than one app can exist with the same name! I made it under our "org" account, and then renamed mine to be safe.

Either way, thank you for responding @rectifyer!

**Comment by rectifyer** [comment]
Ok cool, that works too 😄
