### ISSUE TITLE
Aired property not updated correctly in "Get show watched progress"

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#162]
I'm using `aired` and `completed` properties from [Get show watched progress](https://trakt.docs.apiary.io/#reference/shows/watched-progress/get-show-watched-progress) to show the number of episodes behind in my app's To Watch list.

The issue is when new episodes are just out, `next_episode` is correctly updated but the `aired` count can be behind. This results in the app showing the right next episode to watch but with `0 behind` showing under. Not critical but annoying 😅

**Comment by rectifyer** [comment]
This is unfortunately a side effect of the caching for that method. There isn't much we can do currently without removing the caching, which would have large performance issues.

**Comment by kevincador** [comment]
I'm going to handle that in the app. It will show "At least one behind" 🤓
