### ISSUE TITLE
device code auth url 404s

### ISSUE THREAD

**Issue by castaway** [trakt/api-help#163]
Hi folks,

As per: https://trakt.docs.apiary.io/reference/authentication-devices/code I am trying to use the device code flow to authenticate. But I get stuck at the first hurdle, https://api.trakt.tv/oauth/device/code returns a 404 .. am I doing it wrong or is it broken?

Jess

**Comment by castaway** [comment]
nevermind I am an idiot..

**Comment by mataperezluis** [comment]
what was the problem?

**Comment by castaway** [comment]
Umm, I think I was doing a GET (cos I'd only read the top of the page), and initially failed to see the part further down with the example and the POST info
