### ISSUE TITLE
Exchanging token issue : java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#167]
Hello,

Some user encounter this kind of exception regarding a wrong ssl certificate when trying to log in (exchanging the token) :

`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

Is it an issue you are aware of ?

**Comment by rectifyer** [comment]
I'm not really sure what that error means. Any more details? Our SSL certificates should be all valid.
