### ISSUE TITLE
Need help regarding tvshows behaviour

### ISSUE THREAD

**Issue by Kashish-Sharma** [trakt/api-help#169]
Let's say a show is in **watchlist**, and I mark a single episode as **watched**.
The show is still in watchlist, and also in watched.

Is this correct or Iam missing something?

In my app, there are 3 states:
1. Nothing
2. Watchlist
3. Watched.

When it's nothing, you can:
- Add to watchlist
- Add to watched

When it's watchlist:
- Add to watched
- Remove from watchlist.

When it's watched:
- Not watched
- Rewatched

Is this correct or should I add more options?

**Comment by tysonkerridge** [comment]
I think you already asked this in #122? At the end of the day it’s up to you what your app shows, but you’re probably best off just checking what the Trakt website does if you’re trying to keep it similar. What you have sounds similar already. 

You just need to remember that if an episode is added to history while the show is on the watch list, that show will be automatically removed from the watch list. Again, you should try making the change on the website and see if it matches your app in terms of what makes sense for your app.

**Comment by Kashish-Sharma** [comment]
Confusion starts when we add a watched show to watchlist.
Then it's in both watched and watchlist!
