### ISSUE TITLE
Cannot reconnect to Facebook on the web site ? 

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#170]
I have this issue and I have some users reporting trouble getting signed in using Facebook :

![Screenshot_2020-04-14-22-57-19-025_com microsoft emmx](https://user-images.githubusercontent.com/3800550/79273569-7ec79700-7ea3-11ea-8208-e827b5a79bed.jpg)

**Comment by jonathanantoine** [comment]
@rectifyer 😁 any update 😁?

**Comment by rectifyer** [comment]
Facebook has unfortunately disabled the Trakt app and we've not been able to reinstate it. The website has been updated to help guide the user to get back into their account, but the plan is to move away from Facebook login.

**Comment by jonathanantoine** [comment]
Thanks for the update on this subject!
