### ISSUE TITLE
Where to send refresh_token to get new (device) access token?

### ISSUE THREAD

**Issue by gijsbeijer** [trakt/api-help#173]
Hi all,

I'm just going to appologize up front because it's probably easy as pie, but I just can't seem to find it (yes searched this repo, and googled around).

**Where(/how) do I get my refresh token?**
In the api at https://trakt.docs.apiary.io/#reference/authentication-devices/get-token, it states: 

> Save and use the refresh_token to get a new access_token without asking the user to re-authenticate. Check below for all the error codes that you should handle.

but it never states where to send it and how. Do I send it to the polling url? Should I just send it as a Bearer in one of my requests or should it be in the post data, and do I need to send anything else?

Hope someone can help me out! 
 Also if someone knows where I can send feedback on the API to state this more clearly, let me know!

Regards Gijs

**Comment by tysonkerridge** [comment]
Info should be here: https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-refresh_token-for-access_token. 

It works similar to getting the access token for the first time [(Exchange Code for Access Token)](https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-code-for-access_token) which you originally get the refresh token from.

**Comment by gijsbeijer** [comment]
> Info should be here: https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-refresh_token-for-access_token.
> 
> It works similar to getting the access token for the first time [(Exchange Code for Access Token)](https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-code-for-access_token) which you originally get the refresh token from.

Lifesaver!
I'm authenticating a device so I was checking this at the Authentication - Devices section. 

Is this something that should be referenced in that section as well?

Again, thanks for this!

**Comment by tysonkerridge** [comment]
No worries. 

Hmm, I just noticed that the left side reference menu doesn’t display the refresh exchange. Not sure if that’s expected @rectifyer? And perhaps the device get token description could include a reference link to the refresh exchange seeing as it’s not directly in that section and could be missed as you experienced. 

Will have to wait on an official response 🙂

**Comment by rectifyer** [comment]
Since its the same endpoint, the API docs don't add a separate item in the left nav. I think that's a limitation of the API blueprint framework.
