### ISSUE TITLE
Synced plays become stuck after removing them through the web ui

### ISSUE THREAD

**Issue by maxhand** [trakt/api-help#176]
Steps to reproduce: 

Setup: Find a show that you are not tracking yet, and without any plays.

1. Sync episode play(s) through the API.
2. Navigate to https://trakt.tv/users/{user}/history.
3. Click on a checkmark for one of the synced items from step 1.
4. Click all plays.
5. Navigate to the show for which the history item should be removed from.
6. Observe that there are still played episodes. Attempting to remove all plays for this show will result in an error being displayed (ex: Doh! There was an error doing this.)

I've been able to reproduce this for 2 or 3 shows so far. The userid that I use for testing is maxhand.

Let me know if you need any other details!

**Comment by rectifyer** [comment]
The website isn't instantly updated, but it should get the new data about 5 minutes after it is added from the API. Maybe that is what you're seeing?

**Comment by maxhand** [comment]
Seems like that was likely the issue. The plays are gone now. Apologies for not waiting a bit longer, I was expecting the data to update as fast as play syncing does. 

Thanks for clearing that up!
