### ISSUE TITLE
Past couple of days been getting 405 "Method Not Found" on all endpoints.

### ISSUE THREAD

**Issue by ViNSaNiTY24** [trakt/api-help#177]
Hello, 

The past 3 or 4 days everytime i try to use the Trakt API i've been getting the 405 Method Not Found errors on every single endpoint including the ouath authentication ones. I've been using the API for years and this just seemed to happen out of nowhere. Did something change that i don't know about or is there something wrong with the API?

Thanks for any help you can give me.

**Comment by elgatito** [comment]
@ViNSaNiTY24 have the same issue. How did you fix it?

**Comment by ViNSaNiTY24** [comment]
It was mine own fault. I was using a "GET" request instead of a "POST" request when trying to get my refresh token because your access token expires every 60 days or something. So i would check to see if your token might of expired.

https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-refresh_token-for-access_token
