### ISSUE TITLE
Date inconsistency ?

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#179]
Hello,

Regarding this show : https://trakt.tv/shows/lost-gold-of-world-war-ii

When I set the website to CentraTime: all episodes are at 9:00PM
When I set the website to Paris timezone : the first episode is at 3:00 AM and the other at 4:00AM

It's an issue of the website ? Which info should I display in my apps ?

Thanks !

**Comment by reboot** [comment]
The episodes aired on the end of March, begin of April. On 31th March 2019 the european summer time started. If the US summer time starts at the different date then this is probably correct. What you should display in your app probably depends on the timezone of the device that is running the app.

**Comment by jonathanantoine** [comment]
Thanks @reboot , summer time started in the US the "Sunday, March 10" and the episode I am talking about was 10 days later so it's not related. 

I agree regarding displaying the date using the device timezone but there is some algorithm to apply for date of US TV Shows and it seems there is a glitch here.

Maybe @rectifyer can help :D ?

Thanks !

**Comment by rectifyer** [comment]
Since this is US based show, it will respect the daylight savings time. So, my guess is DST happened between episode 1 and 2 so when converting to a non DTS timezone it's going to be different by an hour to account for that.
