### ISSUE TITLE
Display "create an account" page instead of "sign in" page ?

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#180]
Hello,

Is there way to tell the "Oauth login page" to immediately display the "create an account page" when starting a login process ? Currently it display the sign-in page but some user would love to get the "registration page" immediately.

Thanks !

**Comment by rectifyer** [comment]
I don't think this is something we will support. The longer term solution is an integrated page where it simply asks for the email/username first then determines if their is already and account or if a new one needs to be created. If an app can specific to show the create page, that basically creates the same problem for people looking for the sign in form first.

**Comment by jonathanantoine** [comment]
I would love to display 2 buttons in my app and let the user choose directly from my app where to go instead of having to choose on the next page to create an account 😁
