### ISSUE TITLE
NO 'Access-Control-Allow-Origin' header in chrome extension fetch

### ISSUE THREAD

**Issue by Matheos96** [trakt/api-help#181]
Hello!
I am new to the Trakt API and started of with it yesterday. I want to use it in a chrome extension I am working on. I am trying to get the user to authenticate himself using the api. I am currently using the `urn:ietf:wg:oauth:2.0:oob` redirect url for convenience as I don't know where I would redirect otherwise to get the code back to my extension... (please explain how to do it in a smarter way if you know how)
Anyway, I then have an input field and a button for users to input the code manually given by trakt. Once input and button clicked, I perform a POST request to `https://api.trakt.tv/oauth/token` using javascript's fetch API.  I do this using the following code:
> const rawResponse = await fetch('https://api.trakt.tv/oauth/token', {
            'method': 'POST',
            'headers': {
              'content-Type': 'plain/txt'
            },
            'body': {
                'code': code, 
                'client_id': client_id,
                'client_secret' : client_secret,
                'redirect_uri': redirect_uri,
                'grant_type': 'authorization_code'
            }
          });

I use content-type plain/txt because I saw that cors does not allow application/json. When performing this fetch, both in the background of the extension and in the active window of the extension, I get the following error:
> Access to fetch at 'https://api.trakt.tv/oauth/token' from origin 'chrome-extension://fblfijemjflgcdiofbkdpcniambfgdbb' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I have tried using mode: no-cors but then I just got unauthorized code 401...

I figured I may be able to fix this using the optional _Javascript (cors) origins:_ box in my App settings on trakt, but for a chrome extension I don't really know what I should put in there...

Can anyone help me out?

**Comment by sttz** [comment]
I think this question is more related to Chrome extension development than to Trakt.

Some pointers:

* Cross-origin requests have to be made from the background script, the content script only allows requests in the context of the page it's running in.
* You have to [declare the hosts](https://developer.chrome.com/apps/xhr) you want to connect to in your extension's manifest.
* Given the two points above, requests should work. If not, you'd have to enter your extension's origin (the `chrome-extension://…` in the error above) on the Trakt website.

**Comment by Matheos96** [comment]
> I think this question is more related to Chrome extension development than to Trakt.
> 
> Some pointers:
> 
> * Cross-origin requests have to be made from the background script, the content script only allows requests in the context of the page it's running in.
> * You have to [declare the hosts](https://developer.chrome.com/apps/xhr) you want to connect to in your extension's manifest.
> * Given the two points above, requests should work. If not, you'd have to enter your extension's origin (the `chrome-extension://…` in the error above) on the Trakt website.

You are correct on every point you make. I did solve it and the cause was the hosts. I declared https://api.trakt.tv/*/ as allowed host in my permission in my extension and then it worked from the background script.
I left the box on the trakt website empty and it still works luckily as the chrome-extension:// url is not consistent and the id is unique for every install on every machine why it would have become impossible to do it that way.

Hope this helps someone else too.
