### ISSUE TITLE
How to store Trakt access tokens to ensure username changes don't break things

### ISSUE THREAD

**Issue by GrahamWalters** [trakt/api-help#182]
I'm building a service for syncing libraries to Trakt and was hoping to have the users authenticate with Trakt. Once authenticated I would save their Trakt user id, access token, and some settings in my database. I'm currently hitting the `/users/me` endpoint once a user has authenticated and using the username as the primary key in my users table. My concern is a user could change their username at any point, which would break their account on my site.

I'm wondering what other people are doing for this? Specifically, if you've built a service that uses Trakt, how do you store the credentials and how do you ensure username changes don't break things?

**Users Table**
Here's my users table. As you can see, the other service I'm using provides a unique uuid, so I can verify it is the same user even if the username has changed. 
- trakt_username
- trakt_access_token
- trakt_refresh_token
- trakt_refreshed_at 
- service_b_uuid
- service_b_username
- service_b_access_token
- etc...

In theory the following could happen without a unique Trakt user identifier:
1. create a Trakt account (AccountA)
2. sign into my service using the Trakt account AccountA, which would create a new user
3. rename AccountA to AccountB on Trakt
4. sign into my service as AccountB, which would create a new user
5. another user (user 2) could create a Trakt account with the name AccountA
6. user 2 could sign into my service using the Trakt account AccountA, which would give them access to user 1's original account

A possible fix for 6 would be to store and diff the `username` and `joined_at` fields, but username changes would still break existing accounts.

A real solution would be for the `ids` object to return a numeric or uuid ID as well
```json
"ids": {
  "slug": "Justin",
  "id": 123456789
},
```

**Comment by spyr0s** [comment]
I think the slug is unique for every user and don't change if the user change their name. So you could use the slug in your db.

**Comment by GrahamWalters** [comment]
I just gave this a try and unfortunately the slug **does change** when the username is updated. Here's a relevant doc:
>Username vs. slug
>All users methods should use the slug to identify the user. The slug is a URL safe and globally unique version of the username.

**Comment by rectifyer** [comment]
The `access_token` is the best thing to use since that is unique across all Trakt users. You would need to make sure to update it once you refresh the token.

**Comment by GrahamWalters** [comment]
The `access_token` is unique per session, so I'm not sure how that's supposed to help at all. Using an `access_token` doesn't help stop username changes from breaking their account on a third party service. I'm presuming you're suggesting the following logic:
1. User signs into Trakt and I get an `access_token`
2. I make a request to the settings endpoint to get their username
3. I look in my db for a user with their username (this would break if they'd changed their username since signing up for my service)
4. I make a request to the settings endpoint using the access_token from the db, and then compare the username with the username from step 2.

Using the Trakt Oauth2 APIs without an endpoint for uniquely identifying users is a serious security concern and I hope you reopen this issue. Changing your Trakt username shouldn't break third part services relying on Trakt to authenticate their users.

Here's how other services handle this:

GitHub returns a unique id when getting the user
[passport library](https://github.com/jaredhanson/passport-github/blob/46b96e8ad4af7a3f30532316ab2ce6cc36316ed2/lib/profile.js#L14)
[GitHub Docs](https://developer.github.com/v3/users/#get-the-authenticated-user)

Google returns a `sub` field when exchanging the `code` for an access token
>An identifier for the user, unique among all Google accounts and never reused. A Google account can have multiple email addresses at different points in time, but the sub value is never changed. Use sub within your application as the unique-identifier key for the user. Maximum length of 255 case-sensitive ASCII characters.

[passport library](https://github.com/jaredhanson/passport-google-oauth2/blob/2399ef47f00b47ac587f056f2f100a2c4db81928/lib/profile/openid.js#L26)
[Google Docs](https://developers.google.com/identity/protocols/oauth2/openid-connect#obtainuserinfo)

**Comment by rectifyer** [comment]
The idea was to index on the `access_token` and not the username since that will be a unique identifier. Since the user has granted access and you have the `access_token`, you're able to either use the authenticated `/sync` methods or `/users/me` since `me` will know who they are based on the `access_token`. 

It sounds like that is already what you're doing and I'm pretty sure similar services are using the `access_token` as the identifier for a user. So, in your steps above #2 and #3 wouldn't be needed and instead you can identify them and make `access_token` the primary key. I think that should work, right? I'm just trying to gather more info since this is the first time we've had a request for a Trakt ID and I haven't received this feedback from any other apps or services.

**Comment by GrahamWalters** [comment]
Let me explain, the service I'm building is for connecting Trakt and other media software like Plex. Each user must have a Trakt account, so my goal was to use the Trakt Oauth APIs to offer a "Sign in with Trakt" functionality. When the user signs into Trakt, I check if the user exists in my users table and if not I create a new user. If the user does exist I take the opportunity to store the latest access token, refresh token, and refreshed_at value. I then generate a JWT valid for 24 hours, to be used for interacting with my APIs.

My service stores the access token so it's able to forward events onto Trakt. My service also refreshes the tokens every 2 months.

The issue I'm having is, there's no unique identifier to be used for checking if the user exists in my users table.

**Comment by rectifyer** [comment]
Thanks for the additional details, that does help it make sense. We talked it over more internally and we added a new `uuid` field to `/users/settings` that can be used to uniquely identify a Trakt user. Please let us know how that works out for your service, and keep us posted when you have something to share.

https://trakt.docs.apiary.io/#reference/users/settings/retrieve-settings
