### ISSUE TITLE
Certain shows cannot be GET with IMDB ID

### ISSUE THREAD

**Issue by Matheos96** [trakt/api-help#183]
Hello. I am having trouble with my application. I have access to the IMDB id so I use that to fetch the episode object which I use to start/pause/stop.
This works fairly well but for some new shows, I just get 404... Using the slug works bug I do not have direct access to it...

Example: The Eddy
slug: the-eddy-2020
imdb: tt7423482

`GET https://api.trakt.tv/shows/the-eddy-2020/seasons/1/episodes/8` returns the episode

`GET https://api.trakt.tv/shows/tt7423482/seasons/1/episodes/8` returns 404...

**EDIT**
My current workaround is as follows:

1. Extract imdb id.
2. Perform an id lookup to api: `GET https://api.trakt.tv/search/imdb/{imdb_id}`
3. Extract slug from response and use that for further requests.

This works. Though it feels like a hazzle involving another GET request when I feel I should be able to do it directly using the imdb id?

**Comment by rectifyer** [comment]
We unfortunately don't have 100% coverage for IMDB IDs. It's pretty good, but we ultimately get the IMDB ID from TMDB and TVDB. The fix for that show would be adding the IMDB ID to both of those open databases, then Trakt will sync up about 24 hours later.
