### ISSUE TITLE
Pagination in recommendations

### ISSUE THREAD

**Issue by spyr0s** [trakt/api-help#184]
In the API docs we read 
"By default, 10 results are returned. You can send a limit to get up to 100 results per page"
But  pagination doesn't seem to be supported.
If I send a request with page=1 and limit =10  I get the same results as sending a request with page=2 and limit = 10, or whatever page= X

Is there a way to get paginated results?

**Comment by linaspurinis** [comment]
Witch API method you are using, not all support pagination.

**Comment by rectifyer** [comment]
We don't currently support pagination on the `/recommendations` method due to how these are calculated.
