### ISSUE TITLE
Timeout for rating endpoint

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#186]
Hello,

I don't know if someone is still here on this github but I see a lot of timeout using the rating endpoint (`https://api.trakt.tv/sync/ratings`). The same call works if you try it several times .

**Comment by eliehaykal** [comment]
Hello,
Many users are reporting this behavior when it comes to rating
Please look into it @rectifyer 
Thanks

**Comment by rectifyer** [comment]
What specific error are you getting? I'd need a specific example to reproduce the issue and try and track it down.

**Comment by jonathanantoine** [comment]
No specific error, just a timeout of the API. You can call the rating endpoint on any movie and you should get it. It's nearly all the time these days. (I only use the trakt id to target the movie.)

**Comment by rectifyer** [comment]
So far I'm not able to reproduce the issue which is why I asked if there was a specific example I could try. The rating and unrating is working ok for me whenever I try it.

**Comment by rectifyer** [comment]
Is this working any better since the recent API maintenance?

**Comment by jonathanantoine** [comment]
It looks better at this time yes. Thanks

**Comment by michaldrabik** [comment]
@rectifyer 
I can observe this issue at this moment.
When adding a rating via `POST sync/ratings` it throws a timeout but the rating is actually added and can be seen in the ratings.

**Comment by kevincador** [comment]
Same here. Getting 504: Gateway time-out from Cloudflare on the /sync/ratings endpoint (POST). Saw this id while testing - Ray ID: 5fdf41903fbad4b8.

**Comment by marovargovcik** [comment]
This is also affecting my app I am currently developing and it is not only /sync/ratings but also:

Create list - POST - /users/<user_slug>/lists
Delete list - DELETE - /users/<user_slug>/lists/<list_slug>

Tested via Postman and as result (after a minute or so) is Cloudflare's HTML 504 time-out template.
It may be possible that there are other endpoints suffering from the same issue.

@rectifyer I know that you are probably overwhelmed but this seems like it deserves attention. Should we create a new issue so it's visible in the issue list?

**Comment by eliehaykal** [comment]
> Same here. Getting 504: Gateway time-out from Cloudflare on the /sync/ratings endpoint (POST). Saw this id while testing - Ray ID: 5fdf41903fbad4b8.

I started getting this error now too

**Comment by marovargovcik** [comment]
Issue seems to be resolved. Just tested now with POST /sync/rating.

**Comment by michaldrabik** [comment]
I think it's still present. I can see this myself and users are also reporting timeouts while rating is actually stored succesfully.

**Comment by marovargovcik** [comment]
Hi, @michaldrabik yes it is still an issue. Even Trakt.tv official website is affected and I believe it previously wasn't. 

I created a new issue #241 since this one is closed and may be overlooked by API maintainers.
