### ISSUE TITLE
Unable to remove season from history 

### ISSUE THREAD

**Issue by akitikkx** [trakt/api-help#188]
Hi everyone,

I seem to be having issues trying to remove a single season from the history after being able to add the same season to the history via sync. Adding the season returns a 201 but for the remove, am getting back a 200 with nothing changed:

`https://api.trakt.tv/sync/watchlist/remove`
`{"deleted":{"movies":0,"shows":0,"seasons":0,"episodes":0},"not_found":{"movies":[],"shows":[],"seasons":[],"episodes":[],"people":[]}}`

This is my request body:

`{"episodes":[],"movies":[],"seasons":[],"shows":[{"ids":{"trakt":1407.0,"slug":"grey-s-anatomy","tvdb":73762.0,"imdb":"tt0413573","tmdb":1416.0,"tvrage":3741.0},"seasons":[{"number":7}],"title":"Grey's Anatomy","year":2005}]}`

Please advise what I am missing? What I am not adding to the response to just remove that single season?

Thank you in advance

**Comment by rectifyer** [comment]
I'm not able to reproduce this issue. I'm guessing the season was previously removed, so the API is going to return `0` indicating nothing actually happened.

**Comment by akitikkx** [comment]
Thank you @rectifyer. Am still seeing the season has marked as watched in the history, nothing is actually changing when I call the /remove request. Am able to add successfully but when trying to remove I get a 200 and not a 201. History state of the seasons remain as watched

**Comment by rectifyer** [comment]
I thought this was related to the `watchlist` as indicated in the first post?

**Comment by akitikkx** [comment]
Apologies I made a typo with the request info above, however I managed to fix the issue (which was on my end)

Thank you for a great API and product

**Comment by rectifyer** [comment]
Ok cool, what did the issue end up being in case that helps others?

**Comment by akitikkx** [comment]
My data classes were not correctly sending the season data it seems, made some adjustments
