### ISSUE TITLE
API OAuth sign-in state isn't consistent with Trakt.tv.

### ISSUE THREAD

**Issue by ShaneQi** [trakt/api-help#19]
### steps:

1. The user opens the browser and signs in his account on **Trakt.tv website**.
2. He closes the browser and opens it again, he still can do things like marking episodes as watched on Trakt.tv website without signing in again. (the browser remembers the sign-in state correctly)
3. The user is connecting his Trakt account to my app. My app opens the OAuth authorize endpoint: `https://api.trakt.tv/oauth/authorize?response_type=code&client_id={myAppClientId}&redirect_uri={myAppRedirectUrl}&state={someState}`. **(important: the endpoint's base URL is `api.trakt.tv`, not `trakt.tv`)**

### expected next behavior:

Since the user has signed in and the browser remembered the state, the user shouldn't be prompted with the sign-in page, and the page should redirect straightly to my app's redirect URL then the OAuth process should finish.

### actual next behavior:

The user is prompted with the login page to sign in again. The user has to type in credentials again, in order to go through OAuth.

It's the same browser, but the browser won't pick up the sign-in state.

### prerequisites:

The user has signed in his account on `Trakt.tv`, and he has gone through OAuth, connected his account to my app.

### steps:

1. The user signs out his account on **Trakt.tv website**.
2. He closes the browser and opens it again, he isn't signed in the website anymore. (the sign-in state is cleaned/invalided correctly)
3. The user wants to disconnect his Trakt account from my app, and connect **another account**.
4. The user signed out his account from my app and tries to connect another account. My app cleans the previous account's info and opens the OAuth authorize endpoint: `https://api.trakt.tv/oauth/authorize?response_type=code&client_id={myAppClientId}&redirect_uri={myAppRedirectUrl}&state={someState}`. **(important: the endpoint's base URL is `api.trakt.tv`, not `trakt.tv`)**

### expected next behavior:

Since the user has signed out his account, and browser cleaned/invalided his sign-in state, the user should be prompted with the sign-in page, so that he can sign in another account.

### actual next behavior:

The user isn't prompted with the sign-in page, and the page redirects straightly to my app and the authed account is the previous account (not the new account obviously, because he never gets a chance to type in the credentials of the new account).

## My Hunch

My hunch is that the cookies that `https://api.trakt.tv/oauth/authorize` returns aren't shared with `trakt.tv` because `api.trakt.tv` and `trakt.tv` are considered different domains and the cookies aren't explicitly set to be shared between the two domains.

### Proof to my guess

1. If I change the endpoint I use for authorization from `https://api.trakt.tv/oauth/authorize` (`api` subdomain) to `https://trakt.tv/oauth/authorize` (no subdomain), the use case 1 and 2 will work as expected.
2. I have another proof but I can't remember it at this moment, will edit this or add a comment when I recall it.

## Bigger Problem

As we can see, `api.trakt.tv` and `trakt.tv`'s sign-in states are isolated. There are 2 parallel sets of cookies. And the bigger problem is that **`api.trakt.tv`'s cookies can't be easily cleaned/invalidated.**

`trakt.tv`'s cookies can be cleaned/invalidated by hitting `https://trakt.tv/logout`, but `https://api.trakt.tv/logout` won't work.

Why this matters: for example, my app is using `https://api.trakt.tv/` as base URL, once a user connects his Trakt account, he/she won't be able to login to another account until the expiration time of cookies of `https://api.trakt.tv/` arrives.

## My Workaround

Using `https://trakt.tv/` (no subdomain) as base URL for OAuth related endpoints and using `https://api.trakt.tv/` (subdomain) as base URL for all other endpoints.

## Fix

I don't have much insight of this issue, but I do think this is a bug that needs to be fixed.

I don't like the workaround, because:

1. `https://trakt.tv/oauth/authorize` isn't documented (the doc shows using `https://api.trakt.tv/oauth/authorize` (subdomain): https://trakt.docs.apiary.io/#reference/authentication-oauth/authorize/authorize-application)
2. It doesn't make sense for my app to have a special base url.

**Comment by rectifyer** [comment]
Per the note in the docs (https://trakt.docs.apiary.io/#reference/authentication-oauth/authorize/authorize-application) and API example code.

> **Note:** You should use the normal https://trakt.tv hostname when creating this URL and not the API URL

The API docs are limited to only using a single hostname which is why we have a note for that method and the example code using `https://trakt.tv` as the hostname.

I'll need to look into the OAuth library we use and see if they have support for a `/logout` path to destroy cookies for the API URLs. However, if you use the `https://trakt.tv` hostname then `https://trakt.tv/logout` will work.

**Comment by ShaneQi** [comment]
Ah, I overlooked the note.

But still, I think we should deprecate `https://api.trakt.tv/oauth/authorize` since it doesn't fully work. Or make `https://api.trakt.tv/oauth/authorize` work as most developers expect (like you said: add `/logout`).

Anyways, as long as my 'workaround' is an officially approved practice, I'd consider my issue solved.

Thanks for the response and awesome API.

**Comment by ShaneQi** [comment]
PS: what could make even more sense is that both endpoints share the same sign-in state.
