### ISSUE TITLE
"List Comments" has optional authentication but it's not stated in the docs

### ISSUE THREAD

**Issue by minas1** [trakt/api-help#190]
I have noticed that the ["List Comments" API](https://trakt.docs.apiary.io/#reference/users/list-comments/get-all-list-comments) has optional authentication, but this is not stated in the documentation.

Update the documentation to mention it.

**Comment by rectifyer** [comment]
Updated

**Comment by minas1** [comment]
I still don't see _optional auth_ mentioned.

![SmartSelect_20200614-091742_Firefox](https://user-images.githubusercontent.com/1492092/84586250-81e9ef80-ae20-11ea-8e11-8dc9c4c1ac5b.jpg)
