### ISSUE TITLE
403 errors 

### ISSUE THREAD

**Issue by eliehaykal** [trakt/api-help#191]
Hello,
Some users are reporting 403 errors when trying to access Trakt from my app.
Are there any issues causing this? 
Also the http://status.trakt.tv/ site seems to be down.
Thanks

**Comment by rectifyer** [comment]
Please provide the full API request and response including headers. A 403 indicates an invalid API key.

The status page is loading ok for me, maybe a temporary glitch?

**Comment by UncleStark** [comment]
cloudfare shows captcha for users from Russia, therefore, 403, it affected me too. This is a problem.

**Comment by eliehaykal** [comment]
Yes it does appear as a temporary glitch because I've tried with many other
users and none seem to have any problems.
I just wanted to check if there was something hidden on the radar.

**Comment by eliehaykal** [comment]
> cloudfare shows captcha for users from Russia, therefore, 403, it affected me too. This is a problem.

That is true. 90% of the users reporting the issue are from Russia

**Comment by rectifyer** [comment]
I was able to make some updates in Cloudflare that might help with the captcha showing up. Please let me know if see any reports about things working better.

**Comment by UncleStark** [comment]
in this time nothing has changed

**Comment by UncleStark** [comment]
![image](https://user-images.githubusercontent.com/17180425/87002797-0bdc6c80-c1c3-11ea-9511-1529bcd4a9a1.png)
in this time nothing has changed

**Comment by eliehaykal** [comment]
Yes, I can confirm the issue still persists.

**Comment by rectifyer** [comment]
The Trakt website might still present a captcha, the change was made for the API side of things only.

**Comment by eliehaykal** [comment]
> The Trakt website might still present a captcha, the change was made for the API side of things only.

Some app users are reporting positive results. I'll keep you posted. Thanks for your efforts

**Comment by UncleStark** [comment]
whats name of you app?
