### ISSUE TITLE
Missing documentation for "last_activity" flag in "Get show watched progress" request?

### ISSUE THREAD

**Issue by henrikfroehling** [trakt/api-help#192]
I noticed the flag "last_activity" in the [request](https://trakt.docs.apiary.io/#reference/shows/watched-progress/get-show-watched-progress)'s documentation, but it there only mentions one possible value ('watched').
Is this the only possible value or can this flag have alternative values?

**Comment by rectifyer** [comment]
The default is `aired`. Not sure why the docs aren't rendering correctly, I'll look into that.
