### ISSUE TITLE
Pending follow request

### ISSUE THREAD

**Issue by Tiger3030** [trakt/api-help#194]
How can I find out if there is a pending follow request for a user?

After a follow request has been sent the button on trakt.tv turns to "pending approval". Is there a way to realise this in an app, too? Otherwise follow requests can be sent more than one time, which does not matter for the display on trakt.tv, but the other user recieves an email every time a follow request is sent.

**Comment by rectifyer** [comment]
https://trakt.docs.apiary.io/#reference/users/follower-requests/get-follow-requests

**Comment by Tiger3030** [comment]
This request returns the follow requests other users have sent to the authenticated user. But I need the follow requests the authenticated user has sent to other users.

**Comment by rectifyer** [comment]
Oh I see, no we don't have a way to get that data. It sounds like step 1 is not sending additional emails if they re-request it.

**Comment by rectifyer** [comment]
New API method added to get all pending following requests.

https://trakt.docs.apiary.io/#reference/users/following-requests/get-pending-following-requests
