### ISSUE TITLE
Getting "No records found." response on /scrobble/start for a show

### ISSUE THREAD

**Issue by dominika-matejkova** [trakt/api-help#195]
Hello,

I'm trying to send a request to the /scrobble/start endpoint with a TV show in the body like this:

```
{
    "show": {
        "ids": {
            "tvdb": 364928,
            "trakt": 136863
        },
        "year": 2020,
        "title": "Snowpiercer"
    },
    "episode": {
        "number": 1,
        "season": 1
    },
    "progress": 1
}
```

But I'm only receiving a "No records found." response. 

However, when sending a movie in the body, the endpoint is fine:
```
{
    "progress": 1,
    "ids": {},
    "year": 2014,
    "title": "Guardians of the Galaxy"
}
```

**Comment by rectifyer** [comment]
I just tested that above JSON and it worked fine when using /scrobble/start -- what are the exact headers and response you get from the API?
