### ISSUE TITLE
No X-Pagination-Page-Count header in updated movies request

### ISSUE THREAD

**Issue by linaspurinis** [trakt/api-help#198]
This call worked for months.
API call: movies/updates/2020-08-26?end_date=2020-08-29&page=1&limit=100

Returned Headers:
{'Date': 'Sat, 29 Aug 2020 08:38:13 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=00000000000000000000000; expires=Mon, 28-Sep-20 08:38:13 GMT; path=/; domain=.trakt.tv; HttpOnly; SameSite=Lax', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'X-Permitted-Cross-Domain-Policies': 'none', 'Referrer-Policy': 'strict-origin-when-cross-origin', 'X-Pagination-Page': '1', 'X-Pagination-Limit': '100', 'Expires': 'Sat, 29 Aug 2020 12:00:09 GMT', 'Cache-Control': 'public, max-age=28800', 'Vary': 'Accept-Encoding', 'Content-Encoding': 'gzip', 'ETag': 'W/"0000000000000000"', 'X-Request-Id': '0000000000000000', 'X-Runtime': '0.030426', 'CF-Cache-Status': 'HIT', 'Age': '16683', 'cf-request-id': '000000000000000', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5ca4f45f58ccb4e4-VNO'}
P.S. Id's changed to 0 for pasting.

From documentation: 
All paginated methods will return these HTTP headers.
Header | Value
X-Pagination-Page | Current page.
X-Pagination-Limit | Items per page.
X-Pagination-Page-Count | Total number of pages. | MISSING
X-Pagination-Item-Count | Total number of items. | MISSING

**Comment by rectifyer** [comment]
When I run that method, I see the headers. I'm not sure why you would be seeing any different.

```
x-pagination-page: 1
x-pagination-limit: 100
x-pagination-page-count: 54
x-pagination-item-count: 5400
```

**Comment by linaspurinis** [comment]
Any more info I could provide or some suggestions?

**Comment by rectifyer** [comment]
Not really sure, I'm not able to reproduce the issue and I see the correct headers when I make that exact API call.

**Comment by rectifyer** [comment]
I was finally able to reproduce this issue (missing headers) and just pushed out a fix. It will take a few hours for any cached responses to update.
