### ISSUE TITLE
scrobble/stop above 80% does not mark as watched

### ISSUE THREAD

**Issue by linaspurinis** [trakt/api-help#199]
I understand, what if you send scrobble/stop when the movie is already above 80% in progress, it will be marked as watched. But unfortunately, this is not the case. I always have to call sync/history API to mark movie as watched. Is this is intentional? 

From Documentation: "If the progress is above 80%, the video will be scrobbled and the action will be set to scrobble. "

Thank you.

**Comment by rectifyer** [comment]
What is the full API request and response?

**Comment by linaspurinis** [comment]
My bad, Plex does not provide progress when sending Stop. I was under the impression you not need to send progress if movie is already watched past this mark, it but you send Stop without progress, it does not Scrobble. Looks like expected behavior from Trakt side. Thank you.
