### ISSUE TITLE
Documentation for APIs not available?

### ISSUE THREAD

**Issue by MaxHasADHD** [trakt/api-help#20]
I was looking at the API documentation and found a few sections under `Sync` that don't seem to have end points? `Watched History Sync`, `Collection Sync`, and `Clean Collection`, are these just best sync practices we should take or is there supposed to be an API for these? The way the descriptions are written, it seems like an endpoint should exists.

**Comment by rectifyer** [comment]
They are just best practices for how to implement those scenarios. Each scenario uses multiple sync API methods.

**Watched History Sync**
1. `/sync/watched/:type` to pull down a user's full Trakt watched history for `shows` or `movies`
2. Compare that data to what you have locally
2. POST to `/sync/history` to send up any local plays that aren't on Trakt yet

**Collection Sync**
1. `/sync/collection/:type` to pull down a user's full Trakt collection for `shows` or `movies`
2. Compare that data to what you have locally
2. POST to `/sync/collection` to send up any local library items that aren't on Trakt yet

**Clean Collection**
1. Similar to `Collection Sync` but with using `/sync/collection/remove` to remove collected Trakt items if they don't exist locally in your library

**Comment by MaxHasADHD** [comment]
@rectifyer interesting. How should we handle items being deleted from Trakt / another app? Just delete anything locally that we believe to have been on Trakt before? Would hate to have users loop the same data getting deleted on Trakt and then re-added by my apps.

**Comment by rectifyer** [comment]
@MaxHasADHD yeah, you can remove locally if Trakt doesn't return it in the `/sync/watched/:type` data. You should still pull down all the data and compare if `last_activities` indicates something has changed.
