### ISSUE TITLE
Issues with adding TV shows

### ISSUE THREAD

**Issue by chrisbln** [trakt/api-help#201]
Adding a TV show has some issues. It says HTTP 201, but it didn't create a new TV show into the watchlist (or other lists).
Creating a new Postman Request ends in an HTTP 403. 

```
--> POST https://api.trakt.tv/sync/watchlist
Content-Type: application/json; charset=UTF-8
Content-Length: 280
{"episodes":[],"movies":[],"shows":[{"collected_at":"2020-08-31T15:53:14.422Z","ids":{"imdb":"tt6461346","mediaType":1,"tmdb":70626,"trakt":116840,"tvdb":324596},"mediaType":1,"rated_at":"2020-08-31T15:53:14.422Z","rating":0,"seasons":[],"watched_at":"2020-08-31T15:53:14.422Z"}]}
--> END POST (280-byte body)
<-- 201 https://api.trakt.tv/sync/watchlist (328ms)
date: Mon, 31 Aug 2020 15:53:19 GMT
content-type: application/json; charset=utf-8
set-cookie: __cfduid=d11c9be7032e0ac67e5c7a59e5e0d7ccf1598889199; expires=Wed, 30-Sep-20 15:53:19 GMT; path=/; domain=.trakt.tv; HttpOnly; SameSite=Lax
cache-control: max-age=0, private, must-revalidate
cf-railgun: 096cf54345 99.99 0.080858 0030 57da
etag: W/"32218beb663664559383608d97f53631"
referrer-policy: strict-origin-when-cross-origin
vary: Accept-Encoding
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-request-id: 215c31ae-0224-4bc0-839e-43fcec2d917a
x-runtime: 0.073417
x-xss-protection: 1; mode=block
cf-cache-status: DYNAMIC
cf-request-id: 04e6d21ef80000d45f4dae7200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5cb7ec77fdb4d45f-HAM
{"added":{"movies":0,"shows":0,"seasons":0,"episodes":0},"existing":{"movies":0,"shows":0,"seasons":0,"episodes":0},"not_found":{"movies":[],"shows":[],"seasons":[],"episodes":[],"people":[]}}
<-- END HTTP (192-byte body)
```

**Comment by rectifyer** [comment]
You are sending a blank seasons array, so there is nothing for it to add. I recommend sending the JSON as mentioned in the API examples, and not including all the extra and blank info.

https://trakt.docs.apiary.io/#reference/sync/add-to-watchlist/add-items-to-watchlist

**Comment by chrisbln** [comment]
Why you close the topic as a question? I am in huge trouble that the TV shows not working anymore.  It worked for the last 3 years and a few thousands of users per day cannot use the TV show feature anymore...

https://play.google.com/store/apps/details?id=com.moviebase

**Comment by rectifyer** [comment]
The JSON being sent is invalid if you are adding a TV show. Since `seasons` is sent, it is looking for the array of seasons to be added, but it is blank so nothing is added. If you match the JSON example in the API docs, then it should work. We didn't change anything related to this API, so not sure how the above would have worked previously.

**Comment by chrisbln** [comment]
Thank you. Weird issue :(
