### ISSUE TITLE
Getting OAuth access token fails with HTTP 503 since 2020-07-06

### ISSUE THREAD

**Issue by UweTrottmann** [trakt/api-help#204]
This only affects a fraction of users (300+). The reports surged as of 2020-07-06, have leveled off after 5 days, but are still higher than before.

I can't share a full response as clients only report the HTTP error code (503) and status message (here null) and method that failed.

The Trakt app is "SeriesGuide" (ID 343).

```
--> POST https://trakt.tv/oauth/token h2
Content-Type: application/x-www-form-urlencoded
Host: trakt.tv
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/4.7.2

grant_type=authorization_code&code=REDACTED&client_id=REDACTED&client_secret=REDACTED&redirect_uri=sgoauth%3A%2F%2Fcallback
--> END POST
<-- 503 https://trakt.tv/oauth/token
```

**Comment by UweTrottmann** [comment]
Update: I'm shipping an app update that will report back any [`error` and `error_description` in the response body](https://trakt.docs.apiary.io/#reference/authentication-oauth/authorize/exchange-code-for-access_token). Hopefully I can then provide more insight.

**Comment by rectifyer** [comment]
Ok cool, thank you. The more details and headers the better. This error actually looks to be happening on the website, not the API. Earlier this week we did some additional database updates to help with the stability and that's been looking good these last few days.

**Comment by UweTrottmann** [comment]
"website, not the API": huh, looking at the docs I just realized that tokens can also be retrieved via the API (tested and it works, if using a JSON body instead of sending form URL encoded). Currently using the website (see request above).

The update is not public, yet, so I'll make this change as well.

**Comment by rectifyer** [comment]
The `/oauth/authorize` link should use the main **trakt.tv** website, but otherwise **api.trakt.tv** should be used for everything. I didn't even realize it would work using the website endpoint to get the token 🤷 

Behind the scenes, I found an issue that seems to be related to the 500 error. Once of the backend services was getting overloaded during peak times so I fixed that. Hopefully the 500 errors fully go away now.

**Comment by UweTrottmann** [comment]
It was modelled after an OAuth library that follows the [OAuth RFC](https://tools.ietf.org/html/rfc6749#section-4.1.3) (e.g. also using a `application/x-www-form-urlencoded` body). As it worked using the website as the token endpoint I never really checked the docs to see it should be the API server and a JSON body. Also 🤷 

The user I troubleshooted this with could repro the `503` independent of time. They were also seeing a Cloudflare captcha when signing in. So my assumption is that due to the token getting fetched via the website, the app was getting the Cloudflare captcha as well and failed. Switching to the API server seems to have gotten rid of the captcha.

**Comment by rectifyer** [comment]
Good to know. And that does make sense on the captcha blocking the token generation if going through the website.
