### ISSUE TITLE
500 error on https://api.trakt.tv/people/2781/shows?extended=full

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#205]
I'm getting a 500 error for this actor's shows and I could reproduce 3 days in a row.

HTTP/1.1 500 Internal Server Error
Date: Mon, 14 Sep 2020 07:24:12 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: strict-origin-when-cross-origin
Expires: Mon, 14 Sep 2020 15:24:11 GMT
Cache-Control: public, no-cache, no-store
X-Error-Message: Internal server error. Please open a support issue and include your full API request and response, including all headers.
Vary: Accept-Encoding
X-Request-Id: 6fd7020d-929b-4164-aa0f-d905e2ac244b
X-Runtime: 0.059705
CF-Cache-Status: BYPASS
cf-request-id: 052d19078700000c2de784a200000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5d285dec0a4c0c2d-AMS

**Comment by rectifyer** [comment]
Just pushed a fix for this issue.
