### ISSUE TITLE
Way to get more than 100 changes at once

### ISSUE THREAD

**Issue by Js41637** [trakt/api-help#206]
The API endpoints to get movies and shows that have recently updated has recently been capped to 100 results at once, the docs have always stated this however the endpoint historically let you request a lot more. It makes sense to limit the amount of results at once but 100 seems very low, if you were to only request updates once a day (or even every few days), there could be thousands of changes and with 100 at a time you could be making upwards of 50 requests.

Do you think there is any chance we could up the limit to make it a bit less painful for getting changes? If the issue is performance related as the endpoint does return the title, year and ids, do you think it would be possible to look into an endpoint that just returns the trakt id? All we need (and I assume what most people need who are monitoring changes) is just to know what trakt shows have updated so all we need is the id.

If it isn't possible then the only real solution I have is to manually load a show details with `?extended=full` to see when it last updated which somehow seems worse and less performant than being able to use a changes endpoint.

Another issue I see is there is no way to get changes since a specific time? The API only accepts a `yyyy-mm-dd` style of date, even if I were to request changes every hour (which I can't anyway), it would still return changes for the whole day? Unless I am missing something, I couldn't get it to return changes since a specific date time.

Also there is another issue that I saw was also reported in #198, the endpoint does not add the `X-Pagination-Page-Count` and `X-Pagination-Item-Count` headers, I noticed that it sometimes returns it on the first request but in testing the same endpoint multiple times the header is not there anymore. 
![image](https://user-images.githubusercontent.com/6258213/93463276-e1c5ca00-f92a-11ea-8798-4d3eecd56a90.png)

Thank you.

**Comment by rectifyer** [comment]
We were running into issues with some apps requesting a huge amount of data, with extended info. That's when I noticed the bug where the limit wasn't being enforced correctly as mentioned in the API docs.

I'll look into your other suggestions about a lightweight ID only method and accepting more specific date ranges.

Also, please use api.trakt.tv as the hostname, that old one is unsupported.

**Comment by Js41637** [comment]
Thanks for the reply, an improvement to changes would definitely be ideal. At the moment for the project I use, in order to get updated shows it means we need to go through every show and check its last updated at which means if I have like 200 shows tracked, it requires 200 requests at minimum just to check what shows have changed, not even counting  how many more it takes if it a show has updated just to get the latest information. A more lightweight changes endpoint with a slightly higher limit and more specific date filters would go a long way to reducing the amount of requests required.

----

Also not related to this per se, currently it is quite hard to keep updated data, especially for shows, when requesting a shows full info it gives you the time a show was last updated which is useful to know if a show or its episodes have updated but it also means you then need to request the whole show, all its seasons and all its episodes to make sure you get the latest data and there isn't any way to know what specifically has changed.

If a show like The Expanse updates, it takes 7 requests at minimum to get the show, seasons and episodes. I think there is a way you could optimize this by making the seasons endpoint for a show return the time that a season last updated. This would mean if only Season 4 got a new episode, it would only require 3 requests to get the latest data instead of 7. 

If something like this is possible then it would make getting up to date data much easier and reduce the amount of requests required.

**Comment by rectifyer** [comment]
I pushed a few updates. API docs have also been updated as needed.

- `/shows/updates` and `/movies/updates` allow date and time. The time will be accurate to the hour (for caching purposes) but that should still give a much better degree of accuracy.
- new methods `/shows/updates/id` and `/movies/updates/id` to return only Trakt IDs that have been updated. 
- `/shows/:id/seasons?extended=full` includes the `updated_at` field.

**Comment by Js41637** [comment]
This is great news, thank you for this.

**Comment by jonathanantoine** [comment]
@rectifyer that's nice ! 

Any luck that you update the number of element returned by these endpoints ? 
There is a lot of updated shows and getting them 100 by 100 will make my apps send more requests than fetching each show information individually.

Thanks a lot for your recent work on the API !

**Comment by rectifyer** [comment]
No plans to increase the limit currently. I'll see how these latest updates go and then see if that's something we can do once I have more metrics on the API methods.
