### ISSUE TITLE
Collection metadata returns incorrect values

### ISSUE THREAD

**Issue by sharkykh** [trakt/api-help#209]
Hello,

I'm currently seeing two issues with the API in regards to metadata on "get collection" requests:

1. Collection metadata values used to be [as described on the API docs](https://trakt.docs.apiary.io/#reference/sync/add-to-collection/add-items-to-collection) (mostly strings, and one bool).
	However, now it seems the keys that should have string values have integer values instead, and AFAICT the API docs have no info for mapping those integers to string values.
2. `audio_channels` seems to be empty for all of my movie collection items even though I have it set.

Request: `https://api.trakt.tv/sync/collection/movies/?extended=metadata`

<details>
<summary>Response (Partial)</summary>

```json
[
    {
        "collected_at": "2019-01-01T00:39:23.000Z",
        "updated_at": "2020-04-17T19:56:52.000Z",
        "movie": {
            "title": "A Simple Favor",
            "year": 2018,
            "ids": {
                "trakt": 331407,
                "slug": "a-simple-favor-2018",
                "imdb": "tt7040874",
                "tmdb": 484247
            }
        },
        "metadata": {
            "media_type": 1,
            "resolution": 1,
            "hdr": null,
            "audio": 2,
            "audio_channels": null,
            "3d": false
        }
    },
    {
        "collected_at": "2019-08-25T16:13:05.000Z",
        "updated_at": "2020-08-10T23:54:39.000Z",
        "movie": {
            "title": "Booksmart",
            "year": 2019,
            "ids": {
                "trakt": 374133,
                "slug": "booksmart-2019",
                "imdb": "tt1489887",
                "tmdb": 505600
            }
        },
        "metadata": {
            "media_type": 1,
            "resolution": 1,
            "hdr": null,
            "audio": 2,
            "audio_channels": null,
            "3d": false
        }
    }
]
```

</details>

<details>
<summary>Movies on Trakt.tv</summary>

![mbdZR6Yg9X](https://user-images.githubusercontent.com/10238474/94008520-d0a60e80-fdab-11ea-9fd8-135285854ada.png)
![chrome_u0vVkePv23](https://user-images.githubusercontent.com/10238474/94008552-de5b9400-fdab-11ea-8f51-0121ed4b27df.png)

</details>

Thanks in advance! 😄

**Comment by rectifyer** [comment]
I just pushed a fix for this, please let me know if it's working ok for you now. It might take a few hours (or until you collect something new) before the cached data updates.

**Comment by sharkykh** [comment]
I just deleted my collection and resynced it, I'm getting the same values.
I don't think it's cache, as I synced my collection without metadata first and I saw the `null` values.

Request:
```http
GET https://api.trakt.tv/sync/collection/movies/?extended=metadata
```

Header | Value
-- | --
Accept | `*/*`
Authorization | `Bearer <access_token>`
Content-Type | `application/json`
trakt-api-key | `<client_id>`
trakt-api-version | `2`

Response:

Header | Value
-- | --
cache-control | `max-age=0, private, must-revalidate`
cf-cache-status | `DYNAMIC`
cf-railgun | `daa9f2434d 99.99 0.204914 0030 57da`
cf-ray | `5d7b440b682805f9-FRA`
cf-request-id | `0560e8db20000005f939b12200000001`
content-encoding | `br`
content-type | `application/json; charset=utf-8`
date | `Thu, 24 Sep 2020 08:51:49 GMT`
etag | `W/"824a15ed4360f8263f6d4418d3794388"`
expect-ct | `max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"`
last-modified | `Thu, 24 Sep 2020 08:51:34 GMT`
referrer-policy | `strict-origin-when-cross-origin`
server | `cloudflare`
status | `200`
vary | `Accept-Encoding`
x-content-type-options | `nosniff`
x-download-options | `noopen`
x-frame-options | `SAMEORIGIN`
x-permitted-cross-domain-policies | `none`
x-request-id | `f302d722-e8b2-475d-ba23-42950c43c2f0`
x-runtime | `0.199469`
x-xss-protection | `1; mode=block`

Body (partial):
```json
[
    {
        "collected_at": "2016-04-01T12:35:42.000Z",
        "updated_at": "2020-09-24T08:51:33.000Z",
        "movie": {
            "title": "Star Wars",
            "year": 1977,
            "ids": {
                "trakt": 7,
                "slug": "star-wars-1977",
                "imdb": "tt0076759",
                "tmdb": 11
            }
        },
        "metadata": {
            "media_type": 0,
            "resolution": 3,
            "hdr": null,
            "audio": 4,
            "audio_channels": null,
            "3d": false
        }
    }
]
```

**Comment by rectifyer** [comment]
Weird, I'll redeploy the fix to the API servers and see if that gets its working consistently. Should be live in about an hour.

**Comment by sharkykh** [comment]
I'm getting the same result unfortunately. (I deleted my collection and resynced it)

Header | Value
-- | --
cache-control | max-age=0, private, must-revalidate
cf-cache-status | DYNAMIC
cf-railgun | 26476273bd stream 0.000000 0230 57da
cf-ray | 5d8068224d7dd711-FRA
cf-request-id | 05641f696c0000d7112204d200000001
content-encoding | br
content-type | application/json; charset=utf-8
date | Thu, 24 Sep 2020 23:50:16 GMT
etag | W/"6dd493282e7db3d38048bb993d01c73c"
expect-ct | max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
last-modified | Thu, 24 Sep 2020 23:49:17 GMT
referrer-policy | strict-origin-when-cross-origin
server | cloudflare
status | 304
vary | Accept-Encoding
x-content-type-options | nosniff
x-download-options | noopen
x-frame-options | SAMEORIGIN
x-permitted-cross-domain-policies | none
x-request-id | aa176b3f-faa1-4be2-9f0e-b6b0c8223107
x-runtime | 0.024563
x-xss-protection | 1; mode=block

**Comment by sharkykh** [comment]
I got the 'correct' response once or twice now, but only on the REST API client, never through my Python script.
But now they are **both** back to the 'bad' response.

**Comment by rectifyer** [comment]
I think we hopefully fixed it. There seemed to be an issue with the auto scaling of the API servers.

**Comment by sharkykh** [comment]
Seems to work well now, both REST Client and Python script. Thanks! 🎉

**Comment by Pomanks** [comment]
I caught another issue on the metadata response. When the audio channel is set to `10.1`, the response returns a `1.0.1` value instead. Is this normal behavior or literally a bug?

Request Body: 
```
{
  "movies" : [
    {
      "ids" : {
        "tmdb" : 299534,
        "slug" : "avengers-endgame-2019",
        "trakt" : 191798,
        "imdb" : "tt4154796"
      },
      "hdr" : "dolby_vision",
      "media_type" : "digital",
      "collected_at" : "2019-04-26T21:00:00.000+0000",
      "3d" : false,
      "audio_channels" : "10.1",
      "resolution" : "uhd_4k",
      "audio" : "dolby_digital_plus_atmos"
    }
  ]
}
```

When getting the collection:
```
 "movie" : {
      "released" : "2019-04-26",
      "ids" : {
        "tmdb" : 299534,
        "slug" : "avengers-endgame-2019",
        "trakt" : 191798,
        "imdb" : "tt4154796"
      },
      "rating" : 8.5081600000000002,
      "comment_count" : 177,
      "certification" : "PG-13",
      "trailer" : "http:\/\/youtube.com\/watch?v=TcMBFSGVi1c",
      "runtime" : 181,
      "title" : "Avengers: Endgame",
      "overview" : "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
      "homepage" : "https:\/\/www.marvel.com\/movies\/avengers-endgame",
      "available_translations" : [
        "ar",
        "bg",
        "cs",
        "da",
        "de",
        "el",
        "en",
        "es",
        "fa",
        "fi",
        "fr",
        "he",
        "hi",
        "hr",
        "hu",
        "id",
        "it",
        "ja",
        "ka",
        "ko",
        "lt",
        "lv",
        "nl",
        "no",
        "pl",
        "pt",
        "ro",
        "ru",
        "sk",
        "sl",
        "sr",
        "sv",
        "ta",
        "te",
        "th",
        "tr",
        "uk",
        "uz",
        "vi",
        "zh"
      ],
      "updated_at" : "2021-03-04T08:22:23.000Z",
      "year" : 2019,
      "language" : "en",
      "tagline" : "Part of the journey is the end.",
      "genres" : [
        "action",
        "adventure",
        "science-fiction"
      ],
      "country" : "us",
      "status" : "released",
      "votes" : 33226
    },
    "metadata" : {
      "3d" : false,
      "audio" : "dolby_digital_plus_atmos",
      "hdr" : "dolby_vision",
      "audio_channels" : "1.0.1",
      "media_type" : "digital",
      "resolution" : "uhd_4k"
    },
    "updated_at" : "2021-03-04T17:09:44.000Z",
    "collected_at" : "2019-04-26T21:00:00.000Z"
  }
```
