### ISSUE TITLE
Add option to return emojis in unicode format

### ISSUE THREAD

**Issue by minas1** [trakt/api-help#211]
When getting **comments**, emojis are returned as short codes.

To parse them, apps need to use third-party libraries as short codes are not standardized. This is additional effort and also the app's size is increased, as normally those libraries contain a JSON file with the mapping. 

Please add an option to return the emojis in their unicode format (e.g. 😀).

Something like: `/comments?emojis-as-unicode=true` (or whatever you want to call it).

**Comment by rectifyer** [comment]
The main reason we don't do support this is that would essentially double the cached data by having 2 emoji versions. Is the 3rd party library that large when added to your app?
