### ISSUE TITLE
Staging API 502 bad gateway

### ISSUE THREAD

**Issue by Larsg310** [trakt/api-help#213]
Hi,

It seems like the Trakt staging API has been returning a 502 bad gateway error the last couple of days. It happens in both the browser and my program. The normal API seems to be working fine

![image](https://user-images.githubusercontent.com/5021026/94718782-80eab880-0352-11eb-8c25-24c1eb377416.png)

![image](https://user-images.githubusercontent.com/5021026/94718700-64e71700-0352-11eb-8443-4ae9d2d31c0f.png)

Any idea what's up?

**Comment by rectifyer** [comment]
Staging has some issues (as you've seen) and I need to rebuild the server. Hopefully I can get to that soon.

**Comment by rectifyer** [comment]
Still working on staging, but it is working in a limited capacity so far.

**Comment by rectifyer** [comment]
Staging should be all up and running now. I'm reindexing the solr search service so those results will improve throughout the day. In general, the website and API should be working now though.
