### ISSUE TITLE
How to get Up next to watch episodes from API?

### ISSUE THREAD

**Issue by praveen-wal** [trakt/api-help#215]
I am trying to create an App using this API. Is there any specific API that I can call to fetch the next episodes to watch like, [Check here](https://i.imgur.com/bb1vPnb.png)? Or is there a process that I have to get the list?

**Comment by rectifyer** [comment]
We don't have an API for global progress due to performance reasons. You can get an individual show's detailed progress info if needed, but my recommendation is to grab the user's watched history using `/sync/watched/shows` then compare that to the show data you have locally cached in your app.
