### ISSUE TITLE
502 on prod endpoint api.trakt.tv

### ISSUE THREAD

**Issue by akitikkx** [trakt/api-help#216]
Hi there, 

I have been getting a lot of 502 errors when trying to access api.trakt.tv

![device-2020-10-04-142839](https://user-images.githubusercontent.com/2282990/95015643-4f256a80-064e-11eb-8f33-58a5d8b19031.png)
![device-2020-10-04-143311](https://user-images.githubusercontent.com/2282990/95015689-9ad81400-064e-11eb-8dc7-a9eb06a88509.png)

Sometimes a refresh of the browser helps but sometimes the 502 persists

Thank you in advance

**Comment by rectifyer** [comment]
This is related to the ongoing performance and database issues we are working on. It looks like you're accessing an API URL in a browser view, I'd recommend using the standard trakt.tv domain for the OAuth URL as indicated in the API docs.

https://trakt.docs.apiary.io/#reference/authentication-oauth/authorize/authorize-application
