### ISSUE TITLE
IMDB ID Lookup problem

### ISSUE THREAD

**Issue by NePheus** [trakt/api-help#22]
There are problems using the /search/imdb/[imdbid] api method. I.e. the movie "Mia and the white lion" has the IMDB Id "tt6249748" connected, but IMDB itself has the id "tt4844148" for this movie. However, imdb seems to have a redirect from tt6249748 to tt4844148, so whenever I try to call the imdb detail page, I get redirected to https://www.imdb.com/title/tt4844148/. Unfortunately the trakt api call returns an empty result, because it does not recognize the redirect.

**Comment by rectifyer** [comment]
We don't have a way to attach multiple IMDB IDs to a single movie. However, I assume changing the IMDB ID on the TMDB entry will fix this. Trakt will sync with that change about 24 hours after it is updated on TMDB.
