### ISSUE TITLE
Could you find away to integrate with tvtime?

### ISSUE THREAD

**Issue by Behinder** [trakt/api-help#221]
I would like to use trakt more but tvtime folks are hostile for users who only wants to sync their watch history

**Comment by rectifyer** [comment]
They would need to integrate on their side, not sure they want to. They do have an API, but last I looked it was too limited for use. They have docs at https://api.tvtime.com/doc if you want to try any sort of integration or syncing between the 2.

**Comment by Behinder** [comment]
Well I tried once with them and they were not friendly and they said they
not share their APIs. Thanks for pointing that out it looks something
changed on their side.
I will take a look, maybe I figure it out for Apple Shortcuts. Trakt API
looks sooo complex.

**Comment by rectifyer** [comment]
Hopefully the Trakt API isn't complex, but it for sure is more full featured then it looks like TV Time  offers.

**Comment by Behinder** [comment]
Unfortunately I request access to their API and they never responded :(

**Comment by rectifyer** [comment]
Yeah, I don't think they want to integrate with Trakt unfortunately.

**Comment by Behinder** [comment]
Which is really a bummer, because even if they does not want to
integrate currently there is no way to export all my data from tv time
and import them to Trakt :(
