### ISSUE TITLE
Keep getting error 403

### ISSUE THREAD

**Issue by MMarco94** [trakt/api-help#223]
Starting from a few days ago, we keep receiving error 403 for all API calls. We wonder whether this is related to the limits you put in place.
Our apps synchronize to Trakt via our servers, so it's possible that you saw a lot of connections coming from the same IP. 

We're more than willing to change the API rate and introduce some kind of throttling, if that was the problem. How can we confirm this theory?

**Comment by rectifyer** [comment]
A 403 error indicates an invalid API key.

https://trakt.docs.apiary.io/#introduction/status-codes

**Comment by rectifyer** [comment]
Handled via support.

**Comment by MMarco94** [comment]
Looking more into the issue, it seems our app `FEMA TV Series` (id = 1105) is not "Approved" anymore. 
We didn't receive any communication about this. What happened? Can we get it approved again?
