### ISSUE TITLE
Seeing an increased number of `521` error responses

### ISSUE THREAD

**Issue by chearmstrong** [trakt/api-help#225]
Example request: https://api.trakt.tv/movies/trending?genres=superhero&page=1&limit=200&ratings=61-100

Is this an ongoing performance issue?

**Comment by MaxHasADHD** [comment]
Seeing this as well. We should be seeing `429` for rate limiting right?

**Comment by eliehaykal** [comment]
Yes I can confirm this too

**Comment by michaldrabik** [comment]
Lately I'm seeing this as well. Cloudflare 521's and 502's are appearing quite often.

**Comment by jonathanantoine** [comment]
Seeing this too :(

![Screenshot_1605464958](https://user-images.githubusercontent.com/3800550/99193401-f4b51900-2778-11eb-9592-189762a96d6b.png)

**Comment by rectifyer** [comment]
More info here:
https://blog.trakt.tv/trakt-performance-upgrades-c82f5db61f52
