### ISSUE TITLE
constantly getting errors

### ISSUE THREAD

**Issue by zayn666** [trakt/api-help#229]
this is probably not the best place for this but i want to talk about it..
since ive started to use trakt i get to the cloudflare page half the times i use trakt. sometimes it happens while im using it and switch to a different page. 

i noted today that it gave me a 502 (on the other times i never looked at the code)

is this normal? is this issue noted?

**Comment by rectifyer** [comment]
Related to this:
https://blog.trakt.tv/trakt-performance-upgrades-c82f5db61f52

**Comment by zayn666** [comment]
ok its just that imo something its not right, has a reason been identified? is there load balancing in place?
