### ISSUE TITLE
Invalid json

### ISSUE THREAD

**Issue by luisrecuenco** [trakt/api-help#23]
I just came across an issue while retrieving the following responses from the api:

```
https://api.trakt.tv/shows/60156/seasons?extended=full,episodes
https://api.trakt.tv/shows/2211/seasons?extended=full,episodes
```

The response is not a valid json.

**Comment by rectifyer** [comment]
What is invalid about the JSON? Those methods seem to load ok for me.

This might have been fixed from https://github.com/trakt/api-help/issues/27.

**Comment by luisrecuenco** [comment]
The links seem to be working fine at the moment. Not sure what the problem really was, but I'm glad the problem is gone 😄
