### ISSUE TITLE
Too frequent status changes of a show

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#230]
Hello,

Some show are changing really often of status (Dexter, The Haunting, etc.).
Is there an issue logged related to this ?

Regards.

**Comment by rectifyer** [comment]
We get the show status from TMDB, my guess is the status is changing over there which Trakt then picks up with our nightly update process. TMDB has a changelog to see which edits have been made for a show.

**Comment by jonathanantoine** [comment]
Unfortunately this is not the case 😓. Dexter has only one change in 2013 for instance.

Can you please help me on this matter 🥺! 

I use this information to tell users that a show has changed status and it's spamming them 😓

Do you have the same kind of show information changelog on trakt ?

Thanks !

![Screenshot_2020-11-20-07-28-49-369_com microsoft emmx](https://user-images.githubusercontent.com/3800550/99766842-355abc80-2b02-11eb-9a27-74f921c2be75.jpg)

**Comment by jonathanantoine** [comment]
Any update @rectifyer ?

**Comment by rectifyer** [comment]
The issue seems to be TVDB has the show as "continuing" and TMDB has it "ended". I think that is creating a conflict. I'll test this show out more and it seems like I'll need to more strictly set a preference.

**Comment by webash** [comment]
For additional data points: Whose Line Is It Anyway (US) is also doing this

**Comment by rectifyer** [comment]
I'll make an update later this week so it will use only the TVDB status if TVDB is the primary data source (which it is for these shows).

**Comment by jonathanantoine** [comment]
Thank you @rectifyer !

**Comment by rectifyer** [comment]
Update is live so the status shouldn't toggle between TMDB and TVDB. It will still update if the primary data source changes though.
