### ISSUE TITLE
App not approved

### ISSUE THREAD

**Issue by MMarco94** [trakt/api-help#231]
It seems our app `FEMA TV Series` (id = 1105) is not "Approved" anymore. 
We didn't receive any communication about this. What happened? Can we get it approved again?

Our apps synchronize to Trakt via our servers, so it's possible that you saw a lot of connections coming from the same IP.

We're more than willing to change the API rate and introduce some kind of throttling, if that was the problem. How can we confirm this theory?

**Comment by rudf0rd** [comment]
Hey Marco,

Apologies for not getting an email about this.  We were moving fast to keep the database up.  There were a handful of apps, yours included, which were duplicating users libraries into the hundreds of thousands of plays (in some cases, millions).  We revoked these API keys to alleviate the pressure on our database.

Our current guess is that that the applications we saw this behavior with went something like this:

1. App tries to sync user history
2. Servers are responding slowly, and one of the following happens:
  a.  Our server times out, but the database insert does occur
  b.  The database insert occurs, but timeout configured on the application side triggers and the app tries to sync again
3. Repeat until the servers calm back down and a successful 2xx is returned

There is another less common (and frankly, very broken) possibility where an application is checking a Trakt user history with one type of id (imdb, tmdb, tvdb, etc), but pushing up a different id.

I'll try to find an example and email you on the account attached to your app.
