### ISSUE TITLE
Get Calendar entries with unwatched items only

### ISSUE THREAD

**Issue by greatvc** [trakt/api-help#232]
Hi,

I want to get a list of episodes on the month that are left to watch before today. I tried with the calendar api but i get also the watched ones. Can this be filtered out ? i cannot even see a flag on the output that i can parse from (like i do not get a last_watched_at part). Or maybe another call api that will return for the month November , until today my unwatched only episodes (or shows i do not care).

I'm using now

```
import urllib.request
req = urllib.request.Request('https://api.trakt.tv/calendars/my/shows/2020-11-1/28?')
req.add_header('authorization', 'Bearer <token>')
req.add_header('trakt-api-version', '2')
req.add_header('trakt-api-key', '<key>')
arxeio=open("c:\Calendar.txt","w")
with urllib.request.urlopen(req) as f:
	#title= print(f.read().decode('utf-8'))
	arxeio.write(str(f.read()))

arxeio.close
```

The output is the file attached.

Any help will be greatly appreciated.

Regards,
Vassilis
[Calendar.txt](https://github.com/trakt/api-help/files/5568033/Calendar.txt)

**Comment by rectifyer** [comment]
The calendar API doesn't have a way to do that since the data is cached and shared across users. I'd recommend doing this filtering locally in your app. You can get use `/sync/watched/shows` then use that to remove any calendar items the user has already watched.

**Comment by greatvc** [comment]
yes , i did some more digging and that what i thought, i will catch from the calendar each show and then call it another API for the show and check the last_watched_at part.

thanks!
