### ISSUE TITLE
Last Activities is not updated when there is a new follower request

### ISSUE THREAD

**Issue by Tiger3030** [trakt/api-help#234]
Thank you for adding the new pending follow requests endpoint. I have tested it extensively and everything works as exspected.

However I have noticed that the "_all_"-timestamp in `/sync/last_activities` does not change if there is a new follow request from another user (another user has sent a follow request to the authenticated user). Is this a bug or intended?

Apart from that I think it would be a good idea to add a "_requested_at_"-timestamp to "_account_" in `/sync/last_activities`, which shows when `/users/requests` has changed, i.e. another user has sent a follow request to the authenticated user.

**Comment by Tiger3030** [comment]
> are you asking to add `requested_at` when someone tries to follow them?

Yes, exactly. 

This way you would only have to call `/users/requests` if there are new follow requests and not every time the app syncs with trakt, which would lead to less api calls.

**Comment by rectifyer** [comment]
This update will go out tomorrow. API docs are updated.
