### ISSUE TITLE
Documentation for "Shows/Summary/Get a single show" is not up-to-date

### ISSUE THREAD

**Issue by henrikfroehling** [trakt/api-help#235]
One of my library users got an "upcoming" status for a show, which is not documented in the [API Docs](https://trakt.docs.apiary.io/#reference/shows/summary/get-a-single-show).
Maybe there are also more status values missing?

**Comment by rectifyer** [comment]
Good catch, API docs updated. TMDB and TVDB have different statuses which is why there were a few missing in the docs.
