### ISSUE TITLE
Meaning of `not_found`

### ISSUE THREAD

**Issue by MaxHasADHD** [trakt/api-help#238]
Could I get clarification on the `not_found` object returned with many of the responses? Does the meaning ever change? e.g. when adding an item to a list does it mean that the object with that ID is not found on Trakt.tv? when removing an item from a list does it mean the item is not found on that list? Changing my app to group / batch updates to each POST / DELETE has me looking into these more to properly update objects in the app and want to make sure I'm handling it right.

Also would I be right in deleting my apps cache of list items when removing them from a list if I get a 200 regardless of the contents? If the item isn't found (either on Trakt or in the list depending on the meaning) then I should remove that item anyways, right?

**Comment by rectifyer** [comment]
not_found means we couldn't find the movie/show/episode on Trakt given the parameters passed in for that media object. It should be the same behavior everywhere since it is a shared function behind the scenes to parse and lookup all the media objects.

For lists, yes that sounds correct.
