### ISSUE TITLE
Text Query Search responds with wrong number of objects

### ISSUE THREAD

**Issue by henrikfroehling** [trakt/api-help#239]
Tried the following request `/search/show?query=a&page=1&limit=3`.
The response contains 5 objects and not the expected 3.

```json
[
    {
        "type": "show",
        "score": 1000,
        "show": {
            "title": "A",
            "year": 2017,
            "ids": {
                "trakt": 153177,
                "slug": "a-2019",
                "tvdb": 367354,
                "imdb": null,
                "tmdb": null,
                "tvrage": null
            }
        }
    },
    {
        "type": "show",
        "score": 1000,
        "show": {
            "title": "A",
            "year": null,
            "ids": {
                "trakt": 152713,
                "slug": "a",
                "tvdb": 369542,
                "imdb": null,
                "tmdb": null,
                "tvrage": null
            }
        }
    },
    {
        "type": "show",
        "score": 175.0116,
        "show": {
            "title": "Once Upon a Time",
            "year": 2011,
            "ids": {
                "trakt": 39108,
                "slug": "once-upon-a-time",
                "tvdb": 248835,
                "imdb": "tt1843230",
                "tmdb": 39272,
                "tvrage": 28385
            }
        }
    },
    {
        "type": "show",
        "score": 167.76587,
        "show": {
            "title": "Making a Murderer",
            "year": 2015,
            "ids": {
                "trakt": 103423,
                "slug": "making-a-murderer",
                "tvdb": 303210,
                "imdb": "tt5189670",
                "tmdb": 64439,
                "tvrage": null
            }
        }
    },
    {
        "type": "show",
        "score": 149.28644,
        "show": {
            "title": "The A-Team",
            "year": 1983,
            "ids": {
                "trakt": 1506,
                "slug": "the-a-team",
                "tvdb": 77904,
                "imdb": "tt0084967",
                "tmdb": 1516,
                "tvrage": 5516
            }
        }
    }
]
```

The count seems to be off by 2. Tested also with `limit=8` and got 10 objects.

**Comment by rectifyer** [comment]
This is a side effect of injecting exact matches into the results. There isn't an easy way around this unfortunately.

**Comment by mpfc75** [comment]
What is 'injecting exact matches into the results'? Is there another / better way to preform a search in an app UI as the user types their search criteria?

**Comment by tysonkerridge** [comment]
> What is 'injecting exact matches into the results'? Is there another / better way to preform a search in an app UI as the user types their search criteria?

Based on the results JSON in the first post, the query asked for 3 results which were fetched based on various criteria (see how each has a score). Then, it looks like there's at least two search results that match the term "a" exactly, which were returned alongside those 3 top results to make 5. This is the side effect mentioned, I believe. If you searched something that didn't have any exact matches you'd not run into this side effect.

**Comment by mpfc75** [comment]
Hello Tyson. Thanks for the reply. I believe I understand your explanation. I never really paid attention to the score before. Is that a measure of how close the item matches the search criteria? The higher the score, the better the match?

**Comment by tysonkerridge** [comment]
Yeah, I believe so
