### ISSUE TITLE
How to create a recommendation ?

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#240]
Hello,

Sorry if it's a dumb question, I already looked in the doc but I didn't find how to create a recommendation as "ask to be done" in this doc : https://trakt.docs.apiary.io/#reference/users/personal-recommendations/get-personal-recommendations ?

Thanks !

**Comment by tysonkerridge** [comment]
https://trakt.docs.apiary.io/#reference/sync/add-to-personal-recommendations/add-items-to-personal-recommendations

Perhaps you're looking for this?

**Comment by jonathanantoine** [comment]
That's it, thanks a lot !
