### ISSUE TITLE
API timing out

### ISSUE THREAD

**Issue by marovargovcik** [trakt/api-help#241]
Hi,

there are few endpoints that never return a response and requests will eventually timeout. It is not 100% of time. One day it works, next day it does not.

Affected endpoints (the ones I discovered, there may be more):
POST /sync/ratings
POST /sync/ratings/remove
POST /users/<user_id>/lists
PUT /users/<user_id>/lists/<list_id>
DELETE /users/<user_id>/lists/<list_id>

Even official website is affected. 

#186 seems to be about the same issue.

**Comment by Mihai-B** [comment]
Can confirm. If you post a rating using the API, the rating will be added as expected, but the request will time out.

**Comment by michaldrabik** [comment]
Many users still report this issue. Could we at least get a comment about status on this? Like are you guys aware of this, is this fixable or is this a no-fix?

Regards

**Comment by eliehaykal** [comment]
Any update on this? Still getting some negative feedback regarding the rating endpoint

**Comment by michaldrabik** [comment]
@eliehaykal Ouch this is disturbing because last I heard it should be fixed:
![obraz](https://user-images.githubusercontent.com/11537045/103874004-ec21f480-50d0-11eb-9a5d-6dffdce0eaee.png)

**Comment by rectifyer** [comment]
Yes, ratings should be fixed. We aren't seeing any issues in our internal stats to indicate it's not. Please provide a full API request and response if ratings aren't working.
