### ISSUE TITLE
Shows / Movie of a people belonging to the current user collection

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#246]
Hello,

I noticed in the beautiful app you are building on ios that when you open the details page of some one (exemple : the creator of a tv show) you display all the show belonging to the user in a separate section. 

I love the idea : where do you get this information ?

Thanks !

**Comment by kevincador** [comment]
I guess you can do that with the user's history. What would be interesting for me is the "known for" part. Would be great if you could open that info in the public api.

**Comment by rectifyer** [comment]
The [person summary method](https://trakt.docs.apiary.io/#reference/people/summary/get-a-single-person) returns `known_for_department` which you can use to grab movies/shows in their main department.

The "from your history" section just does some in app comparisons with that above list and things you've watched.

I believe the "popular items" also pulls from that main department, and orders it by the most popular.

**Comment by jonathanantoine** [comment]
Thanks for the answer @rectifyer
In app comparison means that we download the user collection first. It means a lot of calls to the API first. It may be better for it's sake to get it elsewhere but your solution works.
