### ISSUE TITLE
Request to treat HEAD specifically in the rate limits

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#247]
@rectifyer in lists in my app I'm using HEAD requests to just check/fetch minimal info when I just need the number of likes or the number of items in a list. I'm just looking at the pagination headers to get the latest and lightest value for the number of items.

My issue is that first, the HEADs were treated as GET method when looking at rate limits. It was okay, not great.
Now I see that they are treated as POST requests (I'm getting "AUTHED_API_POST_LIMIT" in the headers).

Since POST rate limits are 1 every 1 second, it introduce a delay updating some info when a user is scrolling in a list. It became a bit worst.
If I'm using a GET instead of a HEAD it's a bit better but then I hit the limit really fast when the user scrolls a lot in lists and I'm fetching more data than I need.

Would it be possible to treat the HEAD requests with a specific rate limit? Something similar or higher than the GET requests.

Thanks!

**Comment by rectifyer** [comment]
Closing since there is another topic about this at https://github.com/trakt/api-help/issues/291. Please provide an exact API request and headers, just so I can use the same test case.
