### ISSUE TITLE
Reorder List Items

### ISSUE THREAD

**Issue by linaspurinis** [trakt/api-help#256]
I have a question regarding API call Reorder List Items https://api.trakt.tv/users/id/lists/reorder

What is the fastest way to sort the large list after adding a single item to it? 
From the documentation I understand, what in order to sort I have two options:
1.  Reread the whole list (since the newly added item would have some unique ID assigned to it which I would need for sorting, so I have to reread the whole list and match the ids). Match, sort post the reorder API.
2. Delete the whole list and read all items in the correct order.

Both seem like unnecessary heavy work for a single task. Why I cannot sort using traktid? I would be able to add a single item and post the reorder IDs list via API. But API call requires a unique number for the list item which is unknown to me...

Thank you.

**Comment by rectifyer** [comment]
That would require sending the Trakt ID and the item type, then we'd need to lookup each of those items to see if we find a match. I just used the list item ID for simplicity and speed.

Adding a new item will add it to the end of the list already. Why do you need to reorder it?
