### ISSUE TITLE
TV Show duplicate

### ISSUE THREAD

**Issue by tdeverx** [trakt/api-help#26]
The TV Show Project Blue Book is duplicated

**Comment by tysonkerridge** [comment]
Pretty sure duplicates are requested to be submitted via the [support](https://support.trakt.tv) page, and including links to the two and which is the duplicate etc 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tdeverx** [comment]
Oops, my bad. I'll remove this 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tysonkerridge** [comment]
All good. Maybe we can add something to the description about that @rectifyer

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
