### ISSUE TITLE
Hide this show/Archive Capabilities

### ISSUE THREAD

**Issue by tomacotuna** [trakt/api-help#268]
I was looking on the API methods to see how you could "imitated" the functionality of the "Hide this show" button that is presented on the Trakt.tv website in Calendar page and probably other part as well.

I wanted to implement this functionality in my app as well and sync it with the Trakt.tv server.

**Comment by tomacotuna** [comment]
I think this might be the endpoint (https://trakt.docs.apiary.io/#reference/recommendations/hide-show/hide-a-show-recommendation) judging by the name and description. But its a bit confusing why it is under recommendations, since Calendar doesnt seem to be a recommendation place, and my second unknown fact is how will I identify a show that has been hidden when doing the sync between session. Will i just not receive the show or will it contain some variable letting me know that I should treat this show differently.

**Comment by tysonkerridge** [comment]
Probably looking for this: https://trakt.docs.apiary.io/#reference/users/add-hidden-items/add-hidden-items

**Comment by tomacotuna** [comment]
Yes that seems to be it, will test to see how it interacts with the sync api but i assumes once it is hidden I wont be getting that item anymore. Thanks 🙏
