### ISSUE TITLE
Personal Recommendations - Adding notes

### ISSUE THREAD

**Issue by eliehaykal** [trakt/api-help#270]
Hello,

I am trying to use the "https://api.trakt.tv/sync/recommendations" call to add a note as per the API documentation "https://trakt.docs.apiary.io/#reference/sync/add-to-personal-recommendations/add-items-to-personal-recommendations"

The notes field never gets populated as you can see in the below response, however, I can see the movie added to _**Personal Recommendations list**_
Sample Response:
    `{
      "rank": 1,
      "id": 578370339,
      "listed_at": "2021-03-08T17:14:16.000Z",
     "notes": null,
      "type": "movie",
      "movie": {
        "title": "Ariel",
        "year": 1988,
        "ids": {
          "trakt": 1,
          "slug": "ariel-1988",
          "imdb": "tt0094675",
          "tmdb": 2
        }
      }
    }`

**Comment by eliehaykal** [comment]
@rectifyer I appreciate if you can shed some light on this.

**Comment by rectifyer** [comment]
I found a bug and will have a fix out later this week. Thanks for letting us know!
