### ISSUE TITLE
Problem with networks filter and Unicode network names

### ISSUE THREAD

**Issue by arcsur** [trakt/api-help#273]
After obtaining the list of network names using the `/networks` endpoint I am trying to pass the names to the /shows/trending and `/shows/popular` endpoints as a filter using the `networks` URI parameter.  This works fine for network names within the ASCII charset.  

If the network name requires unicode chars it needs to be encoded which I am doing as UTF-8 and urlencoding,  This is exactly the same behaviour that occurs in Apiary API testing.  However, for any network that has characters not in the ASCII charset I always get an empty array back for `/shows/trending` and `/shows/popular` despite encoding and urlencoding.

I think the API for networks filter may have a bug in that it is not correctly decoding unicode names.

Example:

![Screenshot 2021-03-29 at 19 20 24](https://user-images.githubusercontent.com/1133770/112832102-6e65f780-90c7-11eb-80b2-7c67132b913f.png)
![Screenshot 2021-03-29 at 19 45 37](https://user-images.githubusercontent.com/1133770/112832118-7160e800-90c7-11eb-9e32-4146c0e51831.png)

**Comment by arcsur** [comment]
Some further testing seems to show I am getting results back for some network names, just not the ones near the top of the list

Do some of the network names have no shows associated with them?  If so why are they even in the list?

**Comment by VaslD** [comment]
To my understanding: **(A)** `/networks` returns all networks that Trakt supports; **(B)** `/shows/trending` and `shows/popular` returns shows that are associated with most user activities. You only get results when filtering if **(A)** and **(B)** have an intersection.

Meaning if the network audience is too few or localized that those viewers do not get on Trakt much, you will probably never see shows from said network reach `/shows/trending` or `shows/popular`.

**Comment by rectifyer** [comment]
This URL is loading ok for me, just using the name directly I got directly from `/networks` without any different encoding.

`https://api.trakt.tv/shows/popular?networks=AMI-télé`
