### ISSUE TITLE
Add List Items (and others) endpoint should return updatedAt timestamp of the list.

### ISSUE THREAD

**Issue by michaldrabik** [trakt/api-help#275]
As [Add List Items](https://trakt.docs.apiary.io/#reference/users/add-list-items/add-items-to-custom-list) (but also "remove" and "reorder") endpoint updates "updatedAt" timestamp of the list it has modified (itemCount as well) I believe it should return this timestamp in the response.

After modifying items I usually want to update list's updatedAt locally and that forces me to make another call to fetch list's details with latest "updatedAt".

What do you think?

Regards,
Mike

**Comment by rectifyer** [comment]
That's a great idea. How about the response changes to this:

```
{
  "added": {
    "movies": 1,
    "shows": 1,
    "seasons": 1,
    "episodes": 2,
    "people": 1
  },
  "existing": {
    "movies": 0,
    "shows": 0,
    "seasons": 0,
    "episodes": 0,
    "people": 0
  },
  "not_found": {
    "movies": [
      {
        "ids": {
          "imdb": "tt0000111"
        }
      }
    ],
    "shows": [],
    "seasons": [],
    "episodes": [],
    "people": []
  },
  "list": {
    "updated_at": "2022-04-22T17:00:54.000Z"
  }
}
```

**Comment by michaldrabik** [comment]
Looks good I think

 Item count could also be added as this is what we change here. I guess it can also be counted from responses data though.

**Comment by rectifyer** [comment]
This update will go out tomorrow and output will include `updated_at` and `item_count`. API docs updated now for review.
