### ISSUE TITLE
Exclude already collected shows from recommendations

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#28]
Hello,

Is it possible in some way to exclude already collected / watched shows from the personal recommendations ?

https://trakt.docs.apiary.io/#reference/recommendations/hide-movie/get-show-recommendations

**Comment by rectifyer** [comment]
Good idea. I'll have this available in the API later this week. Docs updated as well.

**Comment by jonathanantoine** [comment]
Thanks a lot!

**Comment by jonathanantoine** [comment]
Do we have to pass a special parameter to the APis or it's auto-magically done on your side for every requests ?

**Comment by rectifyer** [comment]
A URL parameter needs to be added, the docs have it listed.
