### ISSUE TITLE
How to get User profile images ?

### ISSUE THREAD

**Issue by Kashish-Sharma** [trakt/api-help#29]
Is there a way to get a user's profile pic and the backdrop?

**Comment by tysonkerridge** [comment]
You can get their profile pic using the Users Profile endpoint (https://trakt.docs.apiary.io/#reference/users/profile/get-user-profile) and including `?extended=full`. Unsure if backdrop is ever included in that, I guess you can find out for yourself, as the backdrop/header image is a VIP only feature which the API doesn’t have a concept of yet (for exposing VIP only information/endpoints etc. Justin’s comment about that for reference: https://github.com/trakt/api-help/issues/3#issuecomment-451324453).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kashish-Sharma** [comment]
Thanks a lot!!
