### ISSUE TITLE
Problem with oauth in Angular

### ISSUE THREAD

**Issue by ufondu88** [trakt/api-help#292]
I am in the process of creating an Angular SPA, but I have hit a roadblock when I try to implement oauth in my app. Here is my authservice:

`@Injectable({
  providedIn: 'root',
})
export class AuthService {
  clientID = '************************************';
  redirectURI = 'http://localhost:4200/home';
  options = {
    headers: new HttpHeaders({
      'Content-Type': 'application/json'
    }),
  };
  constructor(private http: HttpClient) {}

  authorizeApp() {
    return this.http.get(
      `https://trakt.tv/oauth/authorize?response_type=code&client_id=${this.clientID}&redirect_uri=${this.redirectURI}`);
  }
}`

and here is what my Trakt app settings look like 
![image](https://user-images.githubusercontent.com/41022629/120703677-3ab69d80-c47b-11eb-8d72-b05e0fc764f6.png)

but I keep getting a cors error whenever I run the authorizeApp() method in my app

`Access to XMLHttpRequest at 'https://trakt.tv/oauth/authorize?response_type=code&client_id=*****************&redirect_uri=http://localhost:4200/home' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Any help in resolving this issue would be greatly appreciated. Thank you

**Comment by rectifyer** [comment]
You should just redirect to that URL, not run it as an AJAX call.
