### ISSUE TITLE
Trakt api not available?

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#293]
A lot of my users cannot reach the Api. Is there an issue with cloud flare ?

Regards.

**Comment by rectifyer** [comment]
What’s the specific error and response you’re seeing? Anything listed in
the status page indicating an outage?

**Comment by jonathanantoine** [comment]
After 3 days it seems to be ok now.
It was not all my users and I was not impacted so I didn't have an error and respond.

Thanks anyway.
