### ISSUE TITLE
problem with show/anticpated end point with extended=full

### ISSUE THREAD

**Issue by smart4tuna** [trakt/api-help#296]
if you use  "https://api.trakt.tv/shows/anticipated?extended=full", you receive a 403 error.  This error shows up on test page "https://trakt.docs.apiary.io/#reference/shows/anticipated/get-the-most-anticipated-shows?console=1" as well as using curl.

The api docs show that you should be able to request 'extended info' using the anticipated end point.

BTW, you can receive anticpated data without supplying the api-key header as long as you remove the uri parameter 'extended'.

**Comment by rectifyer** [comment]
A 403 indicates an invalid API key, that shouldn't be related to extended info at all. Since that call is cached at Cloudflare, that is why it sometimes will "work" even with an invalid API key being sent. Ultimately, you need always need to send a valid key though.

**Comment by smart4tuna** [comment]
Thanks.  I was using client-secret.  I guess client-id  == api-key
