### ISSUE TITLE
Unable to always connect to OAuth screen

### ISSUE THREAD

**Issue by akitikkx** [trakt/api-help#304]
Hi,

There appears to be an issue conneting to the oauth/authorize screen. 

![Screenshot_20210719-121429_Chrome](https://user-images.githubusercontent.com/2282990/126145358-9788429b-8b85-48d7-a82b-6c26a8464bcf.jpg)

I am particularly concerned about the stability of the link as this might be a pain-point for my users who might not be able to connect and attribute it to the app being the issue

**Comment by rectifyer** [comment]
It’s always possible to have server hiccups, if it’s replacing a dead server for example. In general though we’ve made a lot of behind the scenes improvements since this post was made.
