### ISSUE TITLE
Lists updated_at date sometimes is set to a few minutes to the past

### ISSUE THREAD

**Issue by aohrem** [trakt/api-help#307]
Hi,

we discovered that the `"lists"` -> `"updated_at"` date from the `GET /sync/last_activities` endpoint sometimes is set to a few minutes to the past when adding a movie to a new list using the popup to add a movie to lists on the Trakt website.

We could best reproduce this behaviour by immediately adding it to another list after adding it to the first one, but sometimes adding it to one was enough.

Best regards,

Andreas

**Comment by rectifyer** [comment]
I think this was an issue with one of the servers having its time clock off. We’ve since updated this to use a new process of keeping the system clock correctly in sync.
