### ISSUE TITLE
Likes not updating in API response

### ISSUE THREAD

**Issue by Kashish-Sharma** [trakt/api-help#32]
When liking a comment via API, like updates on trakt.tv but does not update in API response immediately.

**Comment by tysonkerridge** [comment]
I’ve definitely seen similar issues in relation to adding a comment and it showing up on the website but not being returned through the API, I imagine it’s cache related, and maybe the API isn’t invalidated as often as the website. Probably need to wait on an official response for this one.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kashish-Sharma** [comment]
Thanks !!

**Comment by rectifyer** [comment]
Yes, this is due to caching. We use Cloudflare for all caching and the counts are cached for up to 8 hours on some methods. Our plan over there doesn't allow us to invalidate the cache as much as we'd like to.

**Comment by Kashish-Sharma** [comment]
So are you guys using a private API in trakt.tv as it updates instantly.

**Comment by rectifyer** [comment]
@Kashish-Sharma the Trakt website doesn't use the same API
