### ISSUE TITLE
Show with numeric Slug causes endpoint conflicts

### ISSUE THREAD

**Issue by tysonkerridge** [trakt/api-help#33]
I’ve been alerted to an issue where interactions with the show named [“24”](https://trakt.tv/shows/24) are causing those actions to be applied to the show named [“Presidio Med”](https://trakt.tv/shows/presidio-med) due to the usage of the Trakt Slug instead of the Trakt ID for some endpoints (for reasons I haven’t looked into again just yet, for a lot of them I use the Trakt ID). 

For example, grabbing the first episode using 
`https://api.trakt.tv/shows/24/seasons/1/episodes/1` returns the Presido Med episode, due to its Trakt ID being 24, even though it was intended to be the episode of the show “24” who’s slug is “24”.

I’m wondering whether this is intended or if maybe it’s an unconsidered edge case bug that needs to be addressed?

Either way I will look further into using the Trakt ID instead of the slug but figured it’s still an issue otherwise considering the end points take both slug and ID, and maybe slugs shouldn’t ever be only numeric (eg. “24”’s slug should maybe include the year between a dash such as “24-2001”. Similar to [The Flash (2014)](https://trakt.tv/shows/the-flash-2014) which is “the-flash-2014”, even though I assume it’s only like that because there was already [The Flash (1990)](https://trakt.tv/shows/the-flash) which had “the-flash”).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kashish-Sharma** [comment]
Is there any official method of creating slugs, like adding the first air year at the end of the show name etc, and similarly for movies?

**Comment by tysonkerridge** [comment]
Nah, you shouldn’t need to create them, they’re returned in all the normal objects alongside their other IDs. It’s just once you get an object, you can use either the Trakt ID, Trakt Slug or IMDb ID for a bunch of endpoints (and it matches whatever it finds first etc). Hence the conflict when the slug is numeric only. As “24” will be matched as a Trakt ID. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rectifyer** [comment]
The official recommendation is to use Trakt IDs in the URLs for this reason. We also support Trakt slugs and IMDB IDs, but those aren't guaranteed to work like the Trakt ID will.

**Comment by tysonkerridge** [comment]
Awesome, no worries. Just figured I’d check, in case there was some specific way to specify which ID is being sent etc. I’ll go ahead and make sure I’m using the Trakt ID unless absolutely necessary. Thanks! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jemus42** [comment]
Thank you for pointing that out!
I've been wondering for a while why I get derpy results in some cases for my webapp (which I'm in the process of completely rewriting anyway, now knowing what to do better)
