### ISSUE TITLE
Get Likes output

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#332]
Hi, 

Am I reading the documentation wrong or maybe not looking at the right endpoint but `GET https://api.trakt.tv/users/id/likes/type` doesn't give me full comments objects - only the comment, not the media associated. Would it be possible to get a list of liked comments for a user with full comments object?

Thanks!

**Comment by rectifyer** [comment]
I added an optional parameter to get the comment media objects. This will go live next week, docs updated.

https://trakt.docs.apiary.io/#reference/users/likes/get-likes
