### ISSUE TITLE
“Create custom list” API documentation missing

### ISSUE THREAD

**Issue by tysonkerridge** [trakt/api-help#34]
Looks like the formatting is messed up somewhere which caused the Create documentation to disappear.

I think it’s somehow been mixed up into the “Reorder a user’s lists” documentation as it appears to be under the example response in the reorder section https://trakt.docs.apiary.io/#reference/users/lists/reorder-a-user's-lists

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rectifyer** [comment]
Good catch, thanks! Docs are fixed now.
