### ISSUE TITLE
API Request '/sync/history/remove' always fails with a 504 error

### ISSUE THREAD

**Issue by javikr** [trakt/api-help#343]
Hello,
Please advice, the API request 'https://api.trakt.tv/sync/history/remove' is failing returning a html file with a 504 error.

api.trakt.tv | 504: Gateway time-out

**Comment by javikr** [comment]
Sorry,
Now it's working as expected. Anyway, here I paste the request that were failing with a 504 error:

```
POST /sync/history/remove? HTTP/1.1
Host: api.trakt.tv
Content-Type: application/json
Content-Length: 74
trakt-api-version: 2
Accept: */*
Connection: keep-alive
trakt-api-key: xxxx
Authorization: Bearer xxx
Accept-Language: en;q=1.0, es-US;q=0.9
Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8

{
  "movies": [
    {
      "ids": {
        "tmdb": 414906
      }
    }
  ],
  "seasons": [],
  "episodes": [],
  "shows": []
}
```

**Comment by rectifyer** [comment]
Very strange with only removing a single media item like that. A timeout likely means there was a temporary server issue with things getting backed up and your call failing because of that.
