### ISSUE TITLE
[BUG] Movies and TV Shows not getting marked as watched in Trakt; Trakt rating pop-up not showing up

### ISSUE THREAD

**Issue by AakashC2020** [trakt/api-help#345]
Hi,

I've been using the Trakt addon for Kodi since a long time. I'm facing some issues with it and contacted the developer, but he asked me to contact Trakt support instead. Here's the ticket link for your reference:

https://github.com/trakt/script.trakt/issues/598

Here's my latest Kodi log:

https://paste.kodi.tv/poyehecife

Description of the issues:

Recently I've noticed that Movies and TV Shows have stopped getting marked as watched in Trakt after the playback ends. The Trakt Rating pop-up also doesn't show up after the video ends. I've been using it to scrobble local files, as well as for strm files in other 3rd party addons. The scrobbling starts fine. However, it appears that Trakt is not receiving any Stop command once the playback ends. I received a couple of Trakt errors, one of them is error 429 (Rate limit exceeded). It seems that Trakt is limiting the API calls from Kodi.

The issue mainly happens when a video is played from start to end without stopping, rewinding, or forwarding it in the middle. Smaller length videos having less than 10 mins of duration are sometimes getting marked as watched and sometimes doesn't. However, videos of runtime more than 10 mins are usually not getting marked as watched at all. I checked on multiple Trakt accounts, but that didn't work too.

Sometimes the video gets marked as watched in Trakt after 15 mins or so, once the playback ends.

I've tried reauthorizing Trakt, setting startup delay and scrobble start delay as 3, but those didn't work too. I'm also receiving errors like "Connection reset by peer", "Read timed out", etc. However, nothing is wrong with my internet connection as well. I'm now out of all ideas about how to resolve these issues. Could you please advise?

Environment:

OS: Android 11
Kodi Version 19.4
Device: Nvidia Shield TV Pro

I'm really hoping that you can help. Thanks in advance!

Thanks and Regards,
ShibajiCh.

**Comment by rectifyer** [comment]
This seems to be the error:

```
2022-05-04 12:48:31.896 T:32742   FATAL <general>: [script.trakt] resources.lib.service: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'ReadTimeout'>
Error Contents: (ReadTimeoutError("HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=24)"),)
```

Other plugins are also getting read timeouts, so it seems to be a problem with your connection or maybe you're using a VPN? This error is on your client side, before it actually talks to the Trakt API so I don't know how I can help troubleshoot that.

**Comment by ShibajiCh** [comment]
Hi @rectifyer,

Thanks for your feedback!
I'm not using a VPN. So what might cause this error? Any suggestions?

Thanks and Regards,
ShibajiCh.

**Comment by rectifyer** [comment]
What region are you accessing Trakt from? Only thing I can think of is Cloudflare is restricting access if it detects any security issues.

**Comment by ShibajiCh** [comment]
Hi @rectifyer,

I'm accessing Trakt from Hyderabad, India region.

Thanks and Regards,
ShibajiCh.

**Comment by rectifyer** [comment]
I sent you an email, but I'd need to get your IP and see if Cloudfare is blocking it for some reason. I'm guessing Cloudflare is detecting a security issue and blocking your access. Does the Trakt website work ok?

**Comment by ShibajiCh** [comment]
Hi @rectifyer,

I've already replied to your earlier comment here:
https://support.trakt.tv/support/tickets/13034

I'm again writing the same here:
My ISP provided IP address is: 10.119.210.37
I've set a local static IP address for my Nvidia Shield TV Pro through my router's DHCP server, which is: 192.168.0.176
The Trakt website works perfectly fine for me.
Please check and advise.

Thanks and Regards,
ShibajiCh.

**Comment by rectifyer** [comment]
I didn't find anything in Cloudflare with your IP, so it doesn't appear to be blocking it there. I don't really know what the issue could be, but the error still seems to indicate there is a networking problem before it's even reaching Trakt.

**Comment by ShibajiCh** [comment]
Hi @rectifyer,

Thanks for your feedback!
So is there nothing that can be regarding my issue? Please suggest.

Thanks and Regards,
ShibajiCh.

**Comment by rectifyer** [comment]
I don't have any ideas unfortunately.

**Comment by darkman7hr** [comment]
having same issue for a long time now.. it's very inconvenient
