### ISSUE TITLE
tvrage IDs still included but tvrage is dead

### ISSUE THREAD

**Issue by jemus42** [trakt/api-help#35]
Would it be appropriate to remove `tvrage` IDs (which are 0 for an awful lot of items anyway)?

The only reason to not remove them appears to be backwards compatibility with apps that expect them to be there - but since the site is dead, they're not useful anyways, are they?

**Comment by rectifyer** [comment]
Yeah, we can’t remove them since it would be a breaking change. It is possible apps don’t have the correct error checking if we were to remove the field altogether. In v3 of the api, we’d be able to remove it.

**Comment by jemus42** [comment]
Ah, makes sense. Thanks for the clarification!
