### ISSUE TITLE
Documentation for people/crew incomplete

### ISSUE THREAD

**Issue by jemus42** [trakt/api-help#36]
Documentation on https://trakt.docs.apiary.io/#reference/shows/watched-progress/get-all-people-for-a-show lists the following objects for people/crew: `production`, `art`, `crew`, `costume & make-up`, `directing`, `writing`, `sound`, and `camera`.

The response for `https://api.trakt.tv/shows/futurama/people` additionally includes `visual effects`.

Just thought I'd mention that for completion's sake.

**Comment by rectifyer** [comment]
Thanks, I updated the docs.
