### ISSUE TITLE
500 error on `comments/recent/all`

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#364]
Hi,

This call is currently giving 500 errors (and I think it's been doing that for at least 2 days): `https://api.trakt.tv/comments/recent/all/all?extended=full&limit=50&page=1 https://api.trakt.tv/comments/recent/all/all?extended=full&limit=50&page=1`

Here is the latest response I got :

HTTP/1.1 500 Internal Server Error
Date: Sat, 10 Sep 2022 06:25:55 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
x-pagination-page: 1
x-pagination-limit: 50
expires: Sat, 10 Sep 2022 07:25:55 GMT
x-pagination-page-count: 8242
x-pagination-item-count: 412073
Cache-Control: public, no-cache, no-store
x-error-message: Internal server error. Please open a support issue and include your full API request and response, including all headers.
vary: Accept-Encoding
x-ratelimit: {"name":"UNAUTHED_API_GET_LIMIT","period":300,"limit":1000,"remaining":999,"until":"2022-09-10T06:30:00Z"}
set-cookie: _traktsession=OHDd58Od%2B32v9O9%2F78CMjv4xuRCBhc5bY2KIcevRMZ1PMwGrPHvvjOgaGP0nVaq1c7v22ro5h9acB9RXd0CwQ8wYDsW7X7ooUSzvfUV8oqJCpH%2FfMuzygykRr%2B31%2F4vvNEWf2JV9XY1bwndjlB5jpp1pUHF%2FwevbFSZrVwAhwI2hjtqNcQ%3D%3D--RraaeEHv7fx7bZxg--ybcgY7d9lqCK2IX1Z%2FDkWQ%3D%3D; path=/; HttpOnly
x-request-id: 328a9d9c-eaaf-4f9e-937c-392c9575ccf5
x-runtime: 3.300413
CF-Cache-Status: BYPASS
Server: cloudflare
CF-RAY: 748616be2c492e3e-BRU

Maybe this has nothing to do this that but some (2) users reported an issue with the login page opened from Rippple. They couldn't log in for some reason.

I checked the status page but login and comments seem to not be monitored.

Cheers,

Kevin

**Comment by rectifyer** [comment]
I believe I found a fix for this and I'll release it tomorrow.
