### ISSUE TITLE
Endpoint sync/watchlist/remove is down.

### ISSUE THREAD

**Issue by michaldrabik** [trakt/api-help#365]
Hi.
The API call for `https://api.trakt.tv/sync/watchlist/remove` seems not to be working correctly right now.

![image](https://user-images.githubusercontent.com/11537045/189612358-4c5833d0-7420-4f70-878f-ef24a45f627c.png)

Always times out with no results.

**Comment by rectifyer** [comment]
I'm not able to reproduce any issues. Perhaps this was a temporary server issue?

**Comment by michaldrabik** [comment]
It does seem to be working again. Closing. Thanks.
