### ISSUE TITLE
OAuth PKCE flow

### ISSUE THREAD

**Issue by Axort** [trakt/api-help#367]
Is there a plan to implement PKCE flow for oauth?

**Comment by rectifyer** [comment]
I enabled PKCE on https://staging.trakt.tv, please try it out there and let me know if it is working as expected.

**Comment by Axort** [comment]
Sorry, went silent for a while. I'll look into it as soon as I can, do you have some API documentation for staging?

**Comment by rectifyer** [comment]
Support for PKCE was added to the live API several months ago, just closing up this issue.

**Comment by kdb13** [comment]
Can anyone please tell where in the API docs the PKCE flow is mentioned? I am developing a CLI and would like to use this flow.

**Comment by kdb13** [comment]
> Can anyone please tell where in the API docs the PKCE flow is mentioned? I am developing a CLI and would like to use this flow.

Just found that using the `code_challenge` and `code_verifier` params instead of `client_secret` works with the `/oauth/authorize` endpoint. But I think, it should still be mentioned in the API docs with a dedicated section under **Authentication** for PKCE.

**Comment by kdb13** [comment]
While PKCE works with the normal OAuth flow, I would like to know if it works with the **Devices** flow as well, which generates device codes and then asks for the access token.

**Comment by kdb13** [comment]
> While PKCE works with the normal OAuth flow, I would like to know if it works with the **Devices** flow as well, which generates device codes and then asks for the access token.

Never mind. PKCE works with device flow as well.
