### ISSUE TITLE
Auth issues

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#368]
Hi @rectifyer,

I've had a user complaining about an authentication issue (thread): https://twitter.com/drthunder/status/1577683864998346755

When I tested, I thought the login took way longer than usual (see my answer to the tweet).

Today, I'm testing on a new device/simulator and the login is giving me a 502 Bad Gateway (Cloudflare Ray ID: 75665cbcbae5b9b9) 
![Simulator Screen Shot - iPad mini (6th generation) - 2022-10-07 at 13 41 07](https://user-images.githubusercontent.com/146673/194545620-5b69f452-4d61-4ec0-b1c4-5b694899080f.png)

Seems like a stability issue. Can be only me... just would like to be sure.

Cheers,

Kevin

**Comment by rectifyer** [comment]
The database was under heavy load the last 3-4 days, which likely caused the 502 errors. It was making things slow across the website and API.

Redgarding the tweet, I'm not sure what the attachShadow.js file is, that isn't a file we have in the website. It could be from a 3rd party script (recaptcha for example) or from a browser plugin.
