### ISSUE TITLE
likes/comments API returns object without the comment

### ISSUE THREAD

**Issue by minas1** [trakt/api-help#369]
The [likes/comments](https://trakt.docs.apiary.io/#reference/users/likes/get-likes) API is supposed to return objects that look like this:
```
{
    "liked_at": "...",
    "type": "comment",
    "comment": {...}
}
```

# The problem
However I see that there is one object that does not have the `comment` object:
```
{
    "liked_at": "2019-07-21T21:10:19.000Z",
    "type": "comment"
}
```

# How to reproduce
1. Execute `GET https://api.trakt.tv/users/minas1/likes/comments?page=5`.
2. There is one object that does not have the `comment` object in it.

# Expected result
A possible cause might be that the comment was deleted.
If this is the case, the API should automatically delete likes for deleted comments/movies/etc or not return them at all as part of the API call.

**Comment by minas1** [comment]
Any news on this?

**Comment by rectifyer** [comment]
Looks like the comment was deleted. I'll have a fix out so that likes on deleted comments no longer show up. Fix will be out tomorrow.
