### ISSUE TITLE
Does shows/updates return shows where seasons / episodes changed or only the show object?

### ISSUE THREAD

**Issue by MaxHasADHD** [trakt/api-help#37]
I currently fetch all show, seasons, and episodes every 24 hours that are local in my app. I'm looking to improve that by using the show/updates API, does this work when an individual episode or season is updated or just the show object itself?

**Comment by tysonkerridge** [comment]
I haven’t used it extensively myself so I could be wrong, but my understanding is that it works when an episode or season is updated, yeah. I feel like if it didn’t, it might not be worth using. I think Justin mentioned it would in https://github.com/trakt/api-help/issues/17#issuecomment-457409322

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jonathanantoine** [comment]
Hello,

It works that way and you could also uses the etag http header to download less too.

**Comment by MaxHasADHD** [comment]
Thanks ya'll, I'll look into replacing my sync with the `shows/updates` endpoint. Is is also better to only pull minimal info from that end point, and then fetch full show info for any matching shows? or pull full info immediately?

**Comment by tysonkerridge** [comment]
I imagine pulling minimal info from the `shows/updates` endpoint and then grabbing full info for those you need (that have changed), as I'm pretty certain the `shows/updates` endpoint includes info for every single show that changed, not just ones the user might care about. And as far as I know, there's no good way to get info from only a specific time period, as mentioned in https://github.com/trakt/api-help/issues/17#issuecomment-457437312, and instead it appears to send info from the beginning of the day you send etc.

**Comment by MaxHasADHD** [comment]
It seems to make sense that on a sync, I should refresh the account token if needed, check sync activities, if `episodes.watched_at` and `lists.updatedAt` are both newer than the last synced date for my app, then I don't need to use `shows/updates` since I'll get full info from those APIs, but if they are older then I don't need to fetch history or watchlist, and I use `shows/updates` to get minimal info, then matching shows to the local data I fetch full info for.

**Comment by MaxHasADHD** [comment]
What's a good way of determining if a) a user removed all progress of a show and is not on any of their lists, and b) Show / episode / season was removed from Trakt.tv API? I can't compare all local Ids to all remote Ids anymore because I only fetch one endpoint at a time, and for show progress I'm finding it difficult. For lists I can still compare what's on the list vs what Trakt says is on the list now.

**Comment by tysonkerridge** [comment]
The `/sync/watched/shows` endpoint is likely your friend there, as I imagine it won't return a show (or would return one with 0 plays etc, I forget how it works without checking) if the user has removed all plays - therefore there would no longer be any progress for that show. 

For something being removed, I'm not sure. It might have to be just checked the next time the user tries to view it and if you get a 404 status or something which says it's no longer there, you could remove it locally.

**Comment by rectifyer** [comment]
> I currently fetch all show, seasons, and episodes every 24 hours that are local in my app. I'm looking to improve that by using the show/updates API, does this work when an individual episode or season is updated or just the show object itself?

Just wanted to confirm the show is updated even when individual episodes or seasons are updated. It bubbles up to the top level show.
