### ISSUE TITLE
Series status descriptions

### ISSUE THREAD

**Issue by MaxHasADHD** [trakt/api-help#370]
I noticed that more series status' have appeared such as `pilot` and `continuing`, is there documentation or can documentation be added to what the differences are with each status from each other? I kind of understand `pilot` if it is referring to shows that were not picked up so there is a single Pilot episode for a cancelled series. `returning series` and `continuing` seem the same though, and `planned` / `upcoming`.

**Comment by rectifyer** [comment]
We get the status straight from TMDB, I think you're right about the `pilot` being a single episode and the series ultimately not picked up for a full season. I think `continuing` is a TVDB status, TMDB uses `returning series`.

**Comment by henrikfroehling** [comment]
Since the data comes from TMDB you can lookup the guidelines here: https://www.themoviedb.org/bible

**Comment by rectifyer** [comment]
Good call, the specific guidelines are here:
https://www.themoviedb.org/bible/tv#59f7403f9251416e7100002b
