### ISSUE TITLE
Seems like the check in is using the TV show runtime instead of the specific episode runtime

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#371]
Hi,

For a specific feature in my app I use the episode specific runtime to calculate the end of a checkin. Doing this, I found out that my checkin was 60 minutes long (the TV show runtime) while my own implementation was 72 minutes long (the episode runtime).

Is the check in using the TV show runtime or is it a bug? Would it be possible to use the episode runtime instead oft he show runtime?

Cheers,

Kevin

**Comment by rectifyer** [comment]
What specific item did this? I checked and it's using the episode runtime if we have it, but it will fall back to using the show runtime if we don't. I can check the specific item to confirm we have a runtime and also see if it was recently added to TMDB.

**Comment by kevincador** [comment]
I just tested now with The Lord of the Rings: The Rings of Power latest episode (but I found out about the issue with a previous episode). The episode's runtime is 72 minutes, the show is referenced with a runtime of 60 minutes. If you look at start and expires at time, it's just 60 minutes.

Response Body (https://api.trakt.tv/users/me/watching?extended=full): 
`{"expires_at":"2022-10-16T10:30:33.000Z","started_at":"2022-10-16T09:30:33.000Z","action":"checkin","type":"episode","episode":{"season":1,"number":8,"title":"Alloyed","ids":{"trakt":6575487,"tvdb":8954351,"imdb":"tt11609048","tmdb":3894856,"tvrage":null},"number_abs":null,"overview":"New alliances are forged.","rating":7.83307,"votes":1270,"comment_count":25,"first_aired":"2022-10-14T04:00:00.000Z","updated_at":"2022-10-16T09:21:27.000Z","available_translations":["cs","de","el","en","es","fr","he","hu","it","ko","nl","pl","pt","sv","th","tr","zh"],"runtime":72},"show":{"title":"The Lord of the Rings: The Rings of Power","year":2022,"ids":{"trakt":150900,"slug":"the-lord-of-the-rings-the-rings-of-power","tvdb":367506,"imdb":"tt7631058","tmdb":84773,"tvrage":null},"overview":"Beginning in a time of relative peace, we follow an ensemble cast of characters as they confront the re-emergence of evil to Middle-earth. From the darkest depths of the Misty Mountains, to the majestic forests of Lindon, to the breathtaking island kingdom of Númenor, to the furthest reaches of the map, these kingdoms and characters will carve out legacies that live on long after they are gone.","first_aired":"2022-09-02T01:00:00.000Z","airs":{"day":"Friday","time":"00:00","timezone":"America/New_York"},"runtime":60,"certification":"TV-14","country":"us","trailer":"https://youtube.com/watch?v=x8UAUAuKNcU","homepage":"https://www.amazon.com/dp/B09QHC2LZM","status":"returning series","rating":7.31711,"votes":2343,"comment_count":79,"network":"Amazon","updated_at":"2022-10-16T08:35:08.000Z","language":"en","available_translations":["ar","bg","ca","cs","da","de","el","en","es","fa","fr","he","hr","hu","id","it","ja","ka","kn","ko","lt","my","nl","pl","pt","ro","ru","sl","sr","sv","th","tr","uk","vi","zh"],"genres":["fantasy","science-fiction","action","adventure","drama"],"aired_episodes":8}}`

**Comment by rectifyer** [comment]
I think I found the issue. If a scrobble/checkin was sent using the episode info only like:

```json
{
  "episode": {
    "ids": {
      "trakt": 1234
    }
  }
}
```

That lookup is cached and it was too aggressive. It still needs to be cached, but I reduce it a lot so there will only be a 1hr cache before the episode is updated with a changed runtime. I'll push out this fix tomorrow and it should just start working better.
