### ISSUE TITLE
IMDb Top Rated Lists are broken

### ISSUE THREAD

**Issue by sereisoglu** [trakt/api-help#374]
Hi. The IMDb Top Rated Lists seem to be broken.

https://www.imdb.com/chart/top/
https://trakt.tv/users/justin/lists/imdb-top-rated-movies?sort=rank,asc

https://www.imdb.com/chart/toptv/
https://trakt.tv/users/justin/lists/imdb-top-rated-tv-shows?sort=rank,asc

**Comment by rectifyer** [comment]
Fix going out now, so lists should return to normal after they update tonight.
