### ISSUE TITLE
Popular endpoint becoming stagnant 

### ISSUE THREAD

**Issue by nixgates** [trakt/api-help#38]
I would love to be able to filter this endpoint for ratings submitted in the past x months/years. Currently we able to filter this by year title was released and that's about all we can do to get this list to provide titles a little more current.

Being able to filter the most popular titles with the most ratings in the past 12 months would hopefully allow this endpoint to be a little bit more relevant.

If there's an endpoint/filter I'm missing that might help me out, please let me know!

**Comment by jemus42** [comment]
Would the `trending` endpoint maybe be more relevant? It's still not quite what you're describing, but if you're looking for things along the lines of "currently relevant" then I think that might be a better option maybe?

**Comment by rectifyer** [comment]
@nixgates we don't store historical popularity info to do that type of segmenting. It might work to use the `years` filter (https://trakt.docs.apiary.io/#introduction/filters) an only go back 1 or 2 years. Recently rated items are most likely recently released as well.

**Comment by nixgates** [comment]
I opted to adjust my side so users can benefit from filtering the most popular section by recent years, this seems to be a lot closer to what I was looking for. 

Thank you for your help guys.
