### ISSUE TITLE
Documentation: Wrong URL and title for "People - Updated IDs"

### ISSUE THREAD

**Issue by henrikfroehling** [trakt/api-help#381]
The documentation for https://trakt.docs.apiary.io/#reference/people/updated-ids/get-recently-updated-movie-trakt-ids has wrong title and URL.

![PeopleUpdatedIDs](https://user-images.githubusercontent.com/3494788/201738467-93cde6e6-839a-4927-b094-3c762ba940b2.png)

**Comment by rectifyer** [comment]
Fixed, thanks!
