### ISSUE TITLE
Getting http error code 503 on any request

### ISSUE THREAD

**Issue by bubbleguuum** [trakt/api-help#383]
My Android app which had integrated Trakt for a few years now is getting 503 errors on any request that uses a proper and fresh access token.
Here's a log, invoking /users/settings just after getting a refreshed access_token that I verified is properly passed to "Bearer":

 ```
 I   39:59.023  --> GET https://api.trakt.tv/users/settings h2
                         I   39:59.023  Host: api.trakt.tv
                         I   39:59.023  Connection: Keep-Alive
                         I   39:59.023  User-Agent: okhttp/4.10.0
                         I   39:59.023  Content-Type: application/json
                         I   39:59.024  Accept-Encoding: identity
                         I   39:59.024  trakt-api-key: <REDACTED>
                         I   39:59.024  trakt-api-version: 2
                         I   39:59.024  Authorization: Bearer <REDACTED>
                         I   39:59.024  --> END GET
                         I   39:59.143  <-- 503 https://api.trakt.tv/users/settings (119ms)

```

Same thing happens if I execute the same request via the web API test interface.

I do not know when exactly this happened,  and it could have been quite a while since Trakt is a very optional feature of my app and rarely used and a user just informed me about it.

**Comment by diegosamanez** [comment]
Apparently the server is down or something, for all the requests I make it returns 503

**Comment by tysonkerridge** [comment]
https://github.com/trakt/api-help/discussions/385#discussioncomment-4443842

**Comment by bubbleguuum** [comment]
Indeed. I will close that issue.
