### ISSUE TITLE
500 error for second check-in when a check in is already in progress and near the end

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#387]
Hi,

I've seen this issue for a while now. When a check-in is in progress but close to the end, another check-in was (in the past) working well -> the old check-in was considered successful and finished and the new check-in started. Now, if you try to check-in and another check-in is close to the end, it seems to fail with a 500 error and the check-in is not really started (/watching not giving a check-in) but the episode is marked as watched in /history.

Note: if the current check-in is not close to the end, the 409 is triggered which is 100% what is expected. Only issue is when the second check-in is done close to the end of the first one.

FYI: I've been able to reproduce the issue with the official trakt app (see attached screenshot).
![image](https://user-images.githubusercontent.com/146673/210176710-1e26acca-c75a-4bfe-8bdb-773c5be49266.png)

To reproduce:
- make a first check-in (a 5 minute episode to not wait for too long 😝)
- make a second check-in close to the end (80%)
- 500 error + first check-in is stoped + second check-in is not started + second check-in is added to history
Expected: 201 + first check-in is stoped + second check-in is started

Here is a sample response I managed to get while debugging:

```
Response: <NSHTTPURLResponse: 0x60000393b6c0> { URL: https://api.trakt.tv/checkin } { Status Code: 500, Headers {
    "Cache-Control" =     (
        "no-cache, no-store"
    );
    "Content-Type" =     (
        "application/json"
    );
    Date =     (
        "Sun, 01 Jan 2023 15:38:40 GMT"
    );
    Server =     (
        cloudflare
    );
    "Set-Cookie" =     (
        "_traktsession=HsoCRZu0iVI2sBIgcVchDZNpbkN5FeqG%2Brx07dGqjzKAcoHp2pGuMIERey5KPHEhOoM0YUWToQkCffPAamcYrhAbyBZavDsOiWraN0LTTbglJTfU%2Bz16G5mcqtv%2F%2B0tZsKv61ygr0H5z2dMm%2F7BBtFVRtQRnOEycBFT%2Bkupip4H5t4M5wQ%3D%3D--SXBLl0shByRdaHK5--xs%2BB1QgUc5wOxyhOZbA%2FaA%3D%3D; path=/; HttpOnly"
    );
    Vary =     (
        "Accept-Encoding"
    );
    "cf-cache-status" =     (
        DYNAMIC
    );
    "cf-ray" =     (
        "782c57df6fa1b9ae-BRU"
    );
    "referrer-policy" =     (
        "strict-origin-when-cross-origin"
    );
    "x-content-type-options" =     (
        nosniff
    );
    "x-download-options" =     (
        noopen
    );
    "x-error-message" =     (
        "Internal server error. Please open a support issue and include your full API request and response, including all headers."
    );
    "x-frame-options" =     (
        SAMEORIGIN
    );
    "x-permitted-cross-domain-policies" =     (
        none
    );
    "x-ratelimit" =     (
        "{\"name\":\"AUTHED_API_POST_LIMIT\",\"period\":1,\"limit\":1,\"remaining\":0,\"until\":\"2023-01-01T15:38:40Z\"}"
    );
    "x-request-id" =     (
        "231cd93b-dc28-4ba2-ad9b-298c6ed0207c"
    );
    "x-runtime" =     (
        "0.171258"
    );
    "x-xss-protection" =     (
        "1; mode=block"
    );
} }
```

**Comment by rectifyer** [comment]
I'll have a fix for this tomorrow.
