### ISSUE TITLE
Saved Filters issue when watchnow = favorites

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#388]
Hi, 

I'm looking at implementing Saved Filters in my app. When I check the Saved Filter when I have set it to favorites for the watch now filter on the website, I get this search for instance:
`https://api.trakt.tv/movies/trending?extended=full&imdb_ratings=7.5-10.0&limit=50&metascores=75-100&page=1&query=&ratings=75-100&rt_meters=75-100&streaming_country=be&tmdb_ratings=7.5-10.0&watchnow=favorites&years=2019-2027`

The issue is that I get no result at all because the "favorites" doesn't seem to be translated by my favorites via the API call.

Would it be possible to make that work either by sending the right list of favorites when getting the saved filters? Or by translating the "favorites" keyword int he request?

Thanks!

Kevin

**Comment by rectifyer** [comment]
Nice bug find. I'll do the first way and replace `favorites` with the actual services. Those methods are heavily cached and don't know what user is calling them, so the actual service slugs in the URL will ensure the correct info is returned. Update will be out tomorrow.
