### ISSUE TITLE
Api rate limit

### ISSUE THREAD

**Issue by RamiJ3mli** [trakt/api-help#39]
What is Trakt api's usage rate limit?
Such an important information is nowhere to be found in the docs.
Any help is greatly appreciated!

**Comment by tysonkerridge** [comment]
Unless something has changed recently, it's been mentioned previously that there's currently no enforced API limiting, however it's strongly recommended to be a "good citizen" and cache what you can on your end wherever possible etc. I think it was recommended that you could likely use batches of calls (eg. of 50) if you've having to make a lot at once for whatever reason, and use the Staging API to test that also if you're worried, though it's not running on the same hardware etc.

For many calls in regards to user sync details, there's generally a way to check if there would even be any changes to information from the endpoint via checking the user's last activities first.
