### ISSUE TITLE
Issue with "Link" list

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#405]
Hi @rectifyer,

I just found out about the "Link" privacy setting for custom lists and the `share_link` property while working on supporting Notes in Rippple. I find that really cool so I started working on supporting that too 😊.

While testing, I found out that the current or older versions of Rippple will have trouble parsing the list of custom lists because the accepted values for the privacy didn't take into account the new "Link". Just a heads up as I think this could lead to some issues in apps depending on the implementation.

Another issue is I get your "Link" list when calling the `/users/justin/lists` endpoint. Same on the website:
<img width="761" alt="Screenshot 2023-05-26 at 22 12 58" src="https://github.com/trakt/api-help/assets/146673/2c712a6f-2327-4503-9836-77156242084b">

That shouldn't be the case, right? I get a 404 when I try to open it but it shouldn't be returned, or should I handle that case myself?

Cheers,

Kevin

**Comment by rectifyer** [comment]
Good find, I'll have that bug fixed in an update this week!

I also wondered about adding a new privacy option, but I haven't heard it breaking any apps until your post. I initially thought of keeping it `private` + a `share_link` but decided that wasn't clear enough.

**Comment by kevincador** [comment]
Thanks!

Just to give a bit of context, I'm parsing some info into an enum (swift) that can take only the values I set. If I was just parsing that as a string I wouldn't have that issue but I went for a stronger typing here.

I link the idea of a `private` list with an optional `share_link` that you could toggle (on/off).

And I'm just thinking right now: is there a way for third party apps to fetch the list based on the `share_link` id?

**Comment by tysonkerridge** [comment]
I know it doesn't help for old versions but I try to avoid parsing values directly into enums (and avoid trusting APIs won't change, where possible) for this reason. I've tried a few solutions over the years and I think something like this is probably the best I've been able to create and reuse. Would love a way to reduce the boiler plate.

```swift
// Example usage
class ExampleComponent {
    
    func title(value: ListPrivacy) -> String {
        switch value.known {
        case .private:
            return "Private"
        case .friends:
            return "Friends"
        case .public:
            return "Public"
        //case .link:
        //    return "Link"
        case nil:
            return "Unknown"
        }
    }
    
}

struct ExampleList: Codable {
    let id: Int
    let privacy: ListPrivacy?
}

public struct ListPrivacy: Codable, RawRepresentable {
    
    static var `default`: ListPrivacy { .init(known: .public) }
    
    public let rawValue: String
    public let known: Known?
    
    public enum Known: String, CaseIterable {
        case `private`
        case `public`
        case friends
        // Adding a new value should be as simple as adding it here
        //case link
    }
    
    
    // MARK: Boiler plate (Constant)
    
    private init(rawValue: String, known: Known?) {
        self.rawValue = rawValue
        self.known = known
    }
    
    public init(known: Known) {
        self.init(rawValue: known.rawValue, known: known)
    }
    
    public init(rawValue: String) {
        self.init(rawValue: rawValue, known: Known(rawValue: rawValue))
    }
    
    public init(from decoder: Decoder) throws {
        let rawValue = try decoder.singleValueContainer().decode(String.self)
        self.init(rawValue: rawValue)
    }
    
    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        try container.encode(rawValue)
    }
    
}

```

**Comment by kevincador** [comment]
Thanks! 

I was thinking about something like that but I fear it could lead to other kind of issues since I'm treating the list differently based on the privacy (like allow sharing or not). I'd need to treat the unknown type in a way without knowing what it is.

My next idea was to see if I can have a specific implementation of Codable that would not parse but not break the unknown types and just go over them. 

I'll keep you posted when I land on something I like. I think I have a bit more than 5 enum like that that I would like to future-proof while avoiding the boilerplate.

**Comment by tysonkerridge** [comment]
Yeah I generally just choose a most-reasonable default for unknowns, such as disabling sharing if it's unknown or even showing an error empty state of some sort but yeah let me know if you find an alternate solution.
