### ISSUE TITLE
Recommended/Favorited endpoint is returning 204 without data

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#409]
Hi @rectifyer ,

Currently the old recommended and newer favorited endpoints are returning 204 without data.
Tested and failing on Rippple and Trakt official app. The website seems to be okay.

Kevin

**Comment by rectifyer** [comment]
Which specific endpoint? Just want to make sure I'm looking in the correct place.

**Comment by kevincador** [comment]
I'm seeing this with `https://api.trakt.tv/shows/recommended/weekly` or `https://api.trakt.tv/movies/favorited/all`.
I have some saved filters like this and the official trakt app is also showing a 204 error code for them.
I can send you the traces if needed (maybe linked to my account only).

**Comment by rectifyer** [comment]
Ugh, found the bug and fixed is deployed. It might take a few hours since 204 is a valid response and cached at Cloudflare. Both the `favorited` and `recommended` will both work and are just aliases of each other.
