### ISSUE TITLE
Images URL

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#41]
Hello, 

I know that you no more expose your own image urls. Would it possible technically and legally to returns other systems (tmdb or tvdb for instance) original urls?

That would help a lot the app builder we are 😁

Thanks!

**Comment by rectifyer** [comment]
We don't store the original URLs so we don't have that info to pass along. Even if we did, I don't think we'd pass on direct links to other services since we don't want apps hotlinking directly to images like that.

**Comment by rectifyer** [comment]
I wrote this article a while ago, but it still should be helpful for app developers looking to pull images from external sources.

https://apiblog.trakt.tv/how-to-find-the-best-images-516045bcc3b6

**Comment by jonathanantoine** [comment]
Thanks for answering. I am aware of this very helpful article (thanks a lot for it!). Some Api like tmdb don't mind if we hotlink their images but limit the api rate to determine the url to something very low so having this info would be very nice!

**Comment by rectifyer** [comment]
Even if they allow hotlinking, I still recommend caching the images on our own if possible since that is more reliable and you have more control. We don't have any plans to store and pass through image URLs unfortunately.
