### ISSUE TITLE
History requests returning 403

### ISSUE THREAD

**Issue by Juice805** [trakt/api-help#415]
I am trying to access the user [history endpoint](https://trakt.docs.apiary.io/reference/users/history). Docs claim it does not require OAuth, but a `GET` request to `https://api.trakt.tv/users/juice805/history` in postman returns a 403 response.

I have also tried using OAuth with a token in the `Authorization` header & using the `me` id, which also returned a 403.

**Comment by rectifyer** [comment]
A `403` means your `trakt-api-key` is incorrect, it's not an OAuth error.
