### ISSUE TITLE
PUT notes/id not updating spoiler and privacy

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#417]
Hi @rectifyer ,

I'm trying to update a note just to update the spoiler and privacy settings but it doesn't seem to update those fields.

Updating the notes text works but not the rest.

I'm sending this PUT https://api.trakt.tv/notes/1527
Request Body: `{"privacy":"friends","notes":"XYZ","spoiler":false}`

And get this back 
Response Body: `{"id":1527,"notes":"XYZ","privacy":"private","spoiler":true,"created_at":"2023-09-23T17:35:33.000Z","updated_at":"2023-10-10T15:39:54.000Z","user":{"username":"kcador","private":false,"name":"Kevin Cador","vip":true,"vip_ep":false,"ids":{"slug":"kcador"}}}`

Maybe I'm doing something wrong?

Cheers,

Kevin

**Comment by kevincador** [comment]
Hey,

I don't know if something has changed in the meantime but it seems to work as expected now.

Cheers,

Kevin

**Comment by rectifyer** [comment]
I didn't change anything, so must have just been a bug or issue with the deploy. Glad it's working and really cool to see all the notes features in Rippple!
