### ISSUE TITLE
List Items pagination not working

### ISSUE THREAD

**Issue by thiagocard** [trakt/api-help#418]
When requesting items for a list, if we add the `page` query param everything works, but after adding the `limit` it returns an empty list.

Edit: I just realized it happens when the limit is  >= 50 (`users/me/lists/<listId>/items?page=1&limit=50`)

**Comment by rectifyer** [comment]
I'm not able to reproduce this issue. What specific list are you having an issue with? A full request and response (including headers) would help.

**Comment by thiagocard** [comment]
Hey @rectifyer, tried today and couldn't reproduce it anymore, not sure what happened before but now it's ok.
Thanks for the support!
