### ISSUE TITLE
/sync/history/remove removing movie by imdb ... adds the item

### ISSUE THREAD

**Issue by rysson** [trakt/api-help#419]
I'm trying to remove an item from the history by imdb id.
There is no error, but nothing is removed. 
Worse the item is **added** to the history. The same with tmdb id.
Removing works only with 64-bit raw-history id.

Request
`POST https://api.trakt.tv/sync/history/remove`
```json
{
  "movies": [
    {
      "ids": {
        "imdb": "tt10268488"
      }
    }
  ]
}
```

Response `200`
```json
{
  "deleted": {
    "movies": 0,
    "episodes": 0
  },
  "not_found": {
    "movies": [],
    "shows": [],
    "seasons": [],
    "episodes": [],
    "people": [],
    "users": []
  }
}
```

**Comment by rectifyer** [comment]
I just pushed a fix. Please let me know if it's working correctly now.

**Comment by rysson** [comment]
So awesome reaction time, thanks!
Everything is working now as was expected.
```json
{
  "deleted": {
    "movies": 5,
    "episodes": 0
  },
  "not_found": {
    "movies": [],
    "shows": [],
    "seasons": [],
    "episodes": [],
    "people": [],
    "users": []
  }
}
```
