### ISSUE TITLE
Question : list of possible timezone 

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#42]
Hello,

Is there a list of all the possible timezone you support in the doc? I can't find it. I would like my app to reflect the user choice!

Thanks

**Comment by rectifyer** [comment]
We use the built in list in Ruby on Rails. Check out https://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html which seems to have a mapping for what they provide.

**Comment by jonathanantoine** [comment]
ok, thank you :)
