### ISSUE TITLE
Server returning 500 error on sync/watched

### ISSUE THREAD

**Issue by mmoore99** [trakt/api-help#420]
When I run the following command I get a 500 server error. Is the server experiencing problems?

GET https://api.trakt.tv/sync/watched/shows

Request Headers
Content-Type: application/json
trakt-api-version: 2
trakt-api-key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Postman-Token: b88240b4-4a6e-40d8-865e-6a0efdc770bb
Host: api.trakt.tv
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

Response Headers
Date: Sat, 21 Oct 2023 02:32:27 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
x-frame-options: SAMEORIGIN
x-xss-protection: 0
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
Cache-Control: private, no-store
vary: Accept-Encoding
x-ratelimit: {"name":"AUTHED_API_GET_LIMIT","period":300,"limit":1000,"remaining":990,"until":"2023-10-21T02:35:00Z"}
x-request-id: ef9dcb4c-c703-468c-a263-03f2e853930a
x-runtime: 0.032077
CF-Cache-Status: DYNAMIC
Server: cloudflare
CF-RAY: 819617147ca5174e-SJC
alt-svc: h3=":443"; ma=86400
Response Body

**Comment by rectifyer** [comment]
Should be fixed now.
