### ISSUE TITLE
/shows/id/last_episode returns 204.  200 and Null was expected.

### ISSUE THREAD

**Issue by mpfc75** [trakt/api-help#422]
Trakt endpoint shows/id/last_episode returns HTTP 204 for shows that do not have any episodes.  For example:
```
--> GET https://api.trakt.tv/shows/173650/last_episode?extended=full
--> END GET
<-- 204 https://api.trakt.tv/shows/173650/last_episode?extended=full (37ms)
date: Wed, 01 Nov 2023 21:29:04 GMT
x-frame-options: SAMEORIGIN
x-xss-protection: 0
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
expires: Thu, 02 Nov 2023 05:10:27 GMT
cache-control: public, max-age=28800
x-ratelimit: {"name":"AUTHED_API_GET_LIMIT","period":300,"limit":1000,"remaining":815,"until":"2023-11-01T21:15:00Z"}
x-request-id: 7f110739-3ba5-4ce5-8dab-c96e5ecfe6a9
x-runtime: 0.011299
cf-cache-status: HIT
age: 1116
vary: Accept-Encoding
server: cloudflare
cf-ray: 81f73b2c1f78a253-YYZ
alt-svc: h3=":443"; ma=86400
<-- END HTTP
```
I was expecting to receive a 200 and a null episode.  Is this an incorrect assumption on my part?

**Comment by mpfc75** [comment]
Actually, I think I misspoke about the show not having episodes. It does, just one.

**Comment by mpfc75** [comment]
Closing... sorry for confusion.  I reread the doc (RTFM right?) and I see that the endpoint returns the most recently aired episode or a 204.  Apparently working as designed.

**Comment by rectifyer** [comment]
A 204 is a valid success, just with no content (i.e. null) being return. I think that is valid if there is no episode found. For that show, there are no aired episodes. We use the `first_aired` and it is `null`.
