### ISSUE TITLE
Problem with CORS when using the API

### ISSUE THREAD

**Issue by Ricrdsson1** [trakt/api-help#426]
Hello, I have a problem with CORS verification when using your API on my Web site. I added my WEB in your interface to enable CORS but it probably doesn't work.

```
var request = new XMLHttpRequest();

request.open('POST', 'https://api.trakt.tv/oauth/device/code');

request.setRequestHeader('Content-Type', 'application/json');

request.onreadystatechange = function () {
  if (this.readyState === 4) {
    console.log('Status:', this.status);
    console.log('Headers:', this.getAllResponseHeaders());
    console.log('Body:', this.responseText);
  }
};

var body = {
  'client_id': 'xxx'
};

request.send(JSON.stringify(body));
```

**Comment by Ricrdsson1** [comment]
:)

**Comment by rectifyer** [comment]
@iGerman00 Try sending a `User-Agent` header and see if that works.

**Comment by iGerman00** [comment]
It is being sent, it’s a browser so it should always be sent. Sorry I just excluded it for privacy/fingerprinting reasons along with language headers, dnt and other kind of fluff. I actually also tried in Safari (macOS) and it complained about both CORS headers missing and COAH headers not permitting `User-Agent`.

**Comment by iGerman00** [comment]
@rectifyer I've re-implemented it to use oauth, but it is still flakey. It seems like your server takes a bit of time before recognizing that it needs to send the necessary headers, and Safari still fails for me:

```
[Error] Request header field User-Agent is not allowed by Access-Control-Allow-Headers.
[Error] Fetch API cannot load https://api.trakt.tv/oauth/token due to access control checks.
[Error] Failed to load resource: Request header field User-Agent is not allowed by Access-Control-Allow-Headers.
[Error] Failed to exchange code for token: – TypeError: Load failed
```
