### ISSUE TITLE
Sort by in search

### ISSUE THREAD

**Issue by AlRos14** [trakt/api-help#427]
Hello! Is there a way to change the default mode in API searchs? I don't want to sort by score and I can't find any way to change this. I'm working on a random movie generator but it's difficult if the API won't let me work.

**Comment by rectifyer** [comment]
What field did you want to sort by? Returning random results doesn't really make sense if a ton of results are being generated.

**Comment by rectifyer** [comment]
No current plans to support sorting since it makes the results less revenant.
