### ISSUE TITLE
How to determine if a show is hidden?

### ISSUE THREAD

**Issue by maxhand** [trakt/api-help#430]
I'm trying to filter out shows that a user has hidden, and I was initially using the endpoint listed at  https://trakt.docs.apiary.io/#reference/users/hidden-items/get-hidden-items, but unfortunately it seems like this endpoint is paginated so doing a full lookup of hidden items would be very inefficient. 

I'm trying to filter out hidden items when fetching a user's watched shows, as well as when displaying individual show watched progress. What's the best way of filtering out shows that they've hidden? Is there an equivalent of the /sync/watched/ endpoint that returns a single-page result that contains hidden statuses for shows?

Thank you!

**Comment by rectifyer** [comment]
You should cache the hidden items locally in your app. Then check https://trakt.docs.apiary.io/#reference/sync/last-activities/get-last-activity and compare the `hidden_at` timestamp to what you have cached locally. The `/sync/last_activities` should always be the first step, so you know what needs to be re-cached and what can just continue using the locally cached data.

**Comment by maxhand** [comment]
Thank you for the response.

Is it best practice to use a similar approach with use lists? Cache the individual lists and check the individual list activity timestamps to determine which lists need to be recached?

**Comment by rectifyer** [comment]
Yeah, you can check the `listed_at` in `/sync/last_activities` then check `updated_at` in `/users/me/lists` then updated any changed lists.
