### ISSUE TITLE
"Seasons/Summary/Get all seasons for a show" failing on staging api

### ISSUE THREAD

**Issue by eliottrobson** [trakt/api-help#432]
I'm currently developing an app and the following endpoint has been failing on the staging API for a couple of days.
I was hoping it was temporary but not sure how well monitored the staging endpoint is!

https://trakt.docs.apiary.io/#reference/seasons/summary/get-all-seasons-for-a-show

**Comment by rectifyer** [comment]
Please try now and let me know if it works correctly.

**Comment by eliottrobson** [comment]
Working now, thank you very much!
