### ISSUE TITLE
Ratings endpoint times out when posting large amount of ratings

### ISSUE THREAD

**Issue by frlefebvre** [trakt/api-help#448]
Are there any guidance regarding how many items can be sent to the ratings endpoint? When users first sync their accounts with Trakt, my app might need to send large amounts of ratings as it uploads its content to Trakt. 

In the case of one user, it's trying to post ~800 ratings but that request times out. I'm guessing I should send them in smaller batches but I'm not sure how conservative I should be.

Any guidance would be appreciated!

**Comment by frlefebvre** [comment]
Looking into this some more, if I increase my time out duration, the API takes about 45s to respond when being sent 800 ratings. It *feels* like a long time although I appreciate that's a lot of entities to send. Maybe this could be optimised, or at least documented for other devs to know that response time on this endpoint is proportional with the number of ratings sent.

In the meantime, I'm now making multiple calls instead of a single one, in batches of 200 ratings which solves the issue for me.

**Comment by rectifyer** [comment]
It takes a while since it's checking to see if an existing rating exists we need to update, or if a new record is created. In the future, we have some ideas about async endpoints so things can be processed in the background.
