### ISSUE TITLE
Cast for a given season of a show 

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#45]
Hello,

Is it possible to get the cast of a given season of a show? Sometimes when you catch-up an old season it would be nice! Thanks!

**Comment by rectifyer** [comment]
Not yet, but we hope to support season and episode level casts in the future.

**Comment by jonathanantoine** [comment]
That would be awesome, I look forward to see this happen.

**Comment by rectifyer** [comment]
This is now available. https://github.com/trakt/api-help/issues/74
