### ISSUE TITLE
Value for first_aired is returned as null for all seasons

### ISSUE THREAD

**Issue by methom** [trakt/api-help#452]
I noticed that recently the field `first_aired` contains `null` for all seasons I tried, about three dozen.

E.g. this endpoint `https://api.trakt.tv/seasons/29588?extended=full` provided a `first_aired` value of `null`, while ten days ago, it contained `2013-10-04T00:00:00.000Z` (see attached json files).

The website still shows the correct date, as the screenshot from today proves.

![image](https://github.com/trakt/api-help/assets/5956406/e38045ee-76a3-4ae1-b7c9-cdeec3108e0e)

[vampire_diaries_season_5_2024-04-15.json](https://github.com/trakt/api-help/files/15118799/vampire_diaries_season_5_2024-04-15.json)
[vampire_diaries_season_5_2024-04-25.json](https://github.com/trakt/api-help/files/15118800/vampire_diaries_season_5_2024-04-25.json)

**Comment by rectifyer** [comment]
Good catch. I will have a fix out early next week.

**Comment by methom** [comment]
Thanks for the quick reaction!
