### ISSUE TITLE
[suggestion] activate link with code for devices

### ISSUE THREAD

**Issue by rysson** [trakt/api-help#454]
On device (`urn:ietf:wg:oauth:2.0:oob`) we can generate QR-code on trakt activation.

Is it possible to add code to the link (like `https://trakt.tv/activate/12345678`)?
I'll be much easier to activate the device.

It could be redirect to the same page as now but with filled box. Nothing more.

![20240513-141510-455x480](https://github.com/trakt/api-help/assets/5898312/6d5cf8d3-bd9f-464d-9b25-b275371618dc)

**Comment by rectifyer** [comment]
Good idea! I will have this supported later in the week with the next website update.

**Comment by rysson** [comment]
Oh, I was waiting for code in activate link sent by you and miss that code in link already works.

No I add code to the path if no code in activate link. 

It's awesome now and very easy to use. Thank you very much!
![20240527-090453-820x383](https://github.com/trakt/api-help/assets/5898312/bbf4c0e9-f39d-497b-aa1f-08a348b088ca)
