### ISSUE TITLE
Multiple 500 errors

### ISSUE THREAD

**Issue by linaspurinis** [trakt/api-help#463]
I don't know if this is a known issue, but I'm getting multiple 500 errors for simple API requests like https://api.trakt.tv/users/settings

**Comment by michaldrabik** [comment]
@linaspurinis @rectifyer I think something is down in general : https://trakt.tv/dashboard 

<img width="771" alt="image" src="https://github.com/trakt/api-help/assets/11537045/2f9c52e8-7b3c-451c-ba3a-7a886bbf0869">

**Comment by kevincador** [comment]
For everyone's info, I'm usually checking this: https://status.trakt.tv

@rectifyer if it helps, I had a 500 error in Rippple, logged out and in again and it was okay, I don't know if it was linked to my session but it seems like it ☺️

**Comment by kevincador** [comment]
The logout-login isn't really helping finally. 
The /history endpoint seems to be down all the time and the /settings endpoint is sometimes okay but at some point I'm still  kicked out of the app because it's 500ing on me.

**Comment by rectifyer** [comment]
Are there still any issues related to this? If so, please post a full API request and response.
