### ISSUE TITLE
500 errors when fetching show progress for unaired series.

### ISSUE THREAD

**Issue by dvcol** [trakt/api-help#464]
When fetching progress on a show with unhaired episodes (but already logged plays) likes [orphan black: echoes](https://trakt.tv/shows/orphan-black-echoes).

Which first aired back in [November](https://www.imdb.com/title/tt10016724/) although it erroneously shows as unhaired on Trakt.

I get 500 errors:

![image](https://github.com/trakt/api-help/assets/17250935/95f9ee98-3f40-442c-8b99-58fd7c219a43)

To note, this seems only to occur when requesting specials (which this show doesn't contain).

These errors go away when fetching without specials (most likely an issue in the backend ?)

![image](https://github.com/trakt/api-help/assets/17250935/b571b117-cad4-4712-b27a-52b9a0fa7919)

I also get 500 when I attempt to remove plays directly form the website:

![image](https://github.com/trakt/api-help/assets/17250935/8a46015d-2446-4543-a6e1-3ed61ce77fb9)

**Comment by rectifyer** [comment]
@dvcol I just pushed a few for the API. The same fix might also fix the website. Please let me know if it's working any better for you.

**Comment by dvcol** [comment]
Hey, seems to be fixed now, thanks for the speedy response :)

It now sends back an empty progress object instead of a 500, no matter if specials are queried or not 👍 

Although this particular show aired back in November in Canada, but maybe this is due to my region settings?

**Comment by rectifyer** [comment]
We get the air dates from TMDB. I'm not sure why they are using the US release dates as the main ones, but that's why we don't consider it aired.
