### ISSUE TITLE
refresh_token error (400: invalid request, "missing required parameter: grant_type")

### ISSUE THREAD

**Issue by vankasteelj** [trakt/api-help#471]
Hi there, 

I'm having an issue with the `refresh_token` call, it's giving back an error 400: 
> invalid request, "missing required parameter: grant_type"

Below I include my POST body: 
![nw_QhHL41OtNB](https://github.com/user-attachments/assets/852a4b06-8afa-4ef4-af05-92f9c80f9ed3)

And here's the response:
![nw_SfQAw1CM1K](https://github.com/user-attachments/assets/b7c227c6-82c7-4311-987e-71d5f857ceba)

The `grant_type: 'refresh_token'` is sent in the body, but the server says it's not. I don't believe it's an error on my part (?) : I'm successfully using the same method for `grant_type: 'authorization_code'` and there everything works fine.

**Comment by vankasteelj** [comment]
Debugging: the same error occurs when I send an empty body `'{}'`.

**Comment by vankasteelj** [comment]
I found the error : my "refresh_token" was too old. What is it's TTL ? And why is the response "400" instead of "401" ? 

I retried with a new authentication, then forced a refresh_token, and everything works fine. I don't get it.

**Comment by rectifyer** [comment]
Tokens are valid for [3 months](https://trakt.docs.apiary.io/#reference/authentication-oauth/get-token/exchange-code-for-access_token). A `400` status code typically means the JSON being sent is invalid.

**Comment by vankasteelj** [comment]
I'm sorry but this is not completed. My issue is solved, but the issue isnt. 

1/ The access_token needs to be refreshed every 3 months using refresh_token, alright. That's not what is said on the API documentation, that only says the access_token is valid for 3 month. The fact that the refresh_token also has a TTL of 3 month isn't mentionned and could be included, as I found plenty of other people asking the same question on the web but no answer. 

2/ The json sent was valid, proven by the fact that I can refresh my access_token in the 3 months period. But once that period is over, the response should be "401 - invalid grant", but here was a "400 - missing required parameter" although the parameter was sent. So that code is faulty and it might indicate that something needs to change on the api-side.
