### ISSUE TITLE
Cloudflare blocking calls to the API :(

### ISSUE THREAD

**Issue by sconaty** [trakt/api-help#478]
Earlier today calls to the API started being blocked by Cloudflare for my machine. The following `GET`...

- https://api.trakt.tv/calendars/all/shows?extended=metadata&counties=us&start_date=2024-09-17&days=4

...now results in Cloudflare returning a HTML page with the following message:

> _This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data._
> 
> _You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page._
> 

I haven't changed my code in months so I'm not sure why this has been triggered now. Any feedback you could provide would be appreciated. The referenced id is:

- **Cloudflare Ray ID:** `8c5308a1ea1c072b`

Thanks

**Comment by rectifyer** [comment]
What region are you accessing the API from? That URL works for me, so Cloudflare seems to be blocking your access based on some sort of threat detection.

**Comment by sconaty** [comment]
The call is being made from California, USA.

I'm sure the URL works generally for others and for some reason Cloudflare has taken umbrage to my calls :(. It is my understanding the Cloudflare Ray ID can be used to help determine why the request is being blocked, via the Cloudflare UI.

- https://developers.cloudflare.com/fundamentals/reference/cloudflare-ray-id/

**Comment by sconaty** [comment]
Cloudflare now appears to be letting my requests through - which is great. So the issue is **resolved**.

If you have more information, based on the Cloudflare Ray ID: `8c5308a1ea1c072b` it would be great. If at all possible I'd like to be able to avoid this in future, so any details would be fantastic. Thanks!

**Comment by sconaty** [comment]
Unfortunately, today the same API call is back to failing again, with a `403` response code. Cloudflare is interceding and mitigated these requests with the same response as before.

I have new Cloudflare Ray IDs for the failing calls. I picked one at random:

* **Cloudflare Ray ID:** `8cb5fe406b7a9834`

Could you please check the Cloudflare Security Events [Activity Log](https://developers.cloudflare.com/waf/analytics/security-events/) to help determine why Cloudflare has decided to sporadically block my requests. Thanks.

**Comment by ubsys** [comment]
Hi!
After running my app for over a year in the same region 'Brazil' and on the same PCs, it started returning this Cloudflare page instead of the classic JSON response. I tested the same call with the same headers on the same PC using 'Postman' and it worked perfectly. What could be causing this error?

**Comment by ubsys** [comment]
> Hi! After running my app for over a year in the same region 'Brazil' and on the same PCs, it started returning this Cloudflare page instead of the classic JSON response. I tested the same call with the same headers on the same PC using 'Postman' and it worked perfectly. What could be causing this error?

Same code, same pc, etc. Starts work again now! ..??

**Comment by sconaty** [comment]
Mine has also started working today. So I will close the ticket again - but I do think it would be a good idea for someone, on the Trakt side, to check the Cloudflare Ray IDs. This problem is just going to happen again without more information - or an update to the Cloudflare configuration.

**Comment by rectifyer** [comment]
@sconaty Looks like Cloudflare blocked it since it detected your script as an AI bot. It appears to be a built in rule from what I can tell.

**Comment by sconaty** [comment]
Thanks for the detail @rectifyer. It is what I asked for, but now I have it I'm not sure what to do it :).
For reference my application is written in Rust, uses the [Restson crate](https://crates.io/crates/restson) to make calls - all hand rolled code (was a great way to learn Rust). No AI anywhere.

I do see CloudFlare has implemented logic to [block AI web scrapers](https://blog.cloudflare.com/declaring-your-aindependence-block-ai-bots-scrapers-and-crawlers-with-a-single-click/) but I don't understand why that would block APIs rest calls.
