### ISSUE TITLE
Search API returning error 502

### ISSUE THREAD

**Issue by MaxHasADHD** [trakt/api-help#5]
Currently getting back error 502 when making a search request. Making a request to 
`https://api.trakt.tv/search/show?page=1&query=The%20Good%20Place&limit=30`

**Comment by tysonkerridge** [comment]
Looks like the API is down atm: http://status.trakt.tv

**Comment by rectifyer** [comment]
Looks like some of the API servers had an issue, then auto recovered shortly after. I'll keep an eye and see if this happens again and if we can find a cause.
