### ISSUE TITLE
CORS issue on revoke token

### ISSUE THREAD

**Issue by JumBay** [trakt/api-help#51]
Hi,

On the route POST `https://api.trakt.tv/oauth/revoke` I got a CORS issue. It works fine with all other routes.

Thanks

**Comment by rectifyer** [comment]
Can you provide a code example so I can reproduce the issue?

**Comment by JumBay** [comment]
```JS
fetch('https://api.trakt.tv/oauth/revoke', {
  'headers': { 'content-type': 'application/json' },
  'referrer': 'http://localhost:8100',
  'body': '{"token":"ZZZ","client_id":"XXX","client_secret":"YYY"}',
  'method': 'POST'
});
```
I've tried with header's credentials too but same error: 

> Access to fetch at 'https://api.trakt.tv/oauth/revoke' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by sharkykh** [comment]
I can confirm this issue as well.

**Comment by igorissen** [comment]
I'm using Angular and I have the same issue.
Here is a copy from Chrome devtool.

```js
fetch("https://api.trakt.tv/oauth/revoke", {
    "credentials": "omit",
    "referrer": "http://localhost:4200/movies",
    "referrerPolicy": "no-referrer-when-downgrade",
    "body": null,
    "method": "OPTIONS",
    "mode": "cors",
    "origin": "http://localhost:4200"
});
fetch("https://api.trakt.tv/oauth/revoke", {
    "credentials": "include",
    "headers": {
        "accept": "application/json, text/plain, */*",
        "authorization": "Bearer TOKEN",
        "content-type": "application/json",
        "trakt-api-key": "CLIENT_ID",
        "trakt-api-version": "2"
    },
    "referrer": "http://localhost:4200/movies",
    "referrerPolicy": "no-referrer-when-downgrade",
    "body": "{\"token\":\"TOKEN\",\"client_id\":\"CLIENT_ID\",\"client_secret\":\"CLIENT_SECRET\"}",
    "method": "POST",
    "mode": "cors",
    "origin": "http://localhost:4200"
});
```

**Comment by rectifyer** [comment]
I pushed a fix in regards to this bug. Can you test it out and let me know if it works any differently now?

**Comment by sharkykh** [comment]
@rectifyer 
Thank you, looks like it's working correctly now for me :)

**Comment by rectifyer** [comment]
Cool, thanks for confirming and testing it out to make sure. Yeah, the structure for this method is a bit different for some reason due to the OAuth library we use.
