### ISSUE TITLE
Where to Watch

### ISSUE THREAD

**Issue by scottkuhl** [trakt/api-help#52]
Is where to watch information available through the API?

**Comment by rectifyer** [comment]
Unfortunately no, we're not able to provide watch now links via the API.

**Comment by m-vdv** [comment]
Hey Justin

I've been getting a lot of request to include this in my trakt.tv client app (Nachos).
Any chance this "where to watch" data will be added in the future?
You guys get the data from Reelgood right?
I assume they don't let you expose it in the trakt API?

Please give some insight, thanks!

**Comment by scottkuhl** [comment]
You can get the data from the ReelGood API if you contact them.  But I don't think it is free.
