### ISSUE TITLE
500 Status when updating comment with emoji

### ISSUE THREAD

**Issue by tysonkerridge** [trakt/api-help#54]
Appears to happen for only some emoji, and this isn't with converting to shortcodes. Using the POST (add comment) method appears to work for the same comment content (which gets converted to shortcodes), where the PUT (update comment) errors.

I also noticed if I send an update with comment content such as "This is a comment with emoji ❤️", the API doesn't convert the heart emoji to shortcodes, and returns it directly as the heart emoji when retrieving the comment. 

---

PUT https://api-staging.trakt.tv/comments/1121

"Content-Type" : "application/json"
"trakt-api-version" : "2"
"trakt-api-key" : "{key}"
 "Authorization" : "Bearer {token}"

"comment" : "This is a comment with emoji: 🔢"
"spoiler" : false

--- 

Status Code: 500

"Cache-Control" = "max-age=0, private, no-cache, no-store, must-revalidate"
"Content-Type" = "application/json; charset=utf-8"
Date = "Sun, 31 Mar 2019 06:32:01 GMT"
Server = cloudflare
Vary = "Accept-Encoding"
"cf-ray" = "4c00489d7bdf655d-SYD"
"expect-ct" = "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\""
"x-content-type-options" = nosniff
"x-frame-options" = SAMEORIGIN
"x-request-id" = "687b30c2-4417-4d7d-9225-2c8941df9880"
"x-runtime" = "0.023219"
"x-xss-protection" = "1; mode=block"

**Comment by rectifyer** [comment]
Good catch, the fix for this will be out Monday.
