### ISSUE TITLE
API unicode emoji to short code auto-conversion issue

### ISSUE THREAD

**Issue by tysonkerridge** [trakt/api-help#55]
I've found that when sending new comments with unicode emoji in them, the API is converting them to shortcodes as expected, and the website appears to be displaying them correctly, but the content sent through the API appears to be sending unexpected closing characters for some converted emoji.

After looking into it, I worked out that it's sending a `variation selector-16` instead of a `colon` character for the closing character of the shortcoded emoji. Even using the [official EmojiOne iOS parser](https://github.com/joypixels/emojione-ios) it's failing to convert it due to it expecting colons.

When sending the unicode heart emoji, `❤️`, it gets converted to `:heart:️` which looks like `:heart:` but the closing character (which, frustratingly, looks like a colon) is actually the "variation selector-16" character. You can check it out by pasting `:heart:️` into https://unicodelookup.com/. The issue appears to happen for a few others such as the 'smiling face' (or 'relaxed' shortcode) emoji (`☺️`).

I imagine maybe this isn't too big an issue, as if I convert to shortcodes before sending it appears to work, but I thought it was worth bringing up just in case, even to let others know it's not them going crazy!

An example comment with the issue:
The comment was created with the comment content of: `A comment created with Unicode heart ❤️`

GET https://api-staging.trakt.tv/comments/1126
```
{
  "spoiler" : false,
  "updated_at" : "2019-03-31T07:47:17.000Z",
  "likes" : 0,
  "replies" : 0,
  "comment" : "A comment created with Unicode heart :heart:️",
  "review" : false,
  "user_rating" : null,
  "created_at" : "2019-03-31T07:47:17.000Z",
  "parent_id" : 0,
  "user" : {
    "username" : "Ohifriend",
    "private" : false,
    "vip" : false,
    "vip_ep" : false,
    "name" : "Tyson",
    "ids" : {
      "slug" : "ohifriend"
    }
  },
  "id" : 1126
}
```

**Comment by rectifyer** [comment]
Looks like this character is from the emoji itself. More info: https://emojipedia.org/variation-selector-16/

The library we're using to auto convert isn't removing that control character, so I'll make a custom update to strip it out since its not needed with short codes obviously. Fix will be out Monday as well.
