### ISSUE TITLE
Response of `/shows/{{id}}/last_episode` was wrong when using slug instead of show id AND pass `extended=full`.

### ISSUE THREAD

**Issue by ShaneQi** [trakt/api-help#56]
|CORRECT: use id|CORRECT: use slug w/ `extended=full`|WRONG: use id w/ `extended=full`|
|:---:|:---:|:---:|
|<img width="761" alt="id-not-extended" src="https://user-images.githubusercontent.com/7324708/55454045-ff229f00-55a3-11e9-95d3-ed53048e16a9.png">|<img width="760" alt="slug_extended" src="https://user-images.githubusercontent.com/7324708/55454055-077ada00-55a4-11e9-8054-54ef7b302be8.png">|<img width="763" alt="id_extended" src="https://user-images.githubusercontent.com/7324708/55454053-05188000-55a4-11e9-9b17-d10023b945fd.png">|

# Update

I checked again just now, and it doesn't return wrong info anymore. 

So I guess it could be a caching issue. But why didn't the other ways of using that endpoint return wrong data? 

|request|response|
|:---:|:---:|
|use Id **with** `extended=full`|WRONG|
|use Id **without** `extended=full`|CORRECT|
|use slug **with** `extended=full`|CORRECT|
|use slug **without** `extended=full`|CORRECT|

Another thing I found is that when I use the console in https://trakt.docs.apiary.io, it didn't return wrong info, I guess it's hitting a different server from what we're hitting when we request in a normal way.

My service relies on this endpoint to calculate aired episode in real-time, I need that endpoint to return correct data without any delay. How I calculate is:

1. I stored the next episode info of every show.
2. When the next episode of a show is aired (based on it's `first_aired` datetime), I start a task to calculate how many episodes were actually aired (because shows like Netflix origins usually air multiple episodes at the same time).
3. In the task, I get the last episode info of the show and calculate the actually aired episodes. (for example, the episode that triggered the task is S04E01, and the last episode I fetch later is S04E10, then the actually aired episodes are S04E01, S04E02, S04E03..., S04E10, 10 episodes total)

So I'd like to know what could be happening here, e.g.:

1. Is the API logic different between using id with `extended=full` and the other three ways?
1. If the logic is the same, is the delay because of some caching? Why does the delay only happens when using Id with `extended=full`.
1. If the delay is expected behavior, Is it possible to eliminate the delay?
1. If we can't eliminate the delay, how long is the delay I should expect?
1. What are the other ways that you recommend to implement the real-time aired episodes calculation?

**Comment by ShaneQi** [comment]
It appeared that 'This is Us' is the only show that has this issue at this point in time.
And 'This is Us' just aired a new episode about 3 hours ago.

Hope these info helps.

**Comment by tysonkerridge** [comment]
Could be related to what Justin pointed out here: https://github.com/trakt/api-help/issues/33#issuecomment-467235284

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ShaneQi** [comment]
@tysonkerridge  I'm sorry I had a typo in the table. 

The one that returns wrong info **is actually using id**, but only when using `extended=full` together with it.

**Comment by tysonkerridge** [comment]
Fair enough! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rectifyer** [comment]
This is because of the caching at Cloudflare. It caches responses for 8 hours, then it will refresh the cached data. You can check the response headers like `cache-control` and `expires` to see the cache time and when it is due to expire. Our Cloudflare plan unfortunately doesn't allow us real time data or a way to expire the cache programmatically.

An alternative way to do this calculation is to get all episodes for a show, then calculate things locally based on the `first_aired` dates.

**Comment by ShaneQi** [comment]
Thanks for the explanation. I understand the constraint here. I will figure out another way to achieve what I need.

PS:

You guys are doing great maintaining the Trakt API, I'm a 2-year VIP member, hope you can get more support.
