### ISSUE TITLE
Support sorting for the /watchlist endpoint

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#58]
It would be great if we could ask the `/watchlist` with a way to sort the result. I'm currently looking to fetch the watchlist page by page but I can't if I want to display the watchlist sorted. I have to either fetch the whole list without paging (I'm not sure it's a good idea for really big watchlists) or fetch everything page by page to be able to sort in-app (but then the user will need to wait until every page are fetched and the sort to happen in-app).

One way to handle this would be by adding `X-Sort-By` and `X-Sort-How` to the request. If you don't give them in the request, you could still send them back in the response for people relying on it.

**Comment by rectifyer** [comment]
This isn't easily accomplished since a lot of sorting parameters require a lot of logic to do. That is why the website does sorting client side since the database queries and joins would be too intense.

What sorting options are you specifically trying to apply? I can look into specific use cases and see if anything is possible without being a performance hit. In general though, we return all lists in ranked order since it was a performance issue when we created that API method.

**Comment by kevincador** [comment]
I understand. I don't know the complexity behind them in terms of queries but here would be my :

**added**: would be super useful, the only one I'm really looking forward to seeing if only one can be achieved - seems pretty easy to cache too
**released**: would be cool for a watchlist but may be better to have a filter /released (after the first media filter) to only get what has been released sorted by release date - but this idea would make it harder to cache so maybe just sort by release date and we can do the work in app
**rank**: already ✅ 

Less useful in my opinion:
**title**: would help find something you know you have in the watchlist - easy to cache
**runtime**: would help find something short or long - easy to cache
**popularity**: not easy to cache
**percentage**: not easy to cache
**votes**: not easy to cache

**Comment by Kashish-Sharma** [comment]
Any updates on this ?

**Comment by rectifyer** [comment]
I was able to support sorting by `rank` (default), `added`, `released`, and `title`. This will only work when also specifying an item `type` for the watchlist. Docs are updated and the updated methods will be available later today.

**Comment by kevincador** [comment]
@rectifyer is this available in prod already? I can't see it in the documentation.

**Comment by rectifyer** [comment]
Oops, there was a typo that hid the documentation updates. Should be there now.

https://trakt.docs.apiary.io/#reference/sync/get-watchlist/get-watchlist

**Comment by kevincador** [comment]
Thanks!

Will it be always ascending when I request it the list to be sort? Or should I always check the `X-Applied-Sort-How`?

**Comment by rectifyer** [comment]
You should check that header value.

**Comment by rysson** [comment]
> I was able to support sorting by `rank` (default), `added`, `released`, and `title`. 

Hi, it's great, I can force `X-Applied-Sort-By`. Could you tell me how to change the order  (`X-Applied-Sort-How`)?
It looks like *sort-by* has corresponding *sort-how*:
- rank: asc
- added: desc
- released: desc
- title: asc

I don't now how to sort `added,asc` (both orders for `added` have sense). The same – `released`.

The only way I see is in **every** access (ton each page):
-  update watchlist setting (change sort)
- get watchlist (page)
- restore watchlist sort setting.
