### ISSUE TITLE
User email address

### ISSUE THREAD

**Issue by m-vdv** [trakt/api-help#59]
Please add the authenticated user's email address to the user settings api endpoint.
Here: https://trakt.docs.apiary.io/#reference/users/settings/retrieve-settings

Obviously you don't want to expose every users email address through the API.
But I don't see an issue with providing the authenticated user's email address.

"include_email" could be an optional parameter (like twitter does it).

Would like to hear your thoughts on this.

**Comment by rectifyer** [comment]
Unfortunately, we don't ever plan on exposing a user's email address via the API. This would mean an app could harvest people's emails who gave them access.

**Comment by m-vdv** [comment]
Hi Justin

Ok, I respect this decision. Ultimately it's better to keep user data like this safe so it can't be abused.

Thanks!
