### ISSUE TITLE
Wrong item using search

### ISSUE THREAD

**Issue by MrMamen** [trakt/api-help#6]
Request URL: `https://api.trakt.tv/shows/113/seasons/1/episodes/2`
Request Method: `GET`
response: `{"season":1,"number":2,"title":"Episode 2","ids":{"trakt":6380,"tvdb":306931,"imdb":"tt0830382","tmdb":5414,"tvrage":0}}`

These IDs does not match: https://trakt.tv/shows/113/seasons/1/episodes/2 as expected. Instead they match: https://trakt.tv/shows/nathan-barley/seasons/1/episodes/2

This can be demonstrated with a regular search outside the API as well: https://trakt.tv/search/trakt?query=6380

**Comment by rectifyer** [comment]
The API matches using the `trakt_id` first, so it is matching `113` which is the show "Nathan Barley". The website prefers slugs first since that is more readable for the web.
