### ISSUE TITLE
Polish VOD 

### ISSUE THREAD

**Issue by artix-dev** [trakt/api-help#63]
Hello, would it be possible to do Polish VOD?

**Comment by rectifyer** [comment]
Trakt itself doesn't provide and watch now streaming links. I'm not sure if anyone else has a Polish source for you to use?

**Comment by artix-dev** [comment]
I am looking for a website that provides Polish VOD and it is very difficult to find something in the style of trakt.tv 😔

**Comment by artix-dev** [comment]
This website provides
https://www.justwatch.com/pl/serwis-streamingowy/vod-poland/filmy but
unfortunately I do not see API

pt., 19 kwi 2019, 16:45 użytkownik Justin <notifications@github.com>
napisał:

**Comment by rectifyer** [comment]
I don’t really have any info on that site.
