### ISSUE TITLE
Delay in updating seasons/shows aired episodes information

### ISSUE THREAD

**Issue by nixgates** [trakt/api-help#66]
If someone wouldn't mind helping me out here, it seems there is often a large delay in updating the aired episodes value for both season and show items. 

I've been doing some checks over the past few days it often seems to take a day or two for this information to be updated on some item.

As of writing this issue, Brooklyn Nine Nine is currently showing: ` "aired_episodes": 125` while the last released episode was released near 5 hours ago.  I apologize as I know this is not as big of a gap that I'm describing but it's an example of the issue.

The Last Episode API response for the show in question returns the following aired/updated information:
```
"first_aired": "2019-04-26T01:00:00.000Z",
"updated_at": "2019-04-26T05:07:49.000Z",
```

Is it possible the show/season information is not being refreshed when a related episode item is aired/updated?

**Comment by kevincador** [comment]
This is most probably due to caching. Trakt can't invalidate the cache of specific requests like that every time an info is updated. Try to have a look at the cache headers of the response to make sure.

**Comment by rectifyer** [comment]
Yes, this is because of how those methods are cached. We unfortunately can’t invalidate quicker with the Cloudflare plan we are using. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nixgates** [comment]
That's fair enough, I'll make some changes on my end to try and identify and workaround it using the users local database.

I appreciate the help.
