### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by Kashish-Sharma** [trakt/api-help#67]
I'm facing issues with pagination:
`https://api.trakt.tv/sync/watched/movies?page=1&limit=10`

No matter what value is passed in `page` and `limit`, it's always returning the same data.

Tried with `retrofit`, `postman`

**Comment by Kashish-Sharma** [comment]
Seems like this endpoint doesn't support pagination

**Comment by Kashish-Sharma** [comment]
Pagination in `/watched` endpoint similar to `/watchlist` ?

**Comment by rectifyer** [comment]
As you mentioned, this endpoint doesn't support pagination. The idea is all watched items are returned so you can fully sync locally.
