### ISSUE TITLE
Set a rating for a season by it's id

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#7]
Hello,

Is it possible to set a rating for a season by it's id ? 
The only way I see in the doc is using the showId and the season number.

Thanks !

**Comment by rectifyer** [comment]
Yes it is. In fact, there are several methods that can accept season objects directly. I've updated the docs for the following methods. Good catch!

/sync/collection
/sync/collection/remove
/sync/history
/sync/history/remove
/sync/ratings
/sync/ratings/remove
/sync/watchlist
/sync/watchlist/remove
/users/:id/lists/:list_id/items
/users/:id/lists/:list_id/items/remove

**Comment by jonathanantoine** [comment]
Thank you @rectifyer
