### ISSUE TITLE
Accessing/Syncing Friends and their History/Ratings etc

### ISSUE THREAD

**Issue by tysonkerridge** [trakt/api-help#70]
Is it possible to know when a user’s friends have changed, and/or at least to know when a friend’s history/ratings have changed? If not, perhaps it could be added? For context, I wanted to display friends history and ratings for specific items as the Trakt website does.

For friends changing, `/sync/last_activities` doesn’t seem to contain any information if the users friends have changed so I don’t think there’s any efficient way to know when they change in order to keep the list synced. 

For getting friends history/ratings info for items, the `/sync` endpoints, including `/sync/last_activities` require oauth, so while I can access `/users/id/watched` and `/users/id/ratings` for friends, there’s no efficient way to know if those changed either. I also thought of using `/users/id/history/type/item_id` for history, which might not be too bad, but there’s no way to check for individual ratings.

Of course I could access and cache the information once and check periodically for changes, but it’d be great to have a way to check before pulling that info for multiple friends, even if it’s without extended info (really I just need the IDs from each of those endpoints for each friend to compare if they’ve seen/rated it).

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rectifyer** [comment]
You bring up some good points. The main reason we don't expose all the timestamps for your friends is for privacy reasons. And the reason we don't have methods that return if your friends watched it is for performance reasons. Are you trying to replicate the `Network` section on the Trakt dashboard?

**Comment by tysonkerridge** [comment]
Was trying to replicate the sections in the movie/show/season/episode pages that show up within the “now watching” section, which has which friends have watched and/or rated the item. But also yeah the “Network” dashboard implementation I have isn’t ideal either, due to not knowing whether my friends have changed efficiently, let alone their watched info. 

Also in general was wanting to be able to efficiently store a misc users profile should someone want to view one, where the app has auth to do so based on account privacy etc, such as their watched/collected/ratings, so that I can display user profiles like Trakt and all the data you see there, which I’m already generating for the logged in user from the sync methods to display for them.

Totally understand the privacy concerns, but I suppose it’s not impossible to work it out by hitting up the endpoints themselves and scanning for the earliest/latest date. In my case I just want to know if I should hit those endpoints or not. 

Alternatively if there was some kind of caching on those endpoints it might help too,  as I think they don’t have any at the moment? But I doubt that’s a good idea either.

**Comment by Tiger3030** [comment]
Has anything changed in this situation in the last year?

My suggestion would be
- to add a _“Friends Stats”_ method to `/movies`, `/shows`, `/seasons` and `/episodes` that returns the following data for the users the authenticated user follows:
```
[
  {
    "user_stats": {
      "rating": 10,
      "play_count": 1,
      "completed_count": 1,
      "recommended": true,
      "watchlisted": false,
      "collected": false,
      "commented": false
    },
    "user": {
      "username": "justin",
      "private": false,
      "name": "Justin N.",
      "vip": true,
      "vip_ep": false,
      "ids": {
        "slug": "justin"
      }
    }
  }
]
```

- and to add a _“Friends History”_ method to `/sync` that returns a combined history of the users the authenticated user follows, which could look like this:
```
[
  {
    "watched_at": "2014-03-31T09:28:53.000Z",
    "action": "watch",
    "type": "movie",
    "movie": {
      "title": "The Dark Knight",
      "year": 2008,
      "ids": {
        "trakt": 4,
        "slug": "the-dark-knight-2008",
        "imdb": "tt0468569",
        "tmdb": 155
      }
    },
    "user_stats": {
      "rating": 10,
      "play_count": 1,
      "completed_count": 1,
      "recommended": true,
      "collected": false,
      "commented": false
    },
    "user": {
      "username": "sean",
      "private": false,
      "name": "Sean Rudford",
      "vip": true,
      "vip_ep": false,
      "ids": {
        "slug": "sean"
      }
    }
  },
  {
    "watched_at": "2014-02-27T09:28:53.000Z",
    "action": "checkin",
    "type": "episode",
    "episode": {
      "season": 2,
      "number": 1,
      "title": "Pawnee Zoo",
      "ids": {
        "trakt": 251,
        "tvdb": 797571,
        "imdb": null,
        "tmdb": 397629
      }
    },
    "show": {
      "title": "Parks and Recreation",
      "year": 2009,
      "ids": {
        "trakt": 4,
        "slug": "parks-and-recreation",
        "tvdb": 84912,
        "imdb": "tt1266020",
        "tmdb": 8592
      }
    },
    "user_stats": {
      "rating": null,
      "play_count": 1,
      "completed_count": 1,
      "collected": false,
      "commented": false
    },
    "user": {
      "username": "justin",
      "private": false,
      "name": "Justin N.",
      "vip": true,
      "vip_ep": false,
      "ids": {
        "slug": "justin"
      }
    }
  }
]
```

I think with this version there aren’t any privacy concerns as no timestamps are exposed.

But of course, I do not know how the performance would be. 
On one hand, it will take more performance to provide this data in the API, but on the other hand I think this will lead to less API calls as you would have to make six calls per friend of the authenticated user to get this data at the moment, but with the new methods it would only be one call for the data for all friends.

In the long term it is definitely a good idea to add such methods, as this will lead to more apps implementing these “social features”, which in my opinion will improve Trakt a lot.
