### ISSUE TITLE
Stats algorithm regarding episodes

### ISSUE THREAD

**Issue by jonathanantoine** [trakt/api-help#71]
Hello,

I am working with the user/stats endpoint and I struggle to understand the how "episodes minutes" are computed. 

If I take all the watched episode from the user (which I already have locally in a cache) and I multiply by each show episode duration I do not find the same amount.

Is there something I miss?

Thanks!

**Comment by kevincador** [comment]
If you just multiply by the show episode duration it's not as precise. Some shows have a runtime of 60min but in reality, some episodes are 60, some are 90 and it can be 120 min for a season or show finale.

What you need to do is add all the history item duration to have the most accurate number.

**Comment by jonathanantoine** [comment]
@kevincador this information is available trough the Api ?

**Comment by kevincador** [comment]
the runtime is available at the episode level. I don't think you have it at the history item level. You need to do a lot of database access or cache this in a smart way if you want to have an accurate time in front of the TV.

**Comment by jonathanantoine** [comment]
@kevincador oh ok, I missed it on the episode which already have in my cache. Thanks a lot for pointing me in the right direction ;)
