### ISSUE TITLE
Movie cast and crew extended info not returning correctly

### ISSUE THREAD

**Issue by MaxHasADHD** [trakt/api-help#72]
Making a request to `GET https://api.trakt.tv/movies/304278/people?extended=full` returns minimal information. I can get full info for `GET https://api.trakt.tv/movies/304278/people?extended=min` and `GET https://api.trakt.tv/movies/304278/people?extended=FULL`

**Comment by rectifyer** [comment]
Good catch, looks like a caching issue. I'll have a fix out soon. I'm also working on some other cast/crew updates that will be out soon too. Since we're storing per season and per episode cast/crew info, we'll start exposing that in the API too.

**Comment by MaxHasADHD** [comment]
Sounds great! Can't wait for the updates

**Comment by rectifyer** [comment]
This bug is fixed and check out the new `people` related methods.
https://github.com/trakt/api-help/issues/74
