### ISSUE TITLE
Unable to get movie poster from Trakt id

### ISSUE THREAD

**Issue by ngengesenior** [trakt/api-help#78]
I know, it is explained in the documentation how to use the traktId and slug to get media. I am developing an Android application but when I append the slug to the baseURL,_https://api.trakt.tv/ , I am still unable to load an image into the app. What specific URL do I have to use to get the image URL from the traktId or slug?

**Comment by tysonkerridge** [comment]
The Trakt API doesn’t have images directly. You need to use the different identifiers in the objects to get access to images from other sources (eg. TVDB/TMDB).

You can find the documentation here: https://trakt.docs.apiary.io/#introduction/images, and the blog post (also linked in the documentation) here: https://apiblog.trakt.tv/how-to-find-the-best-images-516045bcc3b6



<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
