### ISSUE TITLE
End point for creating new custom list

### ISSUE THREAD

**Issue by Kashish-Sharma** [trakt/api-help#81]
I couldn't find the API method for creating a new custom list.

**Comment by tysonkerridge** [comment]
It’s in the “Users” section under “Lists”. “Create custom list”. https://trakt.docs.apiary.io/#reference/users/lists/create-custom-list

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kashish-Sharma** [comment]
Thanks!
