### ISSUE TITLE
"relevance" metric from trakt API

### ISSUE THREAD

**Issue by GhalebKhaled** [trakt/api-help#84]
Hi,
I'm building a search page for movies and TV series as well, so now I'm stuck when trying to merge results, I want to have something like "relevance" field so I can order the results depends on their relevance to the search term.
I've checked the API but couldn't find that metric, is there a way I can get it? if not, I'd assume you already have that metric when sorting the results before returning it from the API, how about adding that to the response?

**Comment by tysonkerridge** [comment]
There’s already a `score` parameter in the results for the “get text query results” search endpoint (https://trakt.docs.apiary.io/#reference/search/get-text-query-results). Is that not what you’re after?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GhalebKhaled** [comment]
thanks @tysonkerridge 
yes seems like this is what I'm looking for, the reason I didn't notice this field as it's not added in the python library I'm using
https://github.com/moogar0880/PyTrakt

**Comment by tysonkerridge** [comment]
Fair enough! If it helps, the API supports retrieving movies and shows at the same time, by passing multiple `type` parameters. Eg. 
```
/search/movie,show?query=tron
```
You might have to make some changes to the library directly if it’s not set up to do that. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GhalebKhaled** [comment]
thanks, this is a good information.
I've opened an issue on the repo but seems like it's not very active, so I think I'd go an support both the `score` and the mixed types

thanks again for the help @tysonkerridge
