### ISSUE TITLE
Q: Use tmdbid from episodes in TMDB API?

### ISSUE THREAD

**Issue by Michelasso** [trakt/api-help#85]
For example when I get the trakt user history I can receive a list of episodes. Each episode has its own tmdbid (different from show's ID). Using that tmdbid in the TMDB API either fails (no entry) or returns random items.

I see the TMDB API references episodes by ShowID/Season Number/Episode number. But I hoped I could use that tmdbid instead. Otherwise what's that ID for? From where and why Trakt gets it?

PS: This is a question but I don't know how to mark the issue as such.

**Comment by tysonkerridge** [comment]
Without knowing too much about the TMDb API or the actual reason behind those IDs being there, my guess is that those IDs would be used to add those items to lists or something. If you’ve got the episodes from Trakt, then you likely have the episode/season number etc so should be able to access the TMDb endpoints using what they expect. You likely want to check the TMDb endpoints for ones which take IDs and that’s probably your answer 🙂. 

That said, feel free to wait and see if there’s an official answer.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Michelasso** [comment]
Yeah, it's just that using a simple tmdbid for everything would have simplified my code quite a bit. Although I'm afraid TMDB doesn't use them for episodes. The question is what those ids (which do return all different 5-6 digits numbers, instead of returning NIL) are in the Trakt APIs at this point. But thanks. 😉

**Comment by sttz** [comment]
They are TMDB's IDs it uses internally to identify episodes. The API intentionally doesn't use them to make queries more resilient against episodes being deleted or moved.

See the answer to this question: https://www.themoviedb.org/talk/5c9c25699251410a6c0a02f4

So the ID is only informational, you can use it to check if two episodes are the same but can't use it to look up episode details via TMDBs API.

**Comment by Michelasso** [comment]
Aww... Ok. So they have their use but only for that particular function. I'll better rewrite my data model. then... Thanks!
