### ISSUE TITLE
Lists containing movie do not return my personal lists ONLY

### ISSUE THREAD

**Issue by igorissen** [trakt/api-help#87]
Hi,

Is it normal that this call doesn't return my personal lists but personal lists from the community ? Is there an option to get only user lists ?

```
GET /movies/deadpool-2016/lists? HTTP/1.1
Host: api.trakt.tv
trakt-api-version: 2
trakt-api-key: SOMETHING-HERE
Accept: application/json
```

[https://trakt.docs.apiary.io/#reference/movies/lists/get-lists-containing-this-movie](https://trakt.docs.apiary.io/#reference/movies/lists/get-lists-containing-this-movie)

**Comment by rectifyer** [comment]
Yes, that method returns community lists. To check your own lists, you should first cache your lists locally, then compare locally as well. We don’t have a method to check items per user list, because that would be way too much of a performance hit.
