### ISSUE TITLE
Compressed (gzip) responses shorter than advertised

### ISSUE THREAD

**Issue by UweTrottmann** [trakt/api-help#88]
It appears trakt server responses are sometimes compressed now (`Content-Encoding: gzip`). In that case parsing the response fails (not sure if in all cases) because the JSON body ends prematurely (`java.io.EOFException: source exhausted prematurely` error from okio).

- This is based on multiple error reports from different devices using SeriesGuide.
- I could not verify this as in my tests responses were never compressed. Is there a condition (e.g. JSON length) when responses are compressed? Is this maybe a Cloudflare issue (e.g. body is compressed twice)?

**Comment by rectifyer** [comment]
Hmm, we haven’t changed anything with gzip compression and I thought it was always enabled. I suggest always using gzip, is that possible for you? I think as long as the correct header is sent indicating gzip is supported, the api should return that format.

**Comment by UweTrottmann** [comment]
I'm sorry, my fault. My test requests are actually compressed (and working fine), I just logged at the application instead of the network level using OkHttp.

So closing this as I believe this must then be a fault somewhere between trakt servers and the end user devices.
