### ISSUE TITLE
Status code 400 while signing in.

### ISSUE THREAD

**Issue by Kashish-Sharma** [trakt/api-help#89]
When signing in by entering `username` and `password`, we're getting a 400 error, but everything works fine when signing in via `google` etc.

**Comment by rectifyer** [comment]
In your app, are you using the `trakt.tv` or the `api.trakt.tv` domain? (it should be the main `trakt.tv` domain for all authentication UI)

A 400 error could be an issue with a local ad blocker or VPN as well. I think I've seen similar errors in Android apps in the past and it ended up being an ad blocker.

**Comment by Kashish-Sharma** [comment]
I'm using the URL mentioned in docs to receive the auth token,
`https://api.trakt.tv/oauth/authorize?response_type=code&client_id=%20&redirect_uri=%20&state=%20`
 It should be something like `https://trakt.tv/oauth/authorize` ?

**Comment by tysonkerridge** [comment]
Yep, use the `https://trakt.tv/oauth/authorize` one. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Kashish-Sharma** [comment]
`https://trakt.tv/oauth/authorize` works!!
Thanks a lot.
