### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by enigmadevs** [trakt/api-help#90]
I'm receiving error 500 in all request since 3 hours. Last night was 502 for an hour. Is this normal?

**Comment by tysonkerridge** [comment]
Been seeing similar issues. A tonne of 500s, 503s, 401s and even some 403s. From when I started seeing them, status.trakt.tv had some outages once or twice an hour or two later but that’s all. Seems really hit and miss. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ndcg91** [comment]
Hi! same here.... impossible to have an stable aplication with this issues. Please help!!

**Comment by eliehaykal** [comment]
The api has been unstable since the past 18 hours.

**Comment by rectifyer** [comment]
Sorry about this. Some of the api servers had failing disks. I fixed that this morning and things are returning to normal.
