### ISSUE TITLE
Invalid comment object

### ISSUE THREAD

**Issue by kevincador** [trakt/api-help#91]
One of the comment API endpoint gave us an "invalid" object today:

```json
{
	"type": "doorkeeper::application",
	"comment": {
		"id": 241897,
		"comment": "A little PC crap here and there, but not too much so far.",
		"spoiler": false,
		"review": false,
		"parent_id": 0,
		"created_at": "2019-07-20T14:00:10.000Z",
		"updated_at": "2019-07-20T14:00:10.000Z",
		"replies": 0,
		"likes": 0,
		"user_rating": null,
		"user": {
			"username": "hildebread",
			"private": true,
			"ids": {
				"slug": "hildebread"
			}
		}
	}
}
```

The comment type is `doorkeeper::application` which makes our parsing fail.

Checked on Trakt.tv and it's also failing with a 500 error: https://trakt.tv/comments/241897

Don't know what happened 🤷‍♂️

**Comment by rectifyer** [comment]
Very strange! I only see this single comment with this issue. It seems to be a glitch and so far I can't reproduce it at all. To solve the issue, I removed the comment.
