### ISSUE TITLE
Api not working correctly 

### ISSUE THREAD

**Issue by chief-gif** [trakt/api-help#93]
============================�I went to�https://trakt.docs.apiary.io/#reference/sync/add-to-collection/add-items-to-collection?console=1
and tried this
trakt-api-key: ae1749d8db451e28a76178ec011057ef5fd8d58d75347fda1f194c95e0c017bc�Authorization: Bearer [access_token] (Replaced with my key)
and for body:�{"shows":[{"ids":{"imdb":"tt8115460"}}]}
and it returns�{"added":{"movies":0,"episodes":0},"updated":{"movies":0,"episodes":0},"existing":{"movies":0,"episodes":0},"not_found":{"movies":[],"shows":[],"seasons":[],"episodes":[],"people":[]}}
So nothing was added to my collections.
Now when I do the same for�tt0898266
Meaning sending this as body
{"shows":[{"ids":{"imdb":"tt0898266"}}]}
I can see that in my collection.
 Please debug this at your end, there's an issue with your api.

The actual episode is listed with an IMDB link as well.

**Comment by rectifyer** [comment]
Not an API bug per se, but rather a data issue with multiple shows having that same IMDB ID. In the future, what you can do is search by IMDB ID on the website, then if it finds duplicate shows please post a public support.trakt.tv idea with the correct link to keep, and the bad links that should be removed.

I removed the incorrect duplicate so this API call will work once the cache expires in a few hours. I'd also recommend caching the Trakt ID in your app, which is a unique identifier.
