### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ndcg91** [trakt/api-help#95]
Some days ago we were getting error 500 and other kind of errors apparently because a server issue... These errors has returned and now the api is really slow when it is working and just firing up 500 502 and so on.

**Comment by enigmadevs** [comment]
Same here. Today my app is receiving 502 error constantly. Users are going mad because can't sync their data with trakt.

**Comment by rectifyer** [comment]
I upgraded the API servers and added more capacity today. This should allow more requests to be processed and reduce (or hopefully eliminate) the 500 errors.

**Comment by enigmadevs** [comment]
Sorry but error 502 it's happening again. Users can't sign in Trakt.
