### ISSUE TITLE
Getting 503 response for API requests

### ISSUE THREAD

**Issue by Amuktha-headrun** [trakt/api-help#98]
I've created new app and signed up for API. My app is approved. Completed the authorization process and got the access token and refresh tokens as well. I'm following the steps given in API doc and also the code snippet given for python. Gave correct client id and access toke. Yet I'm getting request forbidden - 403 response code and unable to fetch data from API
>>> from urllib2 import Request, urlopen 
>>> 
>>> headers = { 
... 'Content-Type': 'application/json', 
... 'trakt-api-version': '2', 
... 'trakt-api-key': '[50f59bb6898b836fe19a74226a68710955cd19b48856f70fa1d4e224c03622a4]', 
... 'Authorization': 'Bearer [895d8e13b2eeaee449ce46d55d8792ce0400b112402a32d3bb65509a840f40e3]' 
... } 
>>> request = Request('https://api.trakt.tv/calendars/all/shows/start_date/days', headers=headers) 
>>> 
>>> response_body = urlopen(request).read() 

**I've written to trackttv support and got reply as follows**

> Remove the [ ] around your api key and access token, that should get it working.
> 
> For future API questions, please post in the GitHub project. Thanks!"

But after following the above suggestion, I'm still facing 500 response status now. Please help me with this
>>> from urllib2 import Request, urlopen
>>> 
>>> headers = {
...   'Content-Type': 'application/json',
...   'Authorization': 'Bearer f44b9f99aeaa3a0d8ecf421508ff983585e966497b2cfb77b7b8cda4412b869c',
...   'trakt-api-version': '2',
...   'trakt-api-key': '4403c635e068424536af745657c97aa12f245faa84cdee30d01ad73b79b5dcd2'
... }
>>> request = Request('https://api.trakt.tv/calendars/my/shows/start_date/days', headers=headers)
>>> 
>>> response_body = urlopen(request).read()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
**urllib2.HTTPError: HTTP Error 500: Internal Server Error**

**Comment by rectifyer** [comment]
`start_date` and `days` are parameters you need to either set or remove (since they are optional on this method). The API docs indicate the parameters and has examples how they can be used.

https://trakt.docs.apiary.io/#reference/calendars/my-shows/get-shows

**Comment by Amuktha-headrun** [comment]
Thanks! missed that part!!
