### ISSUE TITLE
Episode title to watched progress

### ISSUE THREAD

**Issue by GerbenBornebroek** [trakt/api-help#99]
I am trying to add the titles of my watched episodes. I am now outputting the show slug + season number and episode number. Here is the result.

```
stranger-things

1
1
2
3
4
5
6
7
8

2
1
2
3
4
5
6
7
8
9

3
1
2
3
4
5
6
7
8
```

How can I add the episode titles to the numbers? Is there a method for this?

**Comment by tysonkerridge** [comment]
I’m assuming you’re using [Get Watched](https://trakt.docs.apiary.io/#reference/users/watched/get-watched) for that information? You’d need to pair that with caching of the episodes from something like [Get all seasons, using the extended parameter to get episodes](https://trakt.docs.apiary.io/#reference/seasons/summary/get-all-seasons-for-a-show).

Alternatively you can use the [Get Watched History](https://trakt.docs.apiary.io/#reference/users/history/get-watched-history) to get the episodes depending on your use case.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by GerbenBornebroek** [comment]
Yes, I do indeed use the [Get Watched](https://trakt.docs.apiary.io/#reference/users/watched/get-watched) for that information. 

Also, I was thinking about using the [get a single episode for a show](https://trakt.docs.apiary.io/#reference/episodes/summary/get-a-single-episode-for-a-show) and loop through that with the season and episode numbers that I already have. But wasn't sure if that was correct and how to even do that.

My end goal is trying to get the episode title + the watched time. So apparently I can use the [Get Watched History](https://trakt.docs.apiary.io/#reference/users/history/get-watched-history) for that. 
I didn't know that I could use that since I thought that I had to use [Get Watched](https://trakt.docs.apiary.io/#reference/users/watched/get-watched) for this.

**Comment by rectifyer** [comment]
The watched history can be useful for recently watched items, but getting the full watched shows is the best way to get all the data at once. Then I'd do what Tyson mentioned and cache the show/season/episode data for the shows you need. The main key is **caching** the data locally in your app, you don't want to be looking this up all the time.
